### ISSUE TITLE
Upgrading to alpha 19 has a breaking change

### ISSUE THREAD

**Issue by httpete** [ariakit/ariakit#1089]
### Current behavior

18 was fine, after upgrading to 19:

Error in Console:
React does not recognize the `hideOnMouseLeave` prop on a DOM element

```

import {
  Menu as AriaMenu,
} from 'ariakit';

        <AriaMenu
          state={rkMenu}
          hideOnMouseLeave

**Comment by diegohaz** [comment]
That's expected. There will be breaking changes between alpha and beta versions. We'll have proper change logs on beta, but we're not there yet.

The prop has been renamed to focusOnHover.

**Comment by httpete** [comment]
OK Cool. I was surprised TypeScript didn't catch it. I changed a few props and I'm back up.
