### ISSUE TITLE
On Demo Page - Quick mouse will cause overlap of menus

### ISSUE THREAD

**Issue by httpete** [ariakit/ariakit#1091]
### Current behavior

https://ariakit.org/examples/menu-bar

I am seeing the same behavior in my local dev. You never ever want more than one menu open at a time. I am using showOnHover, but its the same with click.

For the moment the only way I can work around it is to store each menuState in an array and loop over it like this:

```
        menus.filter(m => m !== rkMenu).forEach(m => m.hide());
```

### Steps to reproduce the bug

1. Open https://ariakit.org/examples/menu-bar
2. click the right most menu and then move fast to the left over the buttons

![image](https://user-images.githubusercontent.com/1200635/157266235-983a0455-2ff2-42ec-b580-fd7d1f5a0175.png)

### Expected behavior

never have two menus up at once.

**Comment by diegohaz** [comment]
I can't reproduce it. What combination of browser/OS are you using?

**Comment by httpete** [comment]
Latest Chrome 99. Windows 10

**Comment by diegohaz** [comment]
Just tested it on Windows. I still can't reproduce it. Are you sure the reproduction steps are correct? Is it the exact same code in the example site? I ask this also because the menu position is different in your screenshot.

**Comment by httpete** [comment]
It is really odd - but this morning I cannot reproduce the issue on the sample page.
I do see this behavior on my real implementation, where the MenuButtons have  showOnHover (I am implementing a fly-out menu style).
I just updated to your latest example, using forwardRefs. I see that "more than one" behavior. Ill try to whip up a Gitpod.

**Comment by httpete** [comment]
OK  good news - everything rides on this to work right:
You need to use the forwardRef at all levels MenuBar / MenuButton / Menu
AND you need this menu.mounted. Now it is working! I will keep pumping on it.

```
  {rkMenu.mounted && (
          <AriaMenu state={rkMenu}

**Comment by diegohaz** [comment]
We use `ref` to work with the underlying HTML elements when necessary (for example, to `focus()` them). You should've seen a React warning about that if you're not using `React.forwardRef`.

Anyway, you should always use `React.forwardRef` on components passed to the Reakit/Ariakit `as` prop and/or render props (I really hope React will do this automatically on v19). But we should cover it better in the new docs.

**Comment by diegohaz** [comment]
I do see behavior similar to what you described if I pass `showOnHover` and `focusOnHover={false}` to the menu bar `<MenuButton as={MenuItem}>` component, and I click on the menu bar item. But that's the expected behavior given the props passed: since the other hovered menu bar items aren't receiving focus, the focused menu will not hide.

We can't make it a hard rule that only one menu should be visible. We just make it the default when using the default props.

There are UIs where two menus should be simultaneously visible. Here's an example on the macOS menu bar:

<img width="690" alt="Screenshot of macOS menu bar with the help menu open with a search query and a second menu open indicating where that item is placed" src="https://user-images.githubusercontent.com/3068563/157610960-e11422bd-4b27-4575-9f5e-86d638d72f83.png">

**Comment by httpete** [comment]
These are combinations I am playing with, so this is very helpful thank you.For WCAG 1.2 compatibility, my requirement is that I do NOT steal focus from the page, but then hovering over the menu opens one and only one. This is the most Aria compliant form of a flyout menu paradigm.We still don't want more than one open in this scenario.
    On Thursday, March 10, 2022, 02:36:26 AM EST, Haz ***@***.***> wrote:  
 
 


I do see behavior similar to what you described if I pass showOnHover and focusOnHover={false} to the menu bar <MenuButton as={MenuItem}> component, and I click on the menu bar item. But that's the expected behavior given the props passed: since the other hovered menu bar items aren't receiving focus, the focused menu will not hide.

We can't make it a hard rule that only one menu should be visible. We just make it the default when using the default props.

There are UIs where two menus should be simultaneously visible. Here's an example on the macOS menu bar:



—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by diegohaz** [comment]
I'd say set focusOnHover to true when there's another menu bar element with focus. This way you aren't stealing focus from another part of the app. The user is already interacting with the menu bar, that should behave as a single widget. You can pass a function to focusOnHover and return true or false so you can do it dynamically.

Let me know if that works and I'll see if focusOnHover can work like that by default.

**Comment by httpete** [comment]
Ill try - it's interesting how difficult it is to get all of the behaviors correct according to WCAG.By rule, if the user hasn't clicked, then you should not steal their focus. If I set showOnHover for the menu, it should work this way. Otherwise, it steals focus from where they are. Once they click, that gets focus.
    On Thursday, March 10, 2022, 07:16:04 PM EST, Haz ***@***.***> wrote:  
 
 


I'd say set focusOnHover to true when there's another menu bar element with focus. This way you aren't stealing focus from another part of the app. The user is already interacting with the menu bar, that should behave as a single widget. You can pass a function to focusOnHover and return true or false so you can do it dynamically.

Let me know if that works and I'll see if focusOnHover can work like that by default.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by httpete** [comment]
@diegohaz first and foremost THANK  YOU.
Right now, I have 

```
<MenuBar>
<Menu
            toggleOnClick={false}
            showOnHover >
            <MenuItem focusOnHover={false}>
            ````


But I do see that focus gets stolen by the Menu.

**Comment by httpete** [comment]
Today, I see it again clear as day:

![image](https://user-images.githubusercontent.com/1200635/157915159-fd1e136e-1dfc-48af-9250-0259731973dc.png)

**Comment by diegohaz** [comment]
I can't reproduce it on any browser (both on macOS and Windows). I don't know how I can help.

**Comment by httpete** [comment]
Every day, I try and I can reproduce it so easily. 
If you would like we can do a remote session and I can show you. I am worried this isn't just me / my browser.

**Comment by diegohaz** [comment]
I see. Let's keep it open and see if other people chime in. I also spotted some issues with mobile that may be related to your case (are you using a touch screen?).

**Comment by httpete** [comment]
Wow - amazing catch. I DO have a touch screen on this Dell laptop. I am using it on an external 4K monitor though - I am not using touch.
I think this is gonna be common.

**Comment by httpete** [comment]
Still see this on the latest alpha.20

**Comment by httpete** [comment]
I can report @diegohaz - the demo page works PERFECTLY for me today. Ill keep checking as I go. Thank you.
