### ISSUE TITLE
[v2] Tooltip throws a console.error when using auto placements

### ISSUE THREAD

**Issue by georgekaran** [ariakit/ariakit#1117]
### Current behavior

When using `auto` placements the Tooltip throws a `console.error` with the following message:
```bash
Popper: "auto" placements require the "flip" modifier be present and enabled to work.
```

PS: Setting the `flip` property to either false or true doesn't change the outcome.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/focused-hypatia-ubj3dm?file=/src/index.js
2. See console logs

### Expected behavior

The app should not throw an error when using auto placements.

**Comment by georgekaran** [comment]
Just opened a [PR](https://github.com/ariakit/ariakit/pull/818) to fix this issue.

**Comment by diegohaz** [comment]
Hey @georgekaran! Could you please describe your use case for the auto placements? I was thinking about removing support for it on v2.

**Comment by georgekaran** [comment]
Hey!

As of today, we don't have any use case for the auto placements at @croct-tech, we only report this because in our unit tests the output was overloaded with `console.error`.

Plus, we don't have any plans to use it since we go for fixed placements most of the time.
