### ISSUE TITLE
Can I stop the "composite" behavior on MenuBar?

### ISSUE THREAD

**Issue by httpete** [ariakit/ariakit#1134]
### Motivation

We want to have all the features of the MenuBar, but not the way it works out of the box.

We want TAB to cycle through each of the MenuItems in the bar, instead of the behavior where it treats the entire set as a compound tabStop, and then arrow through each. 

I tried removing the MenuBar altogether, but then I lose keyboard arrow navigation within.

**Comment by httpete** [comment]
I came up with this:

```
<MenuBar
        onKeyDown={e => {
          e.stopPropagation();
          if (e.key === 'Tab') {
            let n;
            if (!e.shiftKey) {
              n = menubar.next();
            } else {
              n = menubar.previous();
            }
            menubar.move(n);
          }
        }}

**Comment by diegohaz** [comment]
You can pass `tabIndex={0}` to the items.

**Comment by httpete** [comment]
It works perfectly thank you! I made my own function as above, but your solution is much better.
