### ISSUE TITLE
id's getting re-generated making snapshots unstable

### ISSUE THREAD

**Issue by httpete** [ariakit/ariakit#1232]
### Current behavior

I have unit tests that will fail every time they are run:

```
  -     id="id-bc3j4k"
    +     id="id-podxsh"

**Comment by diegohaz** [comment]
See https://github.com/ariakit/ariakit/discussions/1143#discussioncomment-2438886

**Comment by httpete** [comment]
Cool @diegohaz  by the way - performance is MUCH better in the new .next version! I actually had to use lazy loading before to get decent performance now it rocks.

How will React 18 fix this id issue? Possibly I will just wait for that.

**Comment by diegohaz** [comment]
> How will React 18 fix this id issue? Possibly I will just wait for that.

Ariakit uses the new React 18's [`useId`](https://reactjs.org/blog/2022/03/29/react-v18.html#useid) if it's available. It generates deterministic IDs, so your snapshots wouldn't fail. When using React 17, it fallbacks to generating a random ID on the client-side.
