### ISSUE TITLE
Demo page for MenuBar has strange overlap

### ISSUE THREAD

**Issue by httpete** [ariakit/ariakit#1267]
### Current behavior

Looks fine in my app, but JAHU on the demo.

![image](https://user-images.githubusercontent.com/1200635/164762988-1b8d6492-5613-4225-8ca8-ee4a4b36ad9e.png)

### Steps to reproduce the bug

1. Open https://ariakit.org/examples/menu-bar

### Expected behavior

look right aligned to the bottom of menu button.

### Possible solutions

.

**Comment by diegohaz** [comment]
Are you still using the touchscreen laptop with Windows 10 and Chrome 99? Are you able to try it on another device? I remember this issue was present in your screenshot on #1091, but I could never reproduce it. I have macOS, Windows, iPad, iPhone, and Android, but none of them have this issue.

@atomiks Do you think it could be related to Floating UI?

**Comment by atomiks** [comment]
@diegohaz we never got reports of "overlapping" as seen in the screenshot in Popper and that was with a ton of usage

**Comment by httpete** [comment]
> Are you still using the touchscreen laptop with Windows 10 and Chrome 99? Are you able to try it on another device? I remember this issue was present in your screenshot on #1091, but I could never reproduce it. I have all browsers on macOS, Windows 10/11 (on PC and Mac), iPad, iPhone, and Android, but none of them have this issue.
> 
> Here are a few things to try, if you can:
> 
> * Anonymous tab (without extensions).
> * Different browser.
> * Different devices.
> 
> @atomiks Do you think it could be related to Floating UI/Popper.js?

Exact same look on Firefox, and Edge. I just verified on my other laptop and it DOES look fine.  Maybe it's this flash code renderer thing?

**Comment by diegohaz** [comment]
> Maybe it's this flash code renderer thing?

What do you mean?

**Comment by httpete** [comment]
When I right click on your demo I get a notice about Flash. Really odd..

**Comment by diegohaz** [comment]
That's weird. There's no Flash on the site.

**Comment by httpete** [comment]
I would think it’s some extension but I see the exact same in the three browsers and they are virgin

**Comment by httpete** [comment]
@diegohaz If I right click anywhere on your demo page I get:

![image](https://user-images.githubusercontent.com/1200635/165199240-f6ffe525-2783-4fdc-874c-1639d67727a4.png)

**Comment by httpete** [comment]
Really strange. I don’t have the problem I originally reported but I don’t even have to try to get that strange placement. It was perfect one release ago. 

It’s just a Dell Inspiron laptop it does have a touchscreen but I am using a 4K monitor
