### ISSUE TITLE
Support drag-to-select on select/menu.

### ISSUE THREAD

**Issue by latin-1** [ariakit/ariakit#1345]
### Motivation

Sorry I don't know the exact name of this UX.

![image](https://user-images.githubusercontent.com/44946699/168086991-77520317-054d-46e8-8a8d-aeebd750d3ae.png)

It's a common pattern and should be supported in Ariakit.

### Usage example

- Browsers' native `<select>` and menu/context menu.
- React Spectrum ([Picker](https://react-spectrum.adobe.com/react-spectrum/Picker.html) and [Menu](https://react-spectrum.adobe.com/react-spectrum/Menu.html))
- Radix UI ([Select](https://www.radix-ui.com/docs/primitives/components/select), [Dropdown Menu](https://www.radix-ui.com/docs/primitives/components/dropdown-menu) and [Context Menu](https://www.radix-ui.com/docs/primitives/components/context-menu))

**Comment by diegohaz** [comment]
Thanks for suggesting this feature @latin-1.

We've tried this at some point in the past and observed it had some inconsistent behaviors (especially when you consider touch devices, different/multiple pointers, and swipe to scroll). So we decided to support only full clicks by default.

Nonetheless, this behavior is not a standard across all platforms. Windows, for example, doesn't work like that.

That being said, if you really need this behavior in your app, you can do this by opting out of the default behavior and adding the event handler yourself:

```jsx
<SelectItem
  value="Banana"
  hideOnClick={false}
  setValueOnClick={false}
  onMouseUp={() => {
    select.hide();
    select.setValue("Banana");
  }}
/>
```
