### ISSUE TITLE
Set `inert` and `style="pointer-events: none"` while `[data-leave]` for DisclosureContent.

### ISSUE THREAD

**Issue by latin-1** [ariakit/ariakit#1350]
### Motivation

During the hide animation, disclosure content should be inert.

**Comment by diegohaz** [comment]
That's interesting. Have you faced any issues related to this behavior (or the lack of it)? It would help to understand the motivation if you could describe that.

That being said, you can do something like this already:

```jsx
const state = useDisclosureState();
const inert = state.animating;
```
