### ISSUE TITLE
Do not prepend hidden dialog dismiss if both `hideOnEscape` and `hideOnInteractOutside` are set to `false`.

### ISSUE THREAD

**Issue by latin-1** [ariakit/ariakit#1356]
### Motivation

Sometimes, we make a dialog non-dismissible intentionally and might require some user actions to show the dismiss button. In this case, we should not prepend the hidden dismiss.

```tsx
<Dialog hideOnEscape={false} hideOnInteractOutside={false} />
```

**Comment by diegohaz** [comment]
If you want to hide that button, just render a hidden `<DialogDismiss>` yourself:
```jsx
<DialogDismiss hidden />
```
