### ISSUE TITLE
`animated: true` is not reliable.

### ISSUE THREAD

**Issue by latin-1** [ariakit/ariakit#1357]
### Current behavior

Dialog cannot be fully closed.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/awesome-wave-n79cp7
2. Double click the button

### Expected behavior

Dialog closes properly.

### Possible solutions

Use a timeout in ms might help.
https://reactcommunity.org/react-transition-group/transition#Transition-prop-timeout

**Comment by diegohaz** [comment]
The `animated` prop accepts a number, which is the animation duration in ms.

But your code has a bug. You forgot to set [`transition-property`](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-property).

**Comment by latin-1** [comment]
> The animated prop accepts a number, which is the animation duration in ms.

I didn't know before! Thanks for explaining.

> But your code has a bug. You forgot to set [transition-property](https://developer.mozilla.org/en-US/docs/Web/CSS/transition-property).

I add the `transition-property`, and the bug still exists. I believe this bug is caused by dismissing dialog during the enter animation. Setting the `transition-duration` to a larger value could make it easier to reproduce.

**Comment by diegohaz** [comment]
I can't reproduce it after adding `transition-property`: https://codesandbox.io/s/brave-lamarr-77z84m?file=/src/dialog-animated.tsx

**Comment by latin-1** [comment]
It's weird. I can still reproduce this bug in my browser. But on another device, it seems to work fine. Let me close this issue for now.
