### ISSUE TITLE
[Button]: "as" prop throws TS error when used within a wrapper component

### ISSUE THREAD

**Issue by knoefel** [ariakit/ariakit#1362]
### Current behavior

I'm not 100% sure i'm doing something wrong here, but when i try to wrap the `<Button />` component and pass the props `ButtonOptions<'button'>` i get a TS error.

<img width="1248" alt="Screenshot 2022-05-15 at 16 16 33" src="https://user-images.githubusercontent.com/2396344/168477386-f1ed292f-24be-407d-bb0a-5018ba3fd2b9.png">

```typescript
import { Button as AriaButton, ButtonOptions } from 'ariakit/button';
import { FC } from 'react';

type ButtonProps = ButtonOptions<'button'>;

export const Button: FC<ButtonProps> = ({ children, ...props }) => <AriaButton {...props}>{children}</AriaButton>;
```

### Steps to reproduce the bug

[![Edit charming-nightingale-lb7s70](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-nightingale-lb7s70?fontsize=14&hidenavigation=1&theme=dark)

### Expected behavior

It is possible to use the` <Button />` component as wrapper component and pass/use the corresponding props.

Thx in advance for any feedback on this!!

**Comment by diegohaz** [comment]
You have to annotate your component with generics so the `as` prop works properly. Example: https://codesandbox.io/s/wrapping-ariakit-with-as-prop-0gx4m6

In the example above, I'm also including `forwardRef`, which you usually want to do if you're wrapping Ariakit components.

**Comment by selvinkuik** [comment]
Hijacking this thread as I'm not sure my query deserves a new post, but I believe I have a similar issue with the `MenuItem` component. I'm attempting to create a submenu in Typescript, this is my submenu component:

```
import { forwardRef } from 'react'
import { useMenuState, Menu, MenuItem, MenuButton, MenuSeparator } from 'reakit/Menu'

export const PreferencesMenu = forwardRef<HTMLButtonElement>((props, ref) => {
  const menu = useMenuState()
  return (
    <>
      <MenuButton ref={ref} {...menu} {...props}>
        Preferences
      </MenuButton>
      <Menu {...menu} aria-label="Preferences">
        <MenuItem {...menu}>Settings</MenuItem>
        <MenuItem {...menu} disabled>
          Extensions
        </MenuItem>
        <MenuSeparator {...menu} />
        <MenuItem {...menu}>Keyboard shortcuts</MenuItem>
      </Menu>
    </>
  )
})
```

And this is how I am including it:

```
...
return (
  <>
    <MenuButton {...menu}>
      Menu
    </MenuButton>
    <Menu {...menu}>
      <MenuItem {...menu} as={PreferencesMenu} />
    </Menu>
  </>
)
```

However, I am getting:

```
Type 'ForwardRefExoticComponent<RefAttributes<HTMLButtonElement>>' is not assignable to type '"button"'.
```

The problem is likely my understanding of Typescript and Reakit, however I'm a little stumped on which direction to turn...

**Comment by diegohaz** [comment]
@selvinkuik You must type your `PreferencesMenu` props:

```tsx
forwardRef<HTMLButtonElement, React.ButtonHTMLAttributes<HTMLButtonElement>>
```

**Comment by selvinkuik** [comment]
@diegohaz Thanks for replying. Just tried this but I'm still facing type issues. Based on my understanding, this is the new implementation:

```
import { forwardRef } from 'react'
import { useMenuState, Menu, MenuItem, MenuButton, MenuSeparator } from 'reakit/Menu'

export const PreferencesMenu = forwardRef<
  HTMLButtonElement,
  React.ButtonHTMLAttributes<HTMLButtonElement>
>((props, ref) => {
  const menu = useMenuState()
  return (
    <>
      <MenuButton ref={ref} {...menu} {...props}>
        Preferences
      </MenuButton>
      <Menu {...menu} aria-label="Preferences">
        <MenuItem {...menu}>Settings</MenuItem>
        <MenuItem {...menu} disabled>
          Extensions
        </MenuItem>
        <MenuSeparator {...menu} />
        <MenuItem {...menu}>Keyboard shortcuts</MenuItem>
      </Menu>
    </>
  )
})
```

However, I'm still getting a similar error. Now:

```
Type 'ForwardRefExoticComponent<ButtonHTMLAttributes<HTMLButtonElement> & RefAttributes<HTMLButtonElement>>' is not assignable to type '"button"'.
```

**Comment by diegohaz** [comment]
@selvinkuik Could you please open a new issue? A CodeSandbox repro would help as well.
