### ISSUE TITLE
Support search using label string for Select

### ISSUE THREAD

**Issue by devchn** [ariakit/ariakit#1414]
### Motivation

Sorry, my English is not very good.

Only can search using value now.

But there are some cases, the label and value seen by the user are not the same. When users search, they should enter a label string instead of a value.

Should be searched by label string and then clicked to get value.

Hope to support Select with labels.

**Comment by diegohaz** [comment]
What do you mean by search on Select? Do you mean the typeahead functionality (pressing the first character of an item moves focus to it)?

A design / usage example with what you're referring to would help.

**Comment by devchn** [comment]
Thank you for helping me.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/22728668/170417507-1a8152e9-3f17-48e1-9af2-965e1f6fe158.png">

The value is "Apple". But "Apple" have some translations. e.g. "苹果" and "Apple".

When the user is Chinese, he will type Chinese on the search field. And then the list appears "苹果" item. And then he will click the "苹果" item. Finally, get the "Apple" value.
When the user is English, he will type English on the search field. And then the list appears "Apple" item. And then he will click the "Apple" item. Finally, get the "Apple" value.

But it only has value now.

**Comment by devchn** [comment]
https://codesandbox.io/s/cgdzjr?module=src/select-combobox.tsx

**Comment by devchn** [comment]
I seem to find that I can pass the label to the value of the combobox. Then convert the label string to value and pass it to Select. It doesn't seem to be a problem. I'm sorry to bother you. I feel the problem has been solved. It's my problem. I'm sorry.

**Comment by diegohaz** [comment]
No worries. I'd love to see your solution.

**Comment by devchn** [comment]
Idea:
search string => value => label


User types and selects by the search string.
Get the value by the search string.
Get the label by the value.


https://codesandbox.io/s/thirsty-stitch-1her0y?file=/src/App.tsx:0-2667

```javascript
import "./styles.css";
import {
  getCountries,
  getCountryCallingCode,
  CountryCode
} from "libphonenumber-js";
import { useTranslation, translation, Language } from "react-t9n";
import {
  Combobox,
  ComboboxItem,
  ComboboxList,
  useComboboxState
} from "ariakit/combobox";
import {
  Select,
  SelectItem as OriginSelectItem,
  SelectPopover,
  useSelectState
} from "ariakit/select";
import { useDeferredValue } from "react";
import styled from "styled-components";

const appTranslation = translation({
  [Language.Chinese]: {
    US: "美国",
    CN: "中国"
  },

  [Language.English]: {
    US: "America",
    CN: "China"
  }
});

const SelectItem = styled(OriginSelectItem)`
  display: flex;
  justify-content: space-between;
`;

export default function App() {
  const { t } = useTranslation(appTranslation);
  const search2ValueMap = getCountries() // e.g. ["CN", "US", ...]
    .reduce((map, value) => {
      const search = `${t(value)}+${getCountryCallingCode(value)}`; // e.g. "China+86". Allow users to search by "CN" or "86"
      map[search] = value;
      return map;
    }, {} as Record<string, CountryCode>); // .e.g. {"China+86": "CN", "America+1": "US", ...}
  const searchList = Object.keys(search2ValueMap);

  const combobox = useComboboxState({
    list: searchList,
    gutter: 4,
    sameWidth: true
  });
  useDeferredValue(combobox.value);
  const { value: search, setValue: setSearch, ...selectProps } = combobox;

  const select = useSelectState({ ...selectProps, defaultValue: "US" });

  if (!select.mounted && search) {
    setSearch("");
  }

  const getLabel = (value) => (
    <>
      <span>{t(value)}</span>
      <span>+{getCountryCallingCode(value)}</span>
    </>
  );

  return (
    <div className="App">
      <div>Select value: {select.value}</div>
      <Select state={select} className="select">
        {t(select.value)}
      </Select>
      <SelectPopover state={select} composite={false} className="popver">
        <Combobox
          state={combobox}
          autoSelect
          placeholder="Search..."
          className="combobox"
        />
        <ComboboxList state={combobox} className="combobox-list">
          {combobox.matches.map((search, i) => {
            const value = search2ValueMap[search];
            return (
              <ComboboxItem key={value} focusOnHover className="select-item">
                {(props) => (
                  <SelectItem {...props} value={value}>
                    {getLabel(value)}
                  </SelectItem>
                )}
              </ComboboxItem>
            );
          })}
        </ComboboxList>
      </SelectPopover>
    </div>
  );
}

```
