### ISSUE TITLE
An error occurs when Select is used with react-window.

### ISSUE THREAD

**Issue by devchn** [ariakit/ariakit#1423]
### Current behavior

<img width="938" alt="image" src="https://user-images.githubusercontent.com/22728668/170614792-d9bff9bd-a810-41dc-b748-c8ab75f858f0.png">

When used with react-window, an error occurs.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/great-christian-1kqj1u?file=/src/App.tsx
2. An error occurs when using 97 to 110 of code. It is no problem when using 112 to 124 lines of code.
3. See Error
<img width="938" alt="image" src="https://user-images.githubusercontent.com/22728668/170614792-d9bff9bd-a810-41dc-b748-c8ab75f858f0.png">

### Expected behavior

Can be used with react-window.

**Comment by diegohaz** [comment]
You're re-mounting the `<FixedSizeList>` children on every render. This causes the combobox/select item to be registered/unregistered to the state on every render, thus the error.

If you look at the react-window examples (https://react-window.vercel.app/#/examples/list/fixed-size), you'll see that the List children are defined at the module top-level (so the reference is stable).

That said, I'm not sure react-window is a good choice. Virtualization is hard, especially combined with composite widgets, where you also need to take focus management into account. If you really need virtualization, I know some people had success using [react-virtual](https://github.com/TanStack/react-virtual) with Ariakit.

But in your example, you have less than 300 items. You don't need virtualization in this case. If you're experiencing performance issues, there are easier ways to fix them, like [state colocation](https://kentcdodds.com/blog/state-colocation-will-make-your-react-app-faster).

**Comment by devchn** [comment]
Ok. Thank you very much. I have known how to do that.
