### ISSUE TITLE
[v2] Rename `visible`/`setVisible` to `open`/`setOpen`

### ISSUE THREAD

**Issue by diegohaz** [ariakit/ariakit#1426]
### Motivation

I'm thinking about renaming the `defaultVisible`, `visible`, and `setVisible` props on disclosure and derived state hooks to `defaultOpen`, `open`, and `setOpen`.

The main motivation is that this is more aligned with the HTML spec, where these already exist:

```html
<details open>
<dialog open>
```

The second reason is to avoid confusion about what `visible` means. For example:

```jsx
const select = useSelectState({ visible: true })

return (
  <>
    <Select state={select} />
    <SelectPopover state={select} />
  </>
)
```

For a React developer reading that code for the first time, without previous knowledge of Ariakit, it may not be obvious whether `visible` is referring to the visibility of the whole select widget (including the select button) or only the popover.

With `open`, even if you consider the select button element, it still makes sense since a select button being "open" means its popover is being displayed:

```jsx
const select = useSelectState({ open: true })

return (
  <>
    <Select state={select} />
    <SelectPopover state={select} />
  </>
)
```

### Usage example

```jsx
const disclosure = useDisclosureState({ open: true })
disclosure.setOpen(false)
```

### Possible implementations

We basically have to change the implementation and types on the disclosure state and adapt the rest of the code.

**Comment by harshilparmar** [comment]
Can I work on this one ? I guess this is the best issue to start contribute to Ariakit.

**Comment by diegohaz** [comment]
@harshilparmar Yeah, sure!

**Comment by DaniGuardiola** [comment]
Another point in favor of this is the fact that if your component is animated, setting `visible` to `false` is a bit of a lie for whatever the duration of your exit animation is :)
