### ISSUE TITLE
Remove `modal` prop from `ComboboxPopover`

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1455]
### Current behavior

Clicking on the input more than once makes the popup flash.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/1f0t72?module=src/combobox.tsx
2. Click on the input
3. Click again

### Expected behavior

Popover to keep open.

**Comment by marcospassos** [comment]
We need to render the popup on a portal to avoid issues related to zindex and overflow hidden.

**Comment by diegohaz** [comment]
> We need to render the popup on a portal to avoid issues related to zindex and overflow hidden.

Got it. In that case you want `<ComboboxPopover portal>`

**Comment by marcospassos** [comment]
Oh, I remember using `modal` with some early Reakit component versions. I guess it has changed at some point, right?
