### ISSUE TITLE
Combobox popup wrongly aligned to the bottom-end 

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1456]
### Current behavior

I've to admit this is a weird bug that took me 1h to find the cause: it turns out that setting the body margin to 0 makes the combobox popup get aligned to the right.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/blazing-rain-cu8rym
2. Open the modal and it should be incorrectly placed at the right
3. Open the `style.css` and remove the `margin: 0`
4. Open the modal and note it's now correctly placed at the left

### Expected behavior

Modal always aligned to the bottom-left, unless explicitly defined through the `placement` prop.

**Comment by marcospassos** [comment]
I've updated the link, sorry.

**Comment by diegohaz** [comment]
Hmm, I still can't see it.

**Comment by marcospassos** [comment]
Can you try again,  pls?

**Comment by diegohaz** [comment]
Ah, that's because the popover has a default padding to the edges of the viewport.

You can remove that with:

```jsx
useComboboxState({ overflowPadding: 0 })
```

**Comment by marcospassos** [comment]
It should definitely be documented somewhere 😅
