### ISSUE TITLE
FEATURE: FocusScope component

### ISSUE THREAD

**Issue by anuraghazra** [ariakit/ariakit#1462]
### Motivation

The current implementation of ariakit/focus-trap is simplistic and needs manual management of last and first HTML refs. 

I'm proposing a `<FocusScope />` component which will just take `children` components and automatically set last and first ref. 

### Usage example

```tsx
import { FocusScope } from 'ariakit/focus-scope'


<FocusScope>
    <button>Button 1</button>
    <button>Button 2</button>
    <button>Button 3</button>
    <button>Button 2</button>
</FocusScope>
```

### Possible implementations

[Codesandbox demo](https://codesandbox.io/s/ariakit-focus-scope-cty2mi?file=/src/App.tsx)

Uses ariakit-utils/focus' `getAllTabbableIn` function to get the last and first element refs and wraps the FocusTrap elements. 

Similar to other libraries: 

- [ReactSpectrum FocusScope ](https://react-spectrum.adobe.com/react-aria/FocusScope.html)
- [FluentUI FocusTrapZone](https://developer.microsoft.com/en-us/fluentui#/controls/web/focustrapzone)

**Comment by anuraghazra** [comment]
I'm happy to implement this component if this looks good. 

> Also, btw at my org we decided go with ariakit for building base of our accessibility foundation we will be using the Composite, FocusTraps etc.

**Comment by diegohaz** [comment]
I can see how that could be useful. We're doing something similar in the Dialog component:

https://github.com/ariakit/ariakit/blob/7b04986d9ef5aa80866a44a612aeb4846afe81a1/packages/ariakit/src/dialog/dialog.tsx#L383-L413

I'm just not sure if `FocusScope` is a good name. Maybe `FocusTrapRegion` (living inside the `focus-trap` folder)?

**Comment by anuraghazra** [comment]
Yep agree with the naming, 
Thanks I'll check out the modal implementation.
