### ISSUE TITLE
Weird scroll behavior without scroll-margins

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1501]
### Current behavior

It looks like the scroll behavior only works as expected on Chrome when using `scroll-margins` (Safari works as expected). 

https://user-images.githubusercontent.com/943036/173479325-5263c1e2-027e-49d1-a36b-a33049759525.mov

Notice in the video that the navigation "jumps" when not using the scroll margin. The problem with using scroll margin is that our DS requires padding around the listbox, and adding scroll-margin doubles the spaces at the top and bottom. 

Removing the padding makes the items "touch" the upper and bottom edges:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/943036/173480119-6aad94db-e48b-40cd-b26e-88094dd6ad9f.png">

I believe the scrolling behavior should work without CSS pre-requisites. 

Am I missing something?

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/dw2id1?module=src/select-multiple.tsx&file=/src/style.css
2. Remove the scroll-margin
3. Use the keyboard to navigate
4. Notice the navigation jumps at specific points

### Expected behavior

The last item is always aligned to the bottom.

**Comment by diegohaz** [comment]
We're not doing anything special here. That's how browser scrolling works when you `.focus()` on elements offscreen.

You can disable the default behavior and focus on the items manually:

```jsx
const select = useSelectState(...);

useEffect(() => {
  if (!select.moves) return;
  if (!select.activeId) return;
  const element = document.getElementById(select.activeId);
  if (!element) return;
  element.focus({ preventScroll: true });
  element.scrollIntoView({ block: "nearest" });
}, [select.moves]);

<SelectPopover focusOnMove={false}>
```

But we can think of an API to make this easier.

**Comment by marcospassos** [comment]
@diegohaz, why doesn't it happen on Safari? Isn't it due to [this special handling](https://github.com/ariakit/ariakit/blob/ae26bcea85691ff1c654a5c8f9fd8760a297e54d/packages/ariakit/src/composite/composite-item.tsx#L246-L249)?

> We're not doing anything special here. That's how browser scrolling works when you .focus() on elements offscreen.

In that case, should it be affecting virtual focus?

**Comment by diegohaz** [comment]
> @diegohaz, why doesn't it happen on Safari? Isn't it due to [this special handling](https://github.com/ariakit/ariakit/blob/ae26bcea85691ff1c654a5c8f9fd8760a297e54d/packages/ariakit/src/composite/composite-item.tsx#L246-L249)?

Oh yeah! Good point! We should either remove `{ block: "nearest", inline: "nearest" }` from that or apply it to all browsers.

@DaniGuardiola I know you've explored some possibilities here. What do you think?

> In that case, should it be affecting virtual focus?

Items still receive DOM focus when `virtualFocus` is set to true ([more details](https://twitter.com/diegohaz/status/1291006968103088129)). The behavior should be the same.

**Comment by marcospassos** [comment]
> Oh yeah! Good point! We should either remove { block: "nearest", inline: "nearest" } from that or apply it to all browsers.

I recommend adding it to all browsers to ensure consistency – even because this is the desired behavior in most cases.

**Comment by marcospassos** [comment]
@diegohaz, I just noticed that the keyboard navigation of the combobox with group examples has the same issue. I feel completely lost using it:

https://user-images.githubusercontent.com/943036/173671035-8ee405e6-11c7-4e52-8580-dbeef5dd5e7e.mov

Using the `scrollIntoView` should fix it.

**Comment by marcospassos** [comment]
Update: `scroll-margin` doesn't fix the issue in this case

**Comment by DaniGuardiola** [comment]
Hi there! I have run into the exact same issue, and I was working on this PR to integrate a fix like this into Ariakit: https://github.com/ariakit/ariakit/pull/1165

I'm gonna try and give some love to this PR to see if we can merge it. I need to fine-tune it and test it  more thoroughly across browsers first. We also have this fix in our codebase and it's gonna start to appear in more places too, glad to see I'm not the only one running into these issues.

In the meantime, you might find this abstraction useful (put it in a file):

```ts
import { CompositeState } from "ariakit";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useIsomorphicLayoutEffect } from "react-use";

function useScheduleFocus(activeElement?: HTMLElement) {
  const [scheduled, setScheduled] = useState(false);
  const schedule = useCallback(() => setScheduled(true), []);
  useEffect(() => {
    if (scheduled && activeElement) {
      setScheduled(false);
      activeElement.scrollIntoView({ block: "nearest" });
      activeElement.focus({ preventScroll: true });
    }
  }, [activeElement, scheduled]);
  return schedule;
}

/** Implements a a workaround for Ariakit composites by replacing the focus
 * and scroll behavior.
 *
 * Might be fixed in Ariakit soon: https://github.com/ariakit/ariakit/pull/1165
 *
 * Must be used in combination with `scrollWorkaroundCompositeProps`. */
export function useCompositeScrollWorkaround<S extends CompositeState>(
  state: S
) {
  const activeElement = useMemo(
    () =>
      state.activeId
        ? document.getElementById(state.activeId) ?? undefined
        : undefined,
    [state.activeId]
  );
  const scheduleFocus = useScheduleFocus(activeElement);
  useIsomorphicLayoutEffect(() => {
    if (!activeElement) return;
    scheduleFocus();
  }, [state.moves]);
}

/** Props to be passed to composites.
 *
 * Must be used in combination with `useCompositeScrollWorkaround`. */
export const scrollWorkaroundCompositeProps = { focusOnMove: false };
```

**Comment by DaniGuardiola** [comment]
@marcospassos care to test my PR? See if it works for groups too. If not, I appreciate any help / ideas to fix it :smile:

**Comment by marcospassos** [comment]
@DaniGuardiola, I'm trying right. Where am I supposed to use the `scrollWorkaroundCompositeProps`?

**Comment by marcospassos** [comment]
I can confirm this workaround is working with options and groups for both select and combobox:

```tsx
export function useCompositeScrollWorkaround<S extends CompositeState>(state: S): void {
    useEffect(
        () => {
            // Workaround to fix issue with keyboard navigation:
            // https://github.com/ariakit/ariakit/issues/1501#issuecomment-1155047349
            if (state.moves === 0 || !state.activeId) {
                return;
            }

            const element = document.getElementById(state.activeId);

            if (element === null) {
                return;
            }

            const scrollTarget = state.first() === state.activeId
                // If the first element, scroll to any previous element
                // to show the group label, if any
                ? (element.previousElementSibling ?? element)
                : element;

            element.focus({preventScroll: true});
            scrollTarget.scrollIntoView({block: 'nearest'});
        },
        [state.moves, state.first, state.activeId]
    );
}
```

I can't manage to make it work using your workaround, @DaniGuardiola :(

**Comment by marcospassos** [comment]
An issue with this workaround is that hovering over items on the edges scrolls the list. I appreciate it if you guys have any idea how to avoid this temporarily.

**Comment by diegohaz** [comment]
> An issue with this workaround is that hovering over items on the edges scrolls the list. I appreciate it if you guys have any idea how to avoid this temporarily.

You shouldn't be listening to `state.activeId` in the effect deps. Use something like [`useLiveRef`](https://github.com/ariakit/ariakit/blob/6985169158be5ce6ef83e759486fd243128db11a/packages/ariakit-utils/src/hooks.ts#L65-L79) to keep track of it.

**Comment by diegohaz** [comment]
Cool! Just a note: ariakit-utils doesn't really follow semver and may potentially break your app in the future. So it's probably better to implement that function yourself.

**Comment by diegohaz** [comment]
Hey @DaniGuardiola @marcospassos

Could you please review #1584 to see if it fixes your issues?

You can use the following version in the package.json:

```json
"ariakit": "https://pkg.csb.dev/ariakit/ariakit/commit/a76e069b/ariakit"
```
