### ISSUE TITLE
Ariakit Select crashes in Safari

### ISSUE THREAD

**Issue by dmolin** [ariakit/ariakit#1502]
### Current behavior

I'm having issues in using Ariakit (v2) in Safari, using React 18.1.0.

I've made a page in my webapp with just a single component; the code I used is the exact same code used in the Ariakit Select example; the page contains nothing else than that component.
As soon as I open that page I get an exception that reads:

```
TypeError: undefined is not an object (evaluating 'e._currentValue')
```
Following the stack trace (I'm running in production with a minified code, so it's somewhat hard to do that) I can see that the error happens in ./node_modules/ariakit/cjs/composite/composite-item.js at line 184
It looks like it's the call to `store.useState(state || CompositeContext, ...)` and it looks like the first argument provided is null (that then triggers an exception in react-dom)

This happens only in Safari.

More in general, I noticed that the Ariakit demo website doesn't work at all in Safari. each component I try to open throws  an exception.

### Steps to reproduce the bug

1. Just go to: https://ariakit.org/examples/select
2. You should get an error page

### Expected behavior

The component (Select in this case) should be displayed

**Comment by diegohaz** [comment]
What's the Safari version?

**Comment by diegohaz** [comment]
Hmm, it does seem to work on Safari 13.1.2 (which is what I can test with BrowserStack). I can see an error on Safari 12, but it's related to another thing (ResizeObserver).

<img width="917" alt="Screenshot of the site working on Safari 13" src="https://user-images.githubusercontent.com/3068563/173556477-622383ee-aae0-474c-88c3-94cb9cce26fb.png">

Are there any additional steps to reproduce it? Does it happen only on React 18.1?

That `CompositeContext` is created here:

https://github.com/ariakit/ariakit/blob/2c41c08afa396889a0d391615df6a23b3504a8f0/packages/ariakit/src/composite/__utils.ts#L214

It should never be undefined or null. `createStoreContext` calls `React.createContext` underneath.

My best guess would be some minification issue. Could you please try the site with different `rollup` versions (the library we use to bundle the code) here: https://github.com/ariakit/ariakit/pulls?q=is%3Apr+rollup (just open the PR and click on the `Visit preview` link in the vercel bot comment).

**Comment by dmolin** [comment]
The error on ResizeObserver is the one I see in Safari 13.1.3 when opening the ariakit.org web page.

As for the "e._currentValue" one: sadly this is not easy to reproduce; it happens only on our production build. It might well be related to a minification issue (at least it looks like it); Not sure how to proceed with the rollup thing though: we import ariakit as an node module dependency in our (big) codebase...

**Comment by diegohaz** [comment]
I see. I suggested looking into the rollup PRs because I thought it was happening on the Ariakit site as well. The ResizeObserver error should be gone by now (it was only on the website, not on the ariakit package).

I can't help much without being able to reproduce it. I'd start by looking into duplicated React versions.

**Comment by dmolin** [comment]
I'm closing this issue; It was a problem in the production minifier used in our application! Apologies for flagging this up in the first place.
