### ISSUE TITLE
`preventScrollOnKeyDown={false}` doesn't work as expected on Combobox

### ISSUE THREAD

**Issue by diegohaz** [ariakit/ariakit#1505]
### Current behavior

What `preventScrollOnKeyDown={false}` does is just not calling `event.preventDefault()` on key down, which would prevent scroll.

But not when the focused element is a text field. When pressing ArrowDown on text fields, the default browser behavior is not to scroll but to move the cursor to the end of the input (if it's a single-line input).

Also, when `virtualFocus` is set to `true` and the composite base element is not in the same scrollable area as the composite items (which is often also the case of combobox), the browser won't scroll the scrollable area by default (since the DOM focus is not there).

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/stoic-edison-nwz3r9?file=/src/combobox-matches.tsx
2. Click on the Combobox input and press ArrowDown until it reaches the last item.
3. It doesn't scroll down.

### Expected behavior

It should scroll down when pressing ArrowDown on the last item.

### Possible solutions

- Maybe we should rename the prop to `preventDefaultOnKeyDown` to better align expectations.

- Always move DOM focus to the composite item when proxying keydown: https://github.com/ariakit/ariakit/blob/b035bd6c8ba4611391f1017cede5796c3f699ddd/packages/ariakit/src/composite/composite.ts#L67-L72

- Manually scroll on key down (suggestion by @marcospassos): https://codesandbox.io/s/ariakit-combobox-infinity-scroll-forked-wys8x0?file=/src/App.js

**Comment by diegohaz** [comment]
@marcospassos The problem is not `SelectItem` (well, it's not even `ComboboxItem`), but the fact that it doesn't work when the focused element is a text field, which is the case of combobox.

You can see that it works with SelectItem here: https://ariakit.org/examples/select-group

**Comment by diegohaz** [comment]
The workaround is setting `virtualFocus` to `false`:

```jsx
useComboboxState({ virtualFocus: false })
```

But it doesn't work with `<Combobox autoSelect />`

**Comment by marcospassos** [comment]
> @marcospassos The problem is not `SelectItem` (well, it's not even `ComboboxItem`), but the fact that it doesn't work when the focused element is a text field, which is the case of combobox.
> 
> You can see that it works with SelectItem here: https://ariakit.org/examples/select-group

It didn't work even using a select box in the issue that originated this. Maybe unrelated, I found it relevant to point out.

**Comment by diegohaz** [comment]
I have updated the issue to include the case where DOM focus is not in the scrollable area (which is also often the case of Combobox) and to include more possible solutions.

**Comment by diegohaz** [comment]
I believe the optimal solution for this scenario is to use the [`scroll-margin`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin) CSS property. By applying this to the first or last item, and assigning a sufficiently large value to encompass the content at the top or bottom, we can eliminate the need for any additional workaround.

This approach generally provides a superior user experience, as keyboard users won't have to determine whether there's more content to scroll to using the arrow keys.

**Comment by diegohaz** [comment]
The [`preventScrollOnKeyDown`](https://ariakit.org/reference/composite-item#preventscrollonkeydown) is now deprecated in favor of using [`scroll-margin`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-margin).
