### ISSUE TITLE
Adding an exports map in package.json?

### ISSUE THREAD

**Issue by lewisl9029** [ariakit/ariakit#1508]
### Motivation

Skypack has a good writeup on reasons why we might want to have an exports map: https://docs.skypack.dev/package-authors/package-checks#export-map

TL;DR:
- Allows package authors to specify multiple explicit entry points into the package as the public API
- Blocks access to all internal files not specified in the exports map, to prevent usage of unsupported internal modules/APIs
- Enables simpler and more efficient static analysis and bundling by things like build tools and CDNs, without which they'd have to rely on heuristics to decide what to expose as separate modules vs bundle into other modules.

The last point is what brought me here. In https://github.com/jspm/project/issues/194, we can see that jspm's heuristics based bundling ended up resulting in the select package (and possibly others) being bundled into the main entry point, instead of exposed as a separate sub-package, preventing users from importing just the select package.

Thoughts? I'd be happy to open a PR to add this if you're onboard with the idea! It should be just a matter of adding an entry for each of the components in the cjs/esm/umd/ts folders in the npm build artifacts. I don't foresee this adding much ongoing maintenance burden, but happy to discuss further if you have concerns. Thanks!

### Usage example

Once implemented, users will still be able to do this:

```js
import * as select from 'ariakit/select'
```

But not this:

```js
import * as utils from 'ariakit/__utils-ce9ba82e.js'
```

Also, when using jspm, users will be able to do this:

```js
import * as select from 'https://ga.jspm.io/npm:ariakit@2.0.0-next.30/esm/select/index.js'
```

Whereas now they need to import from the entire package:

```js
import * as ariakit from 'https://ga.jspm.io/npm:ariakit@2.0.0-next.30/esm/index.js'
```

### Workaround

At the moment, I'm working around this by importing the entire package:

```js
import * as ariakit from 'https://ga.jspm.io/npm:ariakit@2.0.0-next.30/esm/index.js'
```

### Possible implementations

The implementation will probably involving adding a new exports key in package.json like this:

```js
  // ... other stuff in package.json
  "exports": {
    ".": {
      "require": "./cjs/index.js",
      "import": "./esm/index.js",
      "types": "./ts/index.d.ts"
    },
    "./select": {
      "require": "./cjs/select/index.js",
      "import": "./esm/select/index.js",
      "types": "./ts/select/index.d.ts"
    }
    // ... rest of the components
  }
```

**Comment by diegohaz** [comment]
This should be fixed with `@ariakit/react`.
