### ISSUE TITLE
Selectbox item is not initially selected in strict mode

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1531]
### Current behavior

No item is initially selected when using portals with lazily-mounted popover in strict mode.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/silly-turing-ye2mnl
2. Click on the select box
3. Notice no item is selected

### Expected behavior

Select the first item

**Comment by diegohaz** [comment]
I can reproduce now. Thanks!

**Comment by diegohaz** [comment]
> @diegohaz This issue is still present in the `next.31` (latest). Not sure if the fix really solved the issue.
> 
> You can see it happening [here](https://codesandbox.io/s/silly-turing-ye2mnl).

I can't see the issue locally on `next.31` nor in the CodeSandbox you linked.

**Comment by marcospassos** [comment]
Can you please [try again](https://codesandbox.io/s/silly-turing-ye2mnl)?

Video on how to reproduce:
https://user-images.githubusercontent.com/943036/176327874-ff740806-1784-4988-9892-28c624c984a6.mov

**Comment by diegohaz** [comment]
Ah, I think that's a CodeSandbox bug (probably some dependency cache issue related to using the `latest` keyword in the dependency version). It works if you change the version to `2.0.0-next.31` in package.json.
