### ISSUE TITLE
SetVisible is called twice when popover is lazily mounted

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1544]
### Current behavior

The `setVisible` is called twice when closing select/combobox popovers lazily mounted. This can cause a collateral effect if you're dispatching callbacks like in Ariakit's `onClose` example.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/divine-moon-u2bwb0
2. Open the select
3. See the `setVisible` is called once with `true`
4. Close the select
5. See the `setVisible` is called twice with `false`

### Expected behavior

`setVisible` be called once.

### Workaround

https://github.com/ariakit/ariakit/issues/1544#issuecomment-1166059836

**Comment by diegohaz** [comment]
That's expected. That's part of why it's called `setVisible`, and not `onVisibilityChange` or something else. The setter may be called multiple times with the same value just like any other state updater function in React.

If you want to run something only on change you should manually check it:

```jsx
const select = useSelectState({
  setVisible: (visible) => {
    if (select.visible !== visible && !visible && onClose) {
      onClose();
    }
  },
});
```

**Comment by marcospassos** [comment]
Thanks for clarifying it!
