### ISSUE TITLE
Select - Opening with Space key scrolls the page down

### ISSUE THREAD

**Issue by binhxn** [ariakit/ariakit#1545]
### Current behavior

Hello!

I'm playing around with Select and noticed that if the height of the Select container is large, then pressing the Space key to open the SelectPopover will force the browser to scroll down. For example, in the [Select examples page](https://ariakit.org/examples/select), I added a large height to the canvas (`80vh`). When I open Select with the Enter key, it works as expected. However, when I press the Space key, the browser scrolls down. (My Space key message bubble isn't recorded in the video). Here's a screen recording:

https://user-images.githubusercontent.com/8155387/175751222-062596a8-1d65-448f-ac53-98ae66c16e07.mp4

I'm curious to hear your thoughts on this!

### Steps to reproduce the bug

1. Open Select example page: https://ariakit.org/examples/select
2. Add height of `80vh` to the canvas
3. Open Select with Space key
4. Notice the scroll behavior 

This is occurring on Chrome, Firefox, and Safari

### Expected behavior

Pressing the Space and Enter key should behave the same and not scroll the browser to the bottom of the page.

### Workaround

https://github.com/ariakit/ariakit/issues/1545#issuecomment-1166169418

**Comment by diegohaz** [comment]
Good catch! Thanks! We should probably call `event.preventDefault()` there.

In the meantime, here's a workaround:

```jsx
<Select
  onKeyDown={(event) => {
    if (event.key === " ") {
      event.preventDefault();
      select.toggle();
    }
  }}
/>
```

**Comment by binhxn** [comment]
Of course! And thank you for the quick response!
