### ISSUE TITLE
Allow specifying an initial fallback ref for select popovers

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1553]
### Motivation

As discussed [here](https://github.com/ariakit/ariakit/discussions/1547#discussioncomment-3034343), adding any focusable element to the select popover makes it gains focus when opening the PR.

I propose adding a way to specify a fallback ref used when no selected item is focusable.

### Usage example

```tsx
<SelectPopover state={state} initialFocusRef={select.baseRef}>
...
</SelectPopover>
```

Alternatively:

```tsx
<SelectPopover state={state} fallbackFocusRef={select.baseRef} initialFocusRef={/* current behavior */}>
</SelectPopover>
```

### Requirements

- Allow specifying a fallback ref used when no selected item is focusable.

### Workaround

https://github.com/ariakit/ariakit/discussions/1547#discussioncomment-3027157

### Possible implementations

```diff
export const useSelectPopover = createHook<SelectPopoverOptions>(
-  ({ state, ...props }) => {
+  ({ state, initialFocusRef, ...props }) => {
    const values = toArray(state.value);
    const value = values[values.length - 1] ?? "";
    const [item, setItem] = useState<Item | null>(null);

    // Sets the initial focus ref.
    useEffect(() => {
      setItem((prevItem) => {
        if (state.mounted && prevItem?.ref.current) return prevItem;
        const item = findEnabledItemByValue(state.items, value);
        return item || null;
      });
    }, [state.mounted, state.items, value]);

    props = useSelectList({ state, ...props });
-    props = usePopover({ state, initialFocusRef: item?.ref, ...props });
+    props = usePopover({ state, initialFocusRef: item?.ref ?? initialFocusRef, ...props });

    return props;
  }
);
```

**Comment by diegohaz** [comment]
> adding any focusable element to the select popover makes it gains focus when opening the PR.

It looks like that happens only if the select value is empty (`[]` or `""`). I wonder if SelectPopover should default to `state.baseRef` by default in this case.

**Comment by marcospassos** [comment]
It also happens if the last selected element is disabled. Anyway, defaulting does the job.

Passing `initialFocusRef` will still be possible, right? I mean:

```ts
props = usePopover({ state, initialFocusRef: item?.ref ?? select.baseRef, ...props });
```

**Comment by marcospassos** [comment]
I've just tried this solution locally, and it works perfectly. I've just submitted a [PR](https://github.com/ariakit/ariakit/pull/1557) for further evaluation.
