### ISSUE TITLE
Latest next.32 introduces new typing errors

### ISSUE THREAD

**Issue by httpete** [ariakit/ariakit#1587]
### Current behavior

31 ran fine with no errors, 32 does:
```

ActionBar/Dxi.tsx:78:27 - error TS2339: Property 'visible' does not exist on type 'MenuState<Values>'.

78           placement={menu.visible ? 'left' : 'bottom'}>

**Comment by diegohaz** [comment]
`visible` has been renamed to `open`: https://github.com/ariakit/ariakit/blob/main/packages/ariakit/CHANGELOG.md#major-changes

**Comment by httpete** [comment]
Thank you @diegohaz it works perfectly.
