### ISSUE TITLE
tests starting failing in 32 

### ISSUE THREAD

**Issue by httpete** [ariakit/ariakit#1607]
### Current behavior

    Cannot find module 'ariakit-utils/dom' from '../../../node_modules/ariakit/cjs/button/button.js'

Any thoughts? Thank you.

### Steps to reproduce the bug

run jest ut with an ariakit

### Expected behavior

pass as it did in 31.

**Comment by diegohaz** [comment]
> ### Steps to reproduce the bug
> run jest ut with an ariakit

Not sure what that means. Could you please provide a CodeSandbox or something?

**Comment by httpete** [comment]
Sorry, it was some screwup in my npm.
