### ISSUE TITLE
Issue with Tooltip's content placement in iframe on first render

### ISSUE THREAD

**Issue by navin-moorthy** [ariakit/ariakit#1641]
### Current behavior

https://user-images.githubusercontent.com/39694575/179757108-76854ee3-ce50-4aa0-b532-5b1797edc17b.mp4

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/ariakit-issue-tooltip-bd62qg
2. Hover the button which is rendered within the iframe
3. On first hover, the position of the content is little off from the expected placement
4. Hover the button again to get the expected placement

### Expected behavior

1. Hover the button which is rendered within the iframe
2. Hover the button again to get the expected placement

**Comment by diegohaz** [comment]
Thanks, @navin-moorthy!

Could you try to reproduce it where the iframe contents are in another CodeSandbox (so we can edit it)? I changed the iframe src to `https://ariakit.org/examples/tooltip` and couldn't see any issue.

**Comment by navin-moorthy** [comment]
You can see the issue here aswell in Storybook iframe- https://adaptui-react-tailwind.vercel.app/?path=/story/popups-tooltip-anchor--left
But not when we open the canvas without the iframe - https://adaptui-react-tailwind.vercel.app/iframe.html?args=&id=popups-tooltip-anchor--left&viewMode=story



> I changed the iframe src to https://ariakit.org/examples/tooltip and couldn't see any issue.
You rendered the whole example inside the iframe that did not reproduce the issue
Try rendering just the preview url inside the iframe

**Comment by diegohaz** [comment]
@navin-moorthy It looks like the issue doesn't happen anymore. Did you change something to fix it, or have we somehow fixed it in the library?

**Comment by navin-moorthy** [comment]
Seems somehow it is fixed in the library. may be #1676 PR fixed it.
