### ISSUE TITLE
Voiceover truncates combobox's initial announcement

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1648]
### Current behavior

When opening a combobox, the initial announcement get's truncated

https://user-images.githubusercontent.com/943036/180036878-68199c50-bac6-4dd0-aecd-40dcf5eb4ac3.mov

### Steps to reproduce the bug

1. Open the sample: https://ariakit.org/examples/select-combobox
2. Turn the Voiceover on
3. Open the combobox
4. Notice the first announcement starts with "and 1..."

### Expected behavior

Announces the full sentence:
![image](https://user-images.githubusercontent.com/943036/180037146-8227881d-25d9-48de-adec-2e9acc31147b.png)

[See the reference.](https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html)

### Workaround

https://github.com/ariakit/ariakit/issues/1648#issuecomment-1190597027

**Comment by diegohaz** [comment]
Thanks, @marcospassos! Could you please specify in the issue which browsers you tested? [VoiceOver is generally used with Safari](https://webaim.org/projects/screenreadersurvey9/#browsercombos), so we'll prioritize it.

And just to be sure, this is specific to the `select-combobox` combination, and not the `combobox` alone, right?

**Comment by marcospassos** [comment]
I'm testing on Chrome. This issue specifically doesn't happen on Safari.

> And just to be sure, this is specific to the `select-combobox` combination, and not the `combobox` alone, right?

You're right. The standalone select and combobox components work just fine.

**Comment by changangus** [comment]
Hi, was hoping to help out, could I take this issue?

**Comment by diegohaz** [comment]
@changangus Sure, but I don't know if there's a straightforward solution to this issue. It looks more like a browser bug. Since this is specific to VoiceOver+Chrome, which is not a very popular combination, I'd not spend too much time on this. I'd suggest looking into #1647, which is easier to address and get started.

**Comment by changangus** [comment]
@diegohaz great thanks! Yeah I'll start taking a look at #1647 and comment over there anything that I find.
