### ISSUE TITLE
Inconsistent behavior clearing combobox

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1652]
### Current behavior

I just noticed the following behavior with the cancel button using `autoSelect`:

https://user-images.githubusercontent.com/943036/180314309-c62bf844-cc4f-49e5-a79f-2a47bb09a545.mov

Is it the intended behavior? If so, is there any workaround to always unselect the item after clearing the input?

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/polished-worker-5ugu3i
2. Type "a"
3. Press tab
4. Hit enter
5. Notice no item is now selected
6. Type "a" again
7. Now, click on the clear button
8. Notice the first item remains selected

### Expected behavior

Keep no item selected after clearing the input.

### Workaround

https://github.com/ariakit/ariakit/issues/1652#issuecomment-1191996711

### Possible solutions

Maybe set `hasInsertedTextRef.current = false` on the combobox `onBlur` event.

https://github.com/ariakit/ariakit/blob/66f9e3e4d9e3deb7f6bd5274f4a52e4d6c5aaefc/packages/ariakit/src/combobox/combobox.ts#L93

**Comment by diegohaz** [comment]
> ### Steps to reproduce the bug
> 1. Open sandbox: https://codesandbox.io/s/polished-worker-5ugu3i
> 2. Type "a"
> 3. Press tab
> 4. Hit enter
> 5. Notice no item is now selected
> 6. Type "a" again
> 7. Now, click on the clear button
> 8. Notice the first item remains selected

I can't reproduce these steps with that CodeSandbox. I think you forgot to add the `autoSelect` prop (make sure you save the file).

**Comment by marcospassos** [comment]
Could you please try again?

**Comment by diegohaz** [comment]
Thanks! This looks like a bug. I also noticed that the popover doesn't remain open when focusing on the cancel button if the combobox input doesn't have an `id` prop. That's probably a regression. We might've removed the `id` prop from the combobox component at some point.

**Comment by diegohaz** [comment]
Workaround:

```jsx
const [autoSelect, setAutoSelect] = useState(true);

<Combobox
  autoSelect={autoSelect}
  onChange={() => setAutoSelect(true)}
  onBlur={() => setAutoSelect(false)}
/>
```

**Comment by marcospassos** [comment]
> That's probably a regression. We might've removed the `id` prop from the combobox component at some point.
Why do you think so? For me, [it's expected](https://github.com/ariakit/ariakit/blob/454aef1237ada31e8292ee4966adca3ed0f6e299/packages/ariakit/src/combobox/combobox-cancel.tsx#L64).

**Comment by diegohaz** [comment]
It should work like that out of the box. And it used to be:

https://github.com/ariakit/ariakit/blob/f1af487ef872388dc3234be4b5e741960d9e8467/packages/ariakit/src/combobox/combobox.ts#L347-L349

That default `id` prop was removed from the combobox by mistake at some point before we had tests for the combobox cancel component.

If hiding the popover when focusing on the cancel button is desirable behavior, there should be a more explicit way to do so. Omitting the id is definitely not a good API, and that's not intentional. Are you relying on that?

**Comment by marcospassos** [comment]
No, in fact, keeping it open is the desired behavior. That's why I'm specifying one.

**Comment by marcospassos** [comment]
@diegohaz, the inconsistency reported in this issue is still present in the next 37. This PR's point is that using the keyboard or mouse leads to different results.

**Comment by diegohaz** [comment]
> ### Steps to reproduce the bug
> 1. Open sandbox: https://codesandbox.io/s/polished-worker-5ugu3i
> 2. Type "a"
> 3. Press tab
> 4. Hit enter
> 5. Notice no item is now selected
> 6. Type "a" again
> 7. Now, click on the clear button
> 8. Notice the first item remains selected

I can't reproduce 8 anymore in next.37.

**Comment by marcospassos** [comment]
The workaround for the bug was the cause of it not working 😵‍💫:

<img width="657" alt="image" src="https://user-images.githubusercontent.com/943036/182250903-2c74418f-b559-4d30-a704-e4fe9ad0d069.png">

I can confirm it fixed the issue indeed. Thank you!
