### ISSUE TITLE
Popup misalignment when inside of a container with position relative

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1657]
### Current behavior

The popup's initial render is always misaligned when nested in a container with `position: relative`:

https://user-images.githubusercontent.com/943036/180498198-72348d99-be5d-4fb7-b7e8-ec73002bced6.mov

Consequently, this affects all components backed by the popover (menus, hover cards, etc).

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/blissful-panna-ss5b9s?file=/src/popover.tsx
2. Click on the button
3. Notice the popup is misaligned
4. Click on the button to hide the popover
5. Click on the button again
6. Notice the popup is now correctly aligned

### Expected behavior

Correct alignment on the first render.

### Workaround

Any of the following:

- `<Popover wrapperProps={{ style: { top: 0, left: 0 } }} />`
- Add an explicit `width` value to the popover styles.
- `usePopoverState({ fixed: true })`
- Remove the intermediate `<div>` wrapper between the container and the anchor/popover elements.

### Possible solutions

https://github.com/ariakit/ariakit/issues/1657#issuecomment-1192908178

**Comment by diegohaz** [comment]
Thanks! It looks like it happens since next.31 and may be related to #1535

**Comment by diegohaz** [comment]
It looks like we'll have to add `top: 0, left: 0` here: https://github.com/ariakit/ariakit/blob/790af4e1acd75864f46f589819f066fc70e5f992/packages/ariakit/src/popover/popover.tsx#L78-L81

Reference: https://github.com/floating-ui/floating-ui/issues/1809#issuecomment-1192904516
