### ISSUE TITLE
Focus on combobox not bubbling up

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1659]
### Current behavior

For some reason, the focus on the combobox input is not bubbling up, preventing components higher in the hierarchy from reacting accordingly:

https://user-images.githubusercontent.com/943036/180580200-bba88f68-0df3-4578-ba9f-99776a158575.mov

This also affects hovering with `focusOnHover`.

We caught this issue while building a component that has a different style based on whether it has a focused element within. A naive solution is using the `:focus-within` selector, but in React it would not always work since elements rendered in portals aren't descent of the parent element, so the style isn't applied. There is no option left but to listen for focus events, as React correctly propagates to the respective parents in the rendering tree. However, due to the current behavior of the combobox input, the component isn't notified about the focus change. So, when moving from an item to the input, a blur event is notified removing the style, but no focus bubbles up after that.

The same doesn't happen to other components like menus.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/gallant-lucy-wtq0jc?file=/src/combobox.tsx
2. Click on the comobobox
3. The counter increment by 1
4. Press arrow down
5. The counter increment by 1
6. Press arrow up
7. The counter does not increment

### Expected behavior

All events being notified.

### Workaround

https://github.com/ariakit/ariakit/issues/1659#issuecomment-1193034269

### Possible solutions

We could check if the composite element (`element` below) already has DOM focus. If so, we should fire a custom focus event.

https://github.com/ariakit/ariakit/blob/acfed767a447c06b8236456ad70d2b9372399193/packages/ariakit/src/composite/composite.ts#L162-L164

**Comment by diegohaz** [comment]
> We caught this issue while building a component that has a different style based on whether it has a focused element within.

Are you comfortable sharing the design of what you're building? If we implement this, we'll likely need to build an example with tests so we can guarantee this keeps functioning. It's better if that's based on a real-world example.

**Comment by diegohaz** [comment]
As a workaround, you can either listen to `combobox.activeId === null` if you have access to the combobox state in your parent component.

Or ignore blur events where `event.relatedTarget` is the combobox input element:

```jsx
const ref = useRef(null);

<Combobox ref={ref} />
<ComboboxPopover
  onBlur={(event) => {
    if (event.relatedTarget === ref.current) {
      event.stopPropagation();
    }
  }}
/>
```

Or disable `virtualFocus`:

```jsx
useComboboxState({ virtualFocus: false })
```

**Comment by marcospassos** [comment]
> > We caught this issue while building a component that has a different style based on whether it has a focused element within.
> 
> Are you comfortable sharing the design of what you're building? If we implement this, we'll likely need to build an example with tests so we can guarantee this keeps functioning. It's better if that's based on a real-world example.

Sure! 

Here's the real component:

https://user-images.githubusercontent.com/943036/180609324-2638e9fa-15cc-440c-893f-0e9034224603.mov

And here's [ a simplified implementation ](https://codesandbox.io/s/nervous-euclid-47i33i?file=/src/select-combobox.tsx)so we can iterate over:

https://user-images.githubusercontent.com/943036/180610264-07678cbd-dfe4-4b64-84a1-3d97f8531c57.mov

> Or ignore blur events where `event.relatedTarget` is the combobox input element:

Unfurnatelly, this introduces other issues. Because the last onblur event isn't fired, the style isn't removed.

> Or disable `virtualFocus`:
> 
> ```js
> useComboboxState({ virtualFocus: false })
> ```

This fixed the issue, but it is not an option for select combobox since searching for something becomes a pain – you have to navigate up to the input before searching for something.

**Comment by diegohaz** [comment]
Thanks for the videos and the CodeSandbox!

> This fixes the issue indeed. However, it is not an option to select comboboxes since searching for something becomes a pain – you have to navigate up to the input before searching for something.

When using with Select, you would have to disable typeahead on the `SelectPopover` component:

```jsx
<SelectPopover typeahead={false}>
```

But I see you're using `autoSelect`, which doesn't work without virtual focus. So that may still not be an option.

---

Based on your sandbox, it looks like this could work:

```jsx
<SelectPopover
  onBlur={(event) => {
    if (event.currentTarget.contains(event.relatedTarget)) {
      event.stopPropagation();
    }
  }}
  autoFocusOnHide={(element) => {
    queueMicrotask(() => {
      element.focus();
    });
    return false;
  }}
>
```

[Updated CodeSandbox with comments](https://codesandbox.io/s/ariakit-select-combobox-suppressing-internal-blur-events-gigr7t?file=/src/select-combobox.tsx:1100-1789).

I'll mark this as a feature request because that's the expected behavior since the combobox input already has DOM focus when you move to it with arrow keys. We would've to dispatch a custom focus event somehow programmatically.

**Comment by marcospassos** [comment]
> Based on your sandbox, it looks like this could work:
> 
> ```js
> <SelectPopover
>   onBlur={(event) => {
>     if (event.currentTarget.contains(event.relatedTarget)) {
>       event.stopPropagation();
>     }
>   }}
>   autoFocusOnHide={(element) => {
>     queueMicrotask(() => {
>       element.focus();
>     });
>     return false;
>   }}
> >
> ```
> 
> [Updated CodeSandbox with comments](https://codesandbox.io/s/ariakit-select-combobox-suppressing-internal-blur-events-gigr7t?file=/src/select-combobox.tsx:1100-1789).

That worked just fine, thanks @diegohaz!

**Comment by marcospassos** [comment]
@diegohaz, I just found a caveat with this approach: pressing tab suppresses the blur event.

Uploading Screen Recording 2022-07-25 at 12.39.49.mov…

[Codesandbox](https://codesandbox.io/s/ariakit-select-combobox-suppressing-internal-blur-events-forked-eg2lrg?file=/src/example.tsx)

**Comment by marcospassos** [comment]
The workaround is checking whether the focus is still inside the container:

```ts
if (!event.currentTarget.contains(document.activeElement)) {
    setFocused(false);
}
```

I've updated the Codesandbox with the fix.

**Comment by diegohaz** [comment]
Yeah, that happens because the blur event we dispatch on the item when you move the focus out of the select popover ends up being fired *after* the focus event on the element outside. That's why that `autoFocusOnHide` prop was needed in my first suggestion.

This is the relevant code: https://github.com/ariakit/ariakit/blob/b1f3d9b3bcab322494e4460c7e377e222f5cbf2b/packages/ariakit/src/composite/composite.ts#L301-L308

I'm not sure why this happens since we're synchronously firing it in the composite's blur event (which supposedly fires before the next focus event).

Anyway, with your solution, you can remove the `autoFocusOnHide` prop. But I would use `event.relatedTarget` instead of `document.activeElement`:

```jsx
<div
  onBlur={(event) => {
    if (!event.currentTarget.contains(event.relatedTarget)) {
      setFocused(false);
    }
  }}
>
  <SelectPopover
    portal
    onBlur={(event) => {
      if (event.currentTarget.contains(event.relatedTarget)) {
        event.stopPropagation();
      }
    }}
  />
</div>
```

Also noting that `onBlur` on `SelectPopover` is needed just because we're using `portal`. Otherwise, only the check on the parent's blur event would be needed.

**Comment by diegohaz** [comment]
> I'm not sure why this happens since we're synchronously firing it in the composite's blur event (which supposedly fires before the next focus event).

In fact, I did some tests locally, and the blur event is always fired before the focus event. I don't understand why that's happening differently on that CodeSandbox.

**Comment by marcospassos** [comment]
There's something wrong with the popover and the blur event. I just noticed that if you focus on a hovercard (portal) and press tab (to focus on the next element out of the popover), it will fire blur and then focus, each more than once. That completely broke our panel behavior.

**Comment by diegohaz** [comment]
> There's something wrong with the popover and the blur event. I just noticed that if you focus on a hovercard (portal) and press tab (to focus on the next element out of the popover), it will fire blur and then focus, each more than once. This completely breaks our panel behavior.

Looks like a different issue. Does that happen if you use `<Hovercard portal preserveTabOrder={false}>`?

**Comment by marcospassos** [comment]
Yep, it still happens. That was my first try.

**Comment by marcospassos** [comment]
> There's something wrong with the popover and the blur event. I just noticed that if you focus on a hovercard (portal) and press tab (to focus on the next element out of the popover), it will fire blur and then focus, each more than once. This completely breaks our panel behavior.
Notice that it fires the `focus` event after the `blur` event, even though we're the container is losing focus.

**Comment by diegohaz** [comment]
Could you please open a separate issue for that?
