### ISSUE TITLE
Hovercard popover is always displayed after scrolling

### ISSUE THREAD

**Issue by mustaphaboudouch** [ariakit/ariakit#1662]
### Current behavior

https://user-images.githubusercontent.com/64332287/180682264-f2be8c9f-8cb7-4af9-a410-da4771dc29e7.mov

### Steps to reproduce the bug

1. Open this example: https://ariakit.org/examples/hovercard
2. Hover over the anchor
3. Scroll (up or down) until the mouse is outside the popover
4. Stop scrolling, the popover is always displayed

### Expected behavior

I think when scrolling, once the mouse leaves the popover it should disappear, here is an example from twitter :

https://user-images.githubusercontent.com/64332287/180684782-76240a9e-e792-4833-9a45-a18b61d09bff.mov

### Workaround

https://github.com/ariakit/ariakit/issues/1662#issuecomment-1193667203

### Possible solutions

We probably need to set `hideTimeoutRef.current = 0` inside this setTimeout callback:

https://github.com/ariakit/ariakit/blob/9ce976acd92f0bb61fe2cfb33d538454aca05d0b/packages/ariakit/src/hovercard/hovercard.tsx#L232-L236

**Comment by diegohaz** [comment]
Hi @mustaphaboudouch! Thank you for the videos!

The Ariakit Hovercard doesn't work the same as on Twitter. By default, our Hovercard will appear only when the user *intentionally* moves the mouse over the anchor element. That is, if the user scrolls the page without moving the mouse and the mouse happens to be on the anchor element as a result, the Hovercard will not be displayed.

You can see this happening here:

![Screencast demonstrating what's explained above](https://user-images.githubusercontent.com/3068563/180713848-4a6dc15f-25b8-44a9-9cd5-7804c8e5ea8d.gif)

For consistency, the same goes for hiding the hovercard. The user must move the mouse after scrolling past the hovercard as you did in your video. This was intentionally designed this way so the hovercard is not closed by mistake (e.g., the user may scroll the page to see the rest of the hovercard contents if it's not fully visible but accidentally scroll past it).

That being said, the hovercard is currently not hiding when you move the mouse after scrolling past the hovercard, which is a bug.

**Comment by diegohaz** [comment]
Here's a workaround:

```jsx
const hovercard = useHovercardState();

<Hovercard
  hideOnHoverOutside={() => {
    // Overwrite the default behavior
    setTimeout(hovercard.hide, 500);
    return false;
  }}
>
```

**Comment by 0xDing** [comment]
> ```js
> hideOnHoverOutside
> ```

but this not work with `useMenu` and `Menu` component's hideOnHoverOutside attribute
