### ISSUE TITLE
Blur event fired out of order

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1669]
### Current behavior

Recently I noticed an issue apparently related to the popover component. In some circumstances, the focus event is fired in an unpredictable way, leading to bugs in components that rely on it to track focus inside it.

https://user-images.githubusercontent.com/943036/180890247-191640d4-30f5-4999-a248-102aee1aa298.mov

Related: #1659 

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/hovercard-blur-bug-m31nt6
2. Press tab to focus on the "Focus" button
3. Notice the status is not "Focused"
4. Press tab again to move the focus to the "External focusable area"
5. See the status is not "Not focused"
6. Press shift tab to return the focus to the "Focus" button
7. Notice the status is "Focused" again
8. Press enter to open the hovercard
9. Press tab to focus on the "Focus me" button inside the popup
10. Now, press tab to focus on the "External focusable area"
11. Notice the status is still "Focused"

### Expected behavior

The blur and focus events firing in the correct order.

### Workaround

https://github.com/ariakit/ariakit/issues/1669#issuecomment-1194808357

### Possible solutions

We probably need to call focus here using `queueMicrotask` (in all focus trap elements):
https://github.com/ariakit/ariakit/blob/6646b70f3a6cd8809645a792d7f2618455b2333b/packages/ariakit/src/portal/portal.tsx#L173-L182

**Comment by diegohaz** [comment]
Thanks! As I'd imagined, that's related to the `preserveTabOrder` feature. This video shows how this works: [Focus management with React Portal](https://www.youtube.com/watch?v=ELauJdPoDaQ).

You can work around that by stopping the propagation of the events on these elements. Instead of targeting them, though, as they're not part of the public API, you can just stop the propagation of all events on elements that are not (or within) the anchor and the hovercard elements:

```jsx
const anchorRef = useRef<HTMLButtonElement>(null);
const hovercardRef = useRef<HTMLDivElement>(null);

const stopFocusTrapEvents = (event) => {
  if (
    !anchorRef.current.contains(event.target) &&
    !hovercardRef.current.contains(event.target)
  ) {
    event.stopPropagation();
  }
};

<div onFocus={stopFocusTrapEvents} onBlur={stopFocusTrapEvents}>
  <HovercardAnchor ref={anchorRef}>Focus</HovercardAnchor>
  <Hovercard portal ref={hovercardRef}>
    <Button>Focus me</Button>
  </Hovercard>
</div>
```
