### ISSUE TITLE
Popup doesn't finish mounting if it loses focus before being completely mounted

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1684]
### Current behavior

If the popup disclosure loses focus just after gaining, the popover never finishes mounting:

https://user-images.githubusercontent.com/943036/181810243-7e229c60-8721-4f7d-b1d6-792add7b8424.mov

I caught this bug originally on the select box, but it affects all components that use popover.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/elastic-sinoussi-93n469?file=/src/popover.tsx
2. Press tab to focus on the "Focusable" element
3. Click on "Accept invite"
4. Notice the popover is still hidden
5. Inspect the page and notice that it's in fact with `opacity: 0`

### Expected behavior

Unmounting.

### Workaround

https://github.com/ariakit/ariakit/issues/1684#issuecomment-1200344513

**Comment by diegohaz** [comment]
I see different behavior on the CodeSandbox you shared: the popover appears but never closes. That's expected since there's no CSS transition. Did you forget to save the file?

Also, do you have a concrete use case you can share?

**Comment by marcospassos** [comment]
> Did you forget to save the file?

Yes. The issue is intermittent on the Codesandbox but reproducible 100% of the time in our use case.

> Also, do you have a concrete use case you can share?

We're using [DND kit](https://dndkit.com/) to build sortable list. To make sorting accessible, DND allows dragging elements by pressing the space bar or enter and then using the arrow to reorder them. When canceling a drag, DND kit moves the focus to the card. So that's what is happening: if I select the card and click on the combobox, the focus moves to the comobox and back to the card. For some reason, the popup stays mounted and blocks any click on that area.

I recorded a video that better illustrates the issue:

https://user-images.githubusercontent.com/943036/181845435-97398bab-db06-4801-b626-9c42245d116c.mov

**Comment by diegohaz** [comment]
Thank you for the video! Could you please update the CodeSandbox?

This looks like a bug on our side. But I guess dnd kit shouldn't move focus if the user intentionally focused something else.

**Comment by marcospassos** [comment]
> But I guess dnd kit shouldn't move focus if the user intentionally focused something else.

Second that. The default behavior is even worst: focusing out keeps the element active until you explicitly press space. To make it worse, it registers listeners to the window. You see a custom behavior I've implemented to cancel the dragging when moving the focus away from the element. I'm afraid there's no way to replace that behavior in the userland.

> Thank you for the video! Could you please update the CodeSandbox?

The first video I recorded using exactly the same code. The problem is that I can't reproduce it consistently on Codesandbox. Is there anything else I can do the help you out?

**Comment by diegohaz** [comment]
> The first video I recorded was using exactly the same code. The problem is that I can't reproduce it consistently on Codesandbox. Is there anything else I can do the help you out?

The CodeSandbox you linked doesn't seem to have the same code as in your video. You can open it in an anonymous tab to check.

**Comment by marcospassos** [comment]
There's nothing left to save:

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/943036/181850287-802a4be4-3777-4757-b429-9e7f594306ce.png">

I just compared it with the video. Can you spot what the differences you noticed are?

**Comment by diegohaz** [comment]
Could you paste the contents of the `style.css` file?

**Comment by marcospassos** [comment]
Oh, that's what is missing. Super sorry. I was just comparing the ts files. I've just updated the examples. Try a few times, and you'll probably be able to reproduce it. Let me know if you manage to.

**Comment by diegohaz** [comment]
Thanks! I can reproduce it. I'll take a look into that.

I think it's worth raising an issue on dnd kit about forcing focus when the user has intentionally focused on something else. We do something similar on the dialog component when it closes: https://github.com/ariakit/ariakit/blob/69359165b310a62f35060539a431f3c585937794/packages/ariakit/src/dialog/dialog.tsx#L338

**Comment by diegohaz** [comment]
In the CodeSandbox you shared, you have to call `popover.stopAnimation()` when moving focus to the "Focusabled" element. I don't know how dndkit works. But you would have to do something similar there.

[CodeSandbox](https://codesandbox.io/s/goofy-matsumoto-bulsjf?file=/src/popover.tsx:372-571)

**Comment by marcospassos** [comment]
We don't expose the popover state in our case – it's completely encapsulated. Do you plan to solve it somehow on the popover component?

**Comment by diegohaz** [comment]
I'm working on improvements to the animation logic that will potentially solve the issue you reproduced on CodeSandbox. But I can't guarantee that it will work with dndkit. The best solution is not to steal focus. So I'd suggest opening an issue there.

**Comment by marcospassos** [comment]
I'll do that. I'm asking just to know if I should work on a workaround for now.
