### ISSUE TITLE
Combobox not firing focus event

### ISSUE THREAD

**Issue by marcospassos** [ariakit/ariakit#1688]
### Current behavior

The combobox when used with the selectbox doesn't fire the focus event.

**Use case**

We listen to the focus event to conditionally show the cancel button. Because the focus event doesn't fire, the clear button is never shown:

https://user-images.githubusercontent.com/943036/181854451-b2a67d50-5f5a-4e14-ba1d-dec356524b65.mov

Notice that it works for multiselect, so I suspect it may be related to virtual focus since it's disabled for multiselects.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/objective-water-12i2w0?file=/src/select-combobox.tsx:1193-1276
2. Click to open the combobox
3. Open the console to confirm the focus event was not logged

### Expected behavior

Fire the focus event, as occurs when using the combobox standalone.

### Workaround

https://github.com/ariakit/ariakit/issues/1688#issuecomment-1200028348

**Comment by diegohaz** [comment]
I can reproduce it. Thanks!

You can access all focus events with `onFocusCapture`:

```jsx
<Combobox onFocusCapture={...} />
```
