### ISSUE TITLE
`setOpen` is not fired when `open` is changed externally

### ISSUE THREAD

**Issue by DaniGuardiola** [ariakit/ariakit#1702]
### Current behavior

Currently, when trying to listen for state changes, it's not possible to fully achieve it through passing a custom setter if you're also controlling the state yourself.

E.g.

```ts
const [open, setOpen] = useState(false)
const dialog = useDialogState({
  open,
  setOpen: (value) => {
    console.log("Dialog open state changed:", value);
    setOpen(value);
  }
});
```

In this example, the log would execute only when the state change is initiated internally, e.g. by pressing escape or clicking outside. However, if I can my own `setState` independently, it won't fire.

Sometimes, it is necessary to have a "listener" to sync unrelated stuff to the state. For example, we need this to reset a system of multiple dialog views to the initial view every time the dialog is opened.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/ariakit-state-listener-issue-v93cvr?file=/src/dialog.tsx
2. Open the dialog with the "Open externally" button
3. See console logs and compare with the button that uses `dialog.toggle` instead

### Expected behavior

In the middle of writing this bug report I realized that this is how standard controlled HTML elements behave: https://codesandbox.io/s/controlled-input-36l2on

But what I was expecting is for `setOpen` to be called every time the state is updated, as a listener of sorts.

### Workaround

Using a dirty ugly effect to react to `open` seems to do the trick, but I wonder how suboptimal such a solution is.

### Possible solutions

Not sure if `setOpen` in the dialog state would be the right place, but I think it'd be nice to have a way to pass a "listener" that is guaranteed to be called when the state changes, however that happens.

I guess this is more of a feature request, or maybe there's something fundamentally wrong with the way we've architected things, but I'd like to at least start a discussion around this.

**Comment by diegohaz** [comment]
As you mentioned, that's how controlled stuff works.

The way you'll deal with this depends on what you want to synchronize with the open state. If it's something external, useEffect is the way to go. Otherwise, you can use the derived state technique.

**Comment by DaniGuardiola** [comment]
Ha that's what I thought, thanks @diegohaz!
