### ISSUE TITLE
Focus popover/button on safari 

### ISSUE THREAD

**Issue by jay-lauret** [ariakit/ariakit#1707]
### Current behavior
There is a focus only on safari with the popover component and button component. See the video:

https://user-images.githubusercontent.com/6999969/182813204-3b5cc7c1-6537-4de2-89fb-ae308a4666df.mov

 I put the example popover on sandbox so you can reproduce the bug, it's only happen with safari (Chrome, firefox ok)

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/xenodochial-wright-x0br82
2. Click on the button to see the bug

### Expected behavior

Not focus

**Comment by diegohaz** [comment]
That's how Safari interprets `:focus-visible`. You can disable the default outline and use only our `[data-focus-visible]` selector if you want.
