### ISSUE TITLE
Popover - a way to keep anchor rect updated

### ISSUE THREAD

**Issue by DaniGuardiola** [ariakit/ariakit#1710]
### Motivation

I need a popover to move in sync with an anchor rect that would move around in some circumstances. Currently, `getAnchorRect` can be passed to the state hook, but it's not "reactive".

### Usage example

I guess the state hook could take another prop that is used in the internal effect/memo dependencies so that it gets repositioned when it changes. Or, the properties (each individual coordinate, etc) could be compared every render to check for updates.

```tsx
const popover = usePopoverState({ anchorRect })
```

### Requirements

- The popover should update it's position when the anchor rect changes.

### Workaround

Currently re-mounting kinda does the trick, but it's very hacky and it breaks with animations. Also, any elements inside will be remounted too, which can be a problem.

### Possible implementations

Update the positioning logic to react to a new `anchorRect` prop in the popover state.

**Comment by diegohaz** [comment]
You can call `popover.render()` whenever the anchor rect changes.

**Comment by diegohaz** [comment]
@DaniGuardiola Does `popover.render()` work for you?

**Comment by DaniGuardiola** [comment]
@diegohaz sorry haven't had the chance to try yet, will update soon.

**Comment by DaniGuardiola** [comment]
@diegohaz it worked pretty well! Closing.
