### ISSUE TITLE
Collection Items are not correctly ordered when adding items from start

### ISSUE THREAD

**Issue by natanelia** [ariakit/ariakit#1747]
### Current behavior

- Adding new collection item that is preceeding all items makes the items array incorrectly ordered.
- When defaultActiveId is not provided, the first focused composite item is not the first item.

![Screenshot 2022-08-12 at 10 54 09 AM](https://user-images.githubusercontent.com/1708681/184282206-0975c477-4e25-4886-b47c-29b55be8bf37.png)

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/nervous-moon-y04dgz
2. See console logs

### Expected behavior

- collection.items is always sorted by DOM position
- when defaultActiveId is not provided, the first focused composite item is the first item.

### Workaround

https://github.com/ariakit/ariakit/issues/1747#issuecomment-1212722085

### Possible solutions

![image](https://user-images.githubusercontent.com/1708681/184283124-5c5bca22-29e4-4d58-8308-ed53721016ad.png)

If it is set to -1, it will add starting items at the end of the array. What we expect is that it is added at the beginning of the array, therefore we set it to 0

**Comment by diegohaz** [comment]
Thanks for reporting it, @natanelia!

This is kind of weird, but it seems to work around the issue:
```jsx
const [items, setItems] = useState([]);
const toolbar = useToolbarState({ items, setItems });
```

**Comment by natanelia** [comment]
The workaround does not seem to fix the issue. https://codesandbox.io/s/nervous-moon-y04dgz

If you saw the issue fixed, it was because of fast refresh. Can try refreshing the browser.

**Comment by diegohaz** [comment]
I tested on Chrome and Safari on macOS. What's the browser you're using?

**Comment by natanelia** [comment]
Was using Edge 104. I just tested again in Edge, Chrome and Safari, found out that using external items state can sometimes fix the bug. But it still happened on multiple refreshes. In Safari, we don't even need external items state to have it fixed (often times).

**Comment by diegohaz** [comment]
Yeah, we need a better workaround. It basically needs to trigger the IntersectionObserver: https://github.com/ariakit/ariakit/blob/f73e982044200abde077c193b9361f057b32af63/packages/ariakit/src/collection/collection-state.ts#L114
