### ISSUE TITLE
Wrong default in `includesBaseElement` JSDoc for Combobox

### ISSUE THREAD

**Issue by DaniGuardiola** [ariakit/ariakit#1755]
### Current behavior

Seems like the JSDoc doesn't account for [this default](https://github.com/ariakit/ariakit/blob/main/packages/ariakit/src/combobox/combobox-state.ts#L73) and it says it's `false` by default.

This is caused by the `ComboboxStateProps` inheriting it from `CompositeStateProps`, in which the JSDoc states that, but it's wrong.

### Steps to reproduce the bug

--

### Expected behavior

--

### Possible solutions

Omit the type from `CompositeStateProps` when extending and manually re-export the property type with the right JSDoc? Maybe too much copy past, wish there was a way to extend/override JSDocs!

**Comment by diegohaz** [comment]
Should be fixed in the latest version.
