### ISSUE TITLE
Select-combobox causes the page to the scroll when using keyboard keys

### ISSUE THREAD

**Issue by georgekaran** [ariakit/ariakit#1811]
### Current behavior

Using a Select + Combobox causes the page to be scrolled to the top when opening using the keyboard (⬆️ or ⬇️).

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/objective-fire-j8n8ky?file=/src/select-combobox.tsx
2. Scroll to the middle of the page
3. Open the `Select` using the keyboard (⬆️ or ⬇️)
4. You should be scrolled to the top of the page

[Video showing the unexpected behavior](https://www.loom.com/share/8d5eeeda41ab4c6584402a19db60c6d8)

### Expected behavior

We should be able to open the Popup without being scrolled to the top of the page.

### Workaround

https://github.com/ariakit/ariakit/issues/1811#issuecomment-1230991008

### Possible solutions

Something related to this line: https://github.com/ariakit/ariakit/blob/e54af965ee90988031c4e2ad5a22d0b8d694253c/packages/ariakit/src/select/select.tsx#L141

**Comment by diegohaz** [comment]
@georgekaran Thanks for reporting.

Workaround:

```jsx
<Select
  moveOnKeyDown={false}
  showOnKeyDown={(event) => {
    event.preventDefault();
    select.show();
    return false;
  }}
/>
```

**Comment by georgekaran** [comment]
Thanks, worked like a charm!

**Comment by diegohaz** [comment]
I think this issue still exists?

**Comment by diegohaz** [comment]
Still happening: https://codesandbox.io/s/https-github-com-ariakit-ariakit-issues-1811-4xpkci
