### ISSUE TITLE
radix dialog focus results in field marked as touched

### ISSUE THREAD

**Issue by PhilGarb** [ariakit/ariakit#1825]
### Current behavior

The [radix dialog component](https://www.radix-ui.com/docs/primitives/components/dialog) auto focuses the first input when it is mounted. Which is a nice UX in my opinion. 

This does however lead to a bug when combined with ariakits Form, because the focused field is marked as touched.
This results in all errors being constantly shown.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/damp-currying-v8wgrz?file=/src/App.js
2. Click on Open in the preview
3. See the error message instantly being shown

### Expected behavior

The field should not be marked as touched from being focused.

**Comment by diegohaz** [comment]
I can't reproduce it with the steps you provided. No error is shown the first time I open the dialog (Chrome 104 macOS).

**Comment by PhilGarb** [comment]
Sorry for that. I must have touched the field, forgot to refresh and then mistook the error as a reproduction. 
After some more debugging I have found the issue to be and overly complex combination of the radix dropdown, radix dialog and ariakits forms. I have simplified it and managed to fix the issue. 
This is not an issue with ariakit.
