### ISSUE TITLE
SelectPopover focus on any focusable element which are above the listbox when Tab is pressed

### ISSUE THREAD

**Issue by georgekaran** [ariakit/ariakit#1828]
### Current behavior

When no other focusable element is present on the DOM, pressing the `Tab` key focus on the elements inside the `Popover` and which are above the `listbox`.

[Video simulating the issue](https://www.loom.com/share/d4bdee8372ef45639f7684c1ff28fa1e)

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/friendly-wu-ijl4vt?file=/src/select-multiple.tsx
2. Open the `Select`
3. Press `Tab` key
4. `button 1` is receiving the focus (Which is above the `listbox` in the DOM tree)

PS: Strangely, if I press `Tab` again the `button 2` will not get the focus.

### Expected behavior

We should not focus on elements that are above the `listbox` inside the `Popover` considering the hierarchy tree.

### Workaround

Set `preserveTabOrder` to false on `SelectPopover`.

**Comment by diegohaz** [comment]
Looks like it's fixed in the latest versions: https://codesandbox.io/s/https-github-com-ariakit-ariakit-issues-1828-425y0j
