### ISSUE TITLE
Should ariakit-react-utils re-export ariakit-utils?

### ISSUE THREAD

**Issue by diegohaz** [ariakit/ariakit#1837]
Following up on #1819, I wonder if the `ariakit-react-utils` package should re-export all `ariakit-utils` modules. This way, when working on framework-specific packages (like `ariakit` or `@ariakit/react`), we don't need to figure out if some function belongs to `utils` or `react-utils` (or `vue-utils`, `svelte-utils`, etc.). We just import all utils from the framework-specific utils package.

Anyway, `ariakit-react-utils` hasn't defined `ariakit-utils` as a dependency in package.json. If we re-export everything from `ariakit-utils`, we need to add it as a dependency. Otherwise, we can define it either as a dependency or a peer dependency.

But I think re-exporting everything makes more sense.

cc @sarayourfriend

**Comment by sarayourfriend** [comment]
I'm not completely against this idea, my only concern with it is that it could potentially get confusing. I like the ergonomic benefits you mentioned but given there will probably be some differences in what is available from each of the library specific utils packages, it might get confusing trying to keep track of what is coming from the shared pool of utilities vs the view-library specific ones.

I don't think it's that big a deal, I just wanted to note it, just in case.
