### ISSUE TITLE
Select Combobox portalled popover breaks when used with Radix Dialog

### ISSUE THREAD

**Issue by Michael-Nielsen** [ariakit/ariakit#1914]
### Current behavior

I'm trying to include a select-combobox inside a dialog based on Radix Dialog however there are several behaviours that break when the popover is portalled (which makes sense with how radix focus guards work!). The only workaround I've been able to figure out is remove the portalling however I'm curious to hear if there are any recommended approaches to make the inter-op smoother without having to resort to disabling portalling.

### Steps to reproduce the bug

https://codesandbox.io/s/youthful-shape-hvmip7?file=/select-combobox.js

### Expected behavior

1. The combobox input should receive focus
2. Keyboard shortcuts should work (arrows, enter)
3. Clicking on items should work

### Workaround

Disable portalling?

**Comment by diegohaz** [comment]
That's not an issue on Ariakit. We can't control how Radix Dialog works.

You can disable the portal or attach `SelectPopover` to another node using the `portalElement` prop.
