### ISSUE TITLE
The select value does not change if no parameters are passed to useSelectState

### ISSUE THREAD

**Issue by Jackardios** [ariakit/ariakit#1918]
### Current behavior

The select value does not change if no parameters are passed to useSelectState

https://user-images.githubusercontent.com/24757335/193998716-95e4bf2b-5551-408e-a71c-5983510b1db0.mov

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/funny-chaplygin-eue0nh
2. Choose any value
3. Select value does not changed

### Expected behavior

Regardless of whether I passed any parameters to useSelectState, the value of the Select should change

**Comment by Jackardios** [comment]
It seems that it does not depend on whether the parameters are passed or not, the select stops working at some random moment

https://user-images.githubusercontent.com/24757335/194002450-1cc2eca2-e612-4444-8f53-d3b4dee2c0a7.mov

**Comment by diegohaz** [comment]
Followed the steps, but I can't reproduce it. What browser/os you're using? Are there additional steps to reproduce the issue?

**Comment by Jackardios** [comment]
@diegohaz
MacOS 10.15.7
Google Chrome 106.0.5249.91

**Comment by Jackardios** [comment]
Also tested in Safari 14.1.2 and Firefox 96.0.2 and everything works as it should

**Comment by Jackardios** [comment]
@diegohaz Found a problem in the [TransOver](https://chrome.google.com/webstore/detail/transover/aggiiclaiamajehmlfpkjmlbadmkledi) extension, if I disable it, then everything works as it should. Sorry to bother you

**Comment by diegohaz** [comment]
That's super weird. I can reproduce it with the extension. The `value` state does get updated in the `Select` component, but the extension somehow doesn't let the DOM update. I'd suggest filling an issue on their repo: https://github.com/artemave/translate_onhover
