### ISSUE TITLE
Add the ability to set the number value for Select and Combobox

### ISSUE THREAD

**Issue by Jackardios** [ariakit/ariakit#1920]
### Motivation

String is currently the only possible value type in Select and Combobox. But a frequent case when we need to specify a number (different kind of ID) as a value. Is it possible to add "number" as a valid value type for Select and Combobox components?

### Usage example

```tsx
const state = useSelectState({
   defaultValue: 123,
});
...
<SelectItem value={123}>Some number</SelectItem>
<SelectItem value="apple">Apple</SelectItem>
```

### Requirements

- The `Select` component must accept a 'number' type for the value
- The `Combobox` component must accept a 'number' type for the value

### Workaround

https://github.com/ariakit/ariakit/issues/1920#issuecomment-1268609316

**Comment by diegohaz** [comment]
Can't you use a string and `parseInt(value)` when consuming it as a number?

**Comment by Jackardios** [comment]
@diegohaz Yes, I can convert to a string as input and back to a number as output, but that makes it a little more difficult to use. It would be easier if the number type is initially valid
