### ISSUE TITLE
`Tab`: support manual activation

### ISSUE THREAD

**Issue by ciampo** [ariakit/ariakit#2007]
### Motivation

Currently, `TabPanel`s are activated automatically when the associated `Tab` receives focus (referred to as "Tabs with automatic activation" on [the W3C website](https://www.w3.org/WAI/ARIA/apg/patterns/tabpanel/)).

However, there are instances in which the automatic activation doesn't fit the UX and keyboard navigation needs.

Is there a change the `Tab` component could support manual activation as well, alongside automatic activation?

### Usage example

Manual activation could be enabled via a new option passed to `useTabState`

### Requirements

- When manual activation is selected, focusing a `Tab` won't changed the currently selected `TabPanel`
- To activate a `TabPanel` when manual activation is selected, the user needs to press the `Enter` or the `Space` key when focusing on the corresponding `Tab`

**Comment by diegohaz** [comment]
Hey @ciampo! That's already supported:

```js
// v1
useTabState({ manual: true });

// v2
useTabState({ selectOnMove: false });
```

**Comment by ciampo** [comment]
That's great to hear! I missed that `selectOnMove` option, for some reason I didn't connect it to manual activation.

Thank you for the quick answer! I'll close this issue.
