### ISSUE TITLE
Throws "Maximum update depth exceeded" 

### ISSUE THREAD

**Issue by ddanielsantos** [ariakit/ariakit#2036]
### Current behavior

I need to render something like this

```mermaid
    flowchart LR
    Select --> Dialog --> Combobox
```

### Steps to reproduce the bug

https://codesandbox.io/s/combobox-repro-cu3v9p

1. [Gist reproduction](https://gist.github.com/ddanielsantos/9af0dd3386cb3b43675830d2f0435e3e)
2. Call stack: ![imagem](https://user-images.githubusercontent.com/80872981/200609002-a35d52cd-d7f6-41cd-8724-d4f566fca078.png)

### Expected behavior

Be able to render nested components

### Workaround

https://github.com/ariakit/ariakit/issues/2036#issuecomment-1307707652

### Possible solutions

Something about these lines:
https://github.com/ariakit/ariakit/blob/e1c3b78818c6605931b772ace0ff7ed17e057459/packages/ariakit-react-utils/src/hooks.ts#L148-L150

**Comment by diegohaz** [comment]
@ddanielsantos Could you please create a CodeSandbox with the reproduction?

**Comment by ddanielsantos** [comment]
Sure! here it is: https://codesandbox.io/s/combobox-repro-cu3v9p

**Comment by diegohaz** [comment]
Thanks! That does seem like a bug. Is it possible for your use case to render the Dialog outside of SelectPopover?

**Comment by ddanielsantos** [comment]
Yes, it is

**Comment by diegohaz** [comment]
This should be fixed in the latest version: https://codesandbox.io/s/https-github-com-ariakit-ariakit-issues-2036-mgoljo
