### ISSUE TITLE
[Docs Website] Add Links for the /components and /examples page in the navigation menu

### ISSUE THREAD

**Issue by wkrueger** [ariakit/ariakit#2044]
### Motivation

Scope: website/docs

It took long for me tho notice the `/components` and `/examples` page existed, since I was linearly navigating from the breadbrumb.

### Usage example

Add links when clicking the sub menus

![image](https://user-images.githubusercontent.com/2209181/201411354-c1b34e10-3f36-4a36-b5da-35227ff9af9b.png)

### Requirements

Docs website.

**Comment by diegohaz** [comment]
Thanks! I agree with that.
