### ISSUE TITLE
auto scrolling events can interrupt link handlers on combobox link items

### ISSUE THREAD

**Issue by eleith** [ariakit/ariakit#2056]
### Current behavior

when using combobox with link items, the auto scrolling behavior that tries to keep the item list and input in view can interrupt the link handler, resulting in the item being focused but the link not being followed

### Steps to reproduce the bug

1. using a mobile device or a small browser window is needed
2. go to the [combobox link example](https://ariakit.org/examples/combobox-links)
3. focus on the input so the popover is visible
4. position the scroll bar such that the input and the last combobox item (the ariakit homepage) is essentially cut off ![Screenshot 2022-11-18 at 15-55-32 Combobox with links - Ariakit](https://user-images.githubusercontent.com/284832/202822089-28af9ddb-1785-48cf-884e-7bdd91f0a343.png)
5. select the last item (the ariakit homepage)
6. notice that the window now auto scrolls to try and make the input and the popover visible and the item you selected is now highlighted

### Expected behavior

selecting on any item that is a link should result in being redirected to the link (or a new window being open if target is set)

### Workaround

setting `virtualFocus` to `false` on the combobox state will prevent the link handler from being interrupted

### Possible solutions

i have seen at least one [preventDefault](https://github.com/ariakit/ariakit/blob/1937330ffc4db2b11c2007f3983a77ae97fa2a90/packages/ariakit/src/composite/composite-item.tsx#L269) that was interrupting the link handler, but there could be more, depending on the path taken by the various listeners of combobox item, the popover and the window itself

**Comment by georgekaran** [comment]
Does this issue still exists?

I've just tried following the steps and everything worked as expected.

**Comment by diegohaz** [comment]
I can still reproduce it (Google Chrome 120, macOS Sonoma 14.2)

https://github.com/ariakit/ariakit/assets/3068563/879e9cf5-1f31-44df-ad45-76c1eb897321
