### ISSUE TITLE
Unique names for Item and Value types

### ISSUE THREAD

**Issue by folz** [ariakit/ariakit#2092]
### Motivation

I'm trying to use ariakit in a build environment which is not compatible with node_modules resolution. Instead of installing ariakit with npm/yarn, I instead need to pre-compile it into a single `index.js` and `index.d.ts` file to be included in the build.

The best way I've found to bundle `.d.ts` files so far is https://github.com/timocov/dts-bundle-generator, which has a constraint that all bundled type names (bundled based on usage, irrespective of whether they're `export`ed) must be globally unique. It does not mangle type names if they conflict.

Due to ariakit's naming practices, this turned out to be almost a non-issue. The only types names which conflict are the Item and Value types referenced here:

Item
* https://github.com/ariakit/ariakit/blob/main/packages/ariakit/src/collection/__utils.ts#L4
* https://github.com/ariakit/ariakit/blob/main/packages/ariakit/src/composite/__utils.ts#L265
* https://github.com/ariakit/ariakit/blob/main/packages/ariakit/src/select/__utils.ts#L6
* https://github.com/ariakit/ariakit/blob/main/packages/ariakit/src/tab/tab-state.ts#L15
* https://github.com/ariakit/ariakit/blob/main/packages/ariakit/src/form/form-state.ts#L32
* https://github.com/ariakit/ariakit/blob/main/packages/ariakit/src/combobox/combobox-state.ts#L25

Value
* https://github.com/ariakit/ariakit/blob/main/packages/ariakit/src/checkbox/checkbox-state.ts#L5
* https://github.com/ariakit/ariakit/blob/main/packages/ariakit/src/select/select-state.ts#L27

Would you be open to a PR which updates these type names to be unique based on the pattern they're used in? And if so, do you have any preference for how these should be named? I am happy to make this PR.

Also I understand that this is a very niche feature request and you may not want to change the names of these types. If so, please feel free to reject the request and I can look for another workaround.

### Usage example

N/A

### Requirements

Declared types would have globally unique names.

**Comment by diegohaz** [comment]
Hi @folz

While I'd be open to a PR, I believe that would be a better fit for the `dts-bundle-generator` library. We could change our codebase today, but we can't guarantee that local types will always be globally unique in the future. While working on #2057, I renamed those `Item` and `Value` types, but ended up re-introducing them as aliases to make the code easier to read.

For example:
```ts
export function createCompositeStore<
  T extends CompositeStoreItem = CompositeStoreItem
>({
  ...
```

vs.

```ts
export function createCompositeStore<T extends Item = Item>({
  orientation = "both",
  ...
```

A solution I can think of is `dts-bundle-generator` inlining these local types or renaming them to a globally unique name. This is also possible as a pre-build step with the help of something like ts-morph.

**Comment by rodneyfolz-asana** [comment]
Hello from my work account! What you've said makes sense to me - I agree that it's more correct for `dts-bundle-generator` (or whatever other lib) to handle renames, and I also agree that asking ariakit to stick to globally unique type names is not a sustainable ask. Since you're okay with a PR, I think my plan will be to make one in order to have a point release that does meet the needs of the build environment, even if ariakit does change in the future. That should enable me to bring in ariakit while giving enough time to find a more sustainable workaround. Thank you for your thoughts.
