### ISSUE TITLE
get this Warning: This synthetic event is reused for performance reasons

### ISSUE THREAD

**Issue by clementloridan** [ariakit/ariakit#2093]
### Current behavior

Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `currentTarget` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
(anonymous) @ consolePlugin.ts:175
overrideMethod @ react_devtools_backend.js:4026
printWarning @ react-dom.development.js?a814:88
error @ react-dom.development.js?a814:60
warn @ react-dom.development.js?a814:8566
get @ react-dom.development.js?a814:8560
handleFocusVisible @ focusable.js?1321:256
applyFocusVisible @ focusable.js?1321:291

### Steps to reproduce the bug

Nothing special

### Expected behavior

Should doesn't show this warning

### Possible solutions

https://github.com/ariakit/ariakit/issues/2093#issuecomment-1335454831

**Comment by diegohaz** [comment]
I mean, did you get that error in React 16? We only support React 17+, so if that's the case, the correction may not be necessary.
