### ISSUE TITLE
Feature Request: Allow menu to remain open when focus shifts away from component

### ISSUE THREAD

**Issue by craigcarlyle** [ariakit/ariakit#2162]
### Motivation

My application currently has a few instances where selecting a menu item will trigger an event that will cause the focus to shift outside of the menu component. This currently causes the menu to close, even if the `hideOnSelect` value is set to `false`.

### Usage example

```jsx
const state = useMenuState({ closeOnBlur: false })
```

### Requirements

- The menu component must be able to remain open after focus shifts elsewhere.

**Comment by diegohaz** [comment]
Use the `hideOnInteractOutside` prop:

```jsx
<Menu hideOnInteractOutside={false} />

<Menu hideOnInteractOutside={(event) => false} />
```

**Comment by rfgamaral** [comment]
@diegohaz My experience with `ariakit` is limited, but I'm not sure how to use `hideOnInteractOutside` with `useMenuState`, or if it's even possible. Is it even possible? What am I missing? 🤔

P.S: Hope you had some nice holidays 😊
