### ISSUE TITLE
Can't deselect Checkbox with useCheckboxState when using string values

### ISSUE THREAD

**Issue by diegohaz** [ariakit/ariakit#2164]
### Current behavior

Can't deselect Checkbox with useCheckboxState when using string values

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/ariakit-checkbox-string-value-bug-plktk0
2. Select checkbox
3. Try to toggle it

### Expected behavior

Should be able to deselect it.

### Workaround

We can work around that by using our own state instead of `useCheckboxState`.

**Comment by lwsys** [comment]
When I remove the "value" attribute, the component work successfully. So,may be the "value" attribute cause the problem?

**Comment by gnapse** [comment]
> When I remove the "value" attribute, the component work successfully. So,may be the "value" attribute cause the problem?

Bingo! The combination of providing a `value` attribute, **alongside** not initializing `defaultValue: []` made things not work.

We gave it a try to fix it. See #2223.
