### ISSUE TITLE
Combobox not processing words with accents

### ISSUE THREAD

**Issue by georgekaran** [ariakit/ariakit#2203]
### Current behavior

Using words with accents in the `Combobox` with `autoSelect` causes the input not to process the accent as expected. But, if I clear the input without closing the popover, it works as expected.

[See the video](https://www.loom.com/share/bbe071a4e30e413a8afd3d77fcb2aab8).

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/cold-grass-tsvptg
2. Type any word that contains accents such as `é`

### Expected behavior

It should be able to use words with accents without needing to make a second attempt.

### Workaround

https://github.com/ariakit/ariakit/issues/2203#issuecomment-1378212426

### Possible solutions

https://github.com/ariakit/ariakit/issues/2203#issuecomment-1378212426

Adding the following code `combobox.tsx` seems to do the work
![image](https://user-images.githubusercontent.com/23644327/211181615-56c1e14f-2e45-4ef7-8a12-0b991931711f.png)

Let me know if this seems to be the right path, then I can open a PR to fix this issue.

**Comment by diegohaz** [comment]
We probably need to check if the change event `isComposing` before setting the `valueChangedRef` value:

https://github.com/ariakit/ariakit/blob/1bfe5194ff672eaa437f98295fdd98226434b069/packages/ariakit/src/combobox/combobox.ts#L250

You can fix it in userland by turning `autoSelect` on/off on composition end/start:

```jsx
const [autoSelect, setAutoSelect] = useState(false);

<Combobox
  autoSelect={autoSelect}
  onCompositionStart={() => setAutoSelect(false)}
  onCompositionEnd={() => setAutoSelect(true)}
/>
```

**Comment by gnapse** [comment]
I was trying to fix this one, but I'm confused. I'm not entirely sure how to reproduce. With `autoSelect` turned on, and trying with different combinations of using an accented character in the items and/or in the search input, auto-selecting the first item always worked.

It also does not help that the link to the screen recording is no longer operational, so it may be the case that we are not sure what to reproduce, and we're trying the wrong way.

I'd appreciate if this is clarified. Like, having a new video example, maybe uploaded here to Github so it no longer expires.

**Comment by diegohaz** [comment]
@gnapse This is what I see when I type `é`. The bug happens before autoSelect is triggered for the first time (that's why it works the second time).

https://user-images.githubusercontent.com/3068563/223430578-7a184afc-0516-45f3-9d36-4acff410d352.mp4

**Comment by georgekaran** [comment]
Hey guys, one thing that I noticed is that this was only happening on Apple devices, for instance, if I try to type `é` using Windows or Linux, it just works as expected.

**Comment by gnapse** [comment]
> This is what I see when I type é. The bug happens before autoSelect is triggered for the first time (that's why it works the second time).

@diegohaz that's what we see too. But I do not see the difference vs. when typing a regular non-accented character.

https://user-images.githubusercontent.com/15199/223447620-fd8f25d9-fd3d-45d1-861f-f78a286bf795.mp4

**Comment by diegohaz** [comment]
@gnapse The problem is that it produces `'e` instead of `é` the first time I type it.

**Comment by gnapse** [comment]
Hmmm, that's not my experience. Anyway, we were trying to work on this one, but I think we'll pass and leave for someone that understands it and can reproduce it.
