### ISSUE TITLE
Can't pass the `as` prop from a parent down into Ariakit components

### ISSUE THREAD

**Issue by vivshaw** [ariakit/ariakit#2219]
### Current behavior

Howdy, y'all. We've been running into a problem with the `as` prop that feels pretty basic, but we can't for the life of us figure out if it's a design decision in Ariakit, or just a mistake we're making.

Here's what we hope to do: we're building a design system, and hoped to use Ariakit as a base for some of our trickier components. One of them is a branded Tooltip. We want to build a component that has basically the same interface as [Ariakit's tooltip](https://ariakit.org/components/tooltip), including `as` polymorphism, but has branded styles applied to the tooltip bubble, so that we don't have to have engineers re-apply those styles at every use site.

We figured it'd be pretty easy to just pass down the `as` prop from a parent component, and it does run, but we hit a brick wall getting it to typecheck! :sweat_smile: I have [a minimal repro](https://codesandbox.io/s/ariakit-tooltip-polymorphism-example-bfukyv?file=/src/tooltip.tsx) of two different techniques we tried- the first was borrowing the `as` prop type from Ariakit's source. The second was referencing it with an indexed type. Both run just fine, but neither typecheck.

We've referenced [the `as` discussion in here](https://github.com/ariakit/ariakit/issues/1245) and [here](https://github.com/ariakit/ariakit/issues/226) but didn't find anything that seemed clearly relevant.

Does Ariakit support a use case like this, and if so, d'you happen to know what we messed up?

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/ariakit-tooltip-polymorphism-example-bfukyv?file=/src/tooltip.tsx
2. For "copy the `as` type from Ariakit", see the explanatory comment lines 14-20, and the typecheck fail line 35 (inside the component).
3. For "reference `as` with an indexed type", see the explanatory comment lines 46-52, and the typecheck fail line 87 (at the use site).

### Expected behavior

It should be possible to define components that wrap Ariakit components and pass down the `as` prop, that typecheck correctly.

### Possible solutions

If there's a simple way to do this, pop it in the docs? I'd be happy to make a docs PR if we work out a solution!

**Comment by vivshaw** [comment]
Some more, less crucial but potentially useful info:

### Other things we tried

We also tried a more bull-in-a-china-shop approach where I copied the whole type heirarchy from Ariakit so I could define our component props as:

```TypeScript
export type TooltipPropsWithAs<T extends As> = Props<
  Options<T> & TooltipProps
>
```

That also didn't work, and I assumed was not what Ariakit intended anyway, so I didn't pop that in the repro Codesandbox. If this _is_ helpful, I can pop up a repro for that too. Just lemme know!

### Why we wanna do this

To ensure this ain't an X-vs-Y problem, I figure I should say _why_ we want to do this. Our reasoning is about focus state accessibility. When we pass one of our own `Button`s to an Ariakit `TooltipAnchor` as a child, both the Button and Wrapper are focusable- so there are two focus rings for keyboard users! First `Tab` gets the ring around the `TooltipAnchor`, so they can see the Tooltip but not interact with the Button. Second `Tab` gets the ring around the Button, so they can interact, but the Tooltip is gone. The `as` prop nicely solves this- now there's just one component and one focus ring.

So, that's why we wanna be able to use the `as` prop for our branded components and pass it to the underlying `TooltipAnchor`. If we're approaching this the wrong way, and there's a simpler Blessed Path to achieve this, let us know!

**Comment by danielwaltz** [comment]
For what it's worth, I am running into the same road block trying to implement a simple wrapping component for `Button` called `AppButton` with baked in styling and additional functionality required for my app.

The closest I've come to a solution (that worked using `reakit` before starting to migrate to `ariakit`), is a custom version of react's `forwardRef` I called `forwardRefWithAs`:

```ts
import {
  ComponentProps,
  ElementRef,
  forwardRef,
  ForwardRefRenderFunction,
} from 'react';
import { As } from 'ariakit-react-utils/ts/types';

type PropsWithAs<Props, Type extends As> = Props &
  Omit<ComponentProps<Type>, 'as' | keyof Props> & { as?: Type };

type ComponentWithAs<Props, DefaultType extends As> = {
  <Type extends As>(
    props: PropsWithAs<Props, Type> & { as?: Type }
  ): JSX.Element;
  (props: PropsWithAs<Props, DefaultType>): JSX.Element;
};

const forwardRefWithAs = <Props, DefaultType extends As>(
  component: ForwardRefRenderFunction<ElementRef<DefaultType>, Props>
) => {
  return forwardRef(component) as unknown as ComponentWithAs<
    Props,
    DefaultType
  >;
};

export default forwardRefWithAs;
```

And its usage looks like this:


```ts
import { ElementRef, ForwardedRef } from 'react';
import { Button, ButtonProps } from 'ariakit';
import AppLink from '@/components/AppLink';
import forwardRefWithAs from '@/utils/forwardRefWithAs';

type AsElement = 'button' | 'a' | 'span' | 'label' | typeof AppLink;

export interface AppButtonProps extends ButtonProps<AsElement> {
  type?: ButtonProps['type'];
}

const AppButton = (
  { children, ...rest }: AppButtonProps,
  ref: ForwardedRef<ElementRef<AsElement>>
) => {
  return (
    <Button ref={ref} as="button" {...rest}>
      {children}
    </Button>
  );
};

export default forwardRefWithAs<AppButtonProps, AsElement>(AppButton);
```

I would say also a bull in a china shop approach, but it's a solution that _finally_ actually worked for me, so hopefully it'll help you until official documentation or support for wrapping components like this is available!

The obvious drawback is needing to explicitly define the list of supported elements, but I could also see that being a positive thing!

**Comment by diegohaz** [comment]
Adding TypeScript support for components that use the `as` prop requires significant effort and introduces unnecessary complexity to the codebase. While we could expose the internal methods we use to create these components, they won't be stable.

If you'd like to proceed with this approach, you can `import { createComponent } from "@ariakit/react-core/utils/system"`. However, please be aware that the `@ariakit/react-core` package, which is internally used by `@ariakit/react`, will not adhere to semver for the foreseeable future.

Alternatively, you can come up with your own system methods that add the `as` prop to your components. I put together this CodeSandbox that you can use as a reference if you want to embark on this adventure: https://codesandbox.io/s/typescript-as-prop-dicj8?file=/src/App.tsx

Nevertheless, I would advise against pursuing this path. Instead, I recommend using the newly introduced `render` prop, as demonstrated in this example: https://ariakit.org/examples/tooltip-framer-motion
