### ISSUE TITLE
Typescript node16/nodenext module resolution not resolving correctly

### ISSUE THREAD

**Issue by PhilGarb** [ariakit/ariakit#2220]
### Current behavior

While migrating a project to esm I came upon an issue with the currently recommended and configured approach of using this library. 

It is recommended to import individual components from subpaths:
`import { Combobox } from "ariakit/combobox"`

This works fine in commonjs, but typescript fails to resolve the type when switching to 
`moduleResolution: node16` or `moduleResolution: nodenext`.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/new-thunder-4uejmy?file=/src/ImportError.tsx
2. Open ImportError.tsx

### Expected behavior

No error should be shown and full type information should be available.

### Workaround

I do not know of a way to handle this as the library consumer.

### Possible solutions

The main issue here is that typescript is not using the types and main fields with these newer moduleResolution modes. The alternative is the exports property that mimics the behavior, but also allows the proper configuration of subpath exports. 
https://www.typescriptlang.org/docs/handbook/esm-node.html
https://nodejs.org/api/packages.html#subpath-exports

I think this needs to be added to support the resolution. If the import from the nested folder structure like `ariakit/combobox` is not that important a simple addition of:

```
  "exports": {
    "./types": "./ts/index.d.ts"
  },
```

in the ariakit-react-utils and ariakit-utils packages would allow the types to be resolved in ariakit itself.

**Comment by diegohaz** [comment]
Related: #1508

**Comment by camiaei** [comment]
hi, do you know of any workaround? thanks

**Comment by camiaei** [comment]
I was writing "ariakit/Combobox" following an example from the Ariakit docs. I changed it to lowercase and now it works (Next 13.1.6 via create-t3-app). My tsconfig fwiw:

```
{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "checkJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "noUncheckedIndexedAccess": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", "**/*.cjs", "**/*.mjs"],
  "exclude": ["node_modules"]
}
```

**Comment by PhilGarb** [comment]
@camiaei I have to patches for ariakit and ariakit-react-utils. The solution is to use the exports field in package.json to properly expose the subpath exports.

ariakit > package.json:
```  json
"exports": {
    "./*": {
      "import": "./esm/*/index.js",
      "require": "./cjs/*/index.js",
      "types": "./ts/*/index.d.ts"
    },
    ".": {
      "import": "./esm/index.js",
      "require": "./cjs/index.js",
      "types": "./ts/index.d.ts"
    }
  },
```

and ariakit-react-utils > package.json:

``` json
  "exports": {
    "./types": {
      "import": "./esm/index.d.ts",
      "require": "./cjs/types.ts",
      "types": "./ts/index.d.ts"
    },
    ".": {
      "import": "./esm/index.js",
      "require": "./cjs/index.js",
      "types": "./ts/index.d.ts"
    }
  },
```

This seems to be working for me, but I not sure about the general implications of this change.

**Comment by diegohaz** [comment]
This should be fixed with `@ariakit/react`.
