### ISSUE TITLE
Website newsletter link broken

### ISSUE THREAD

**Issue by wil93** [ariakit/ariakit#2227]
### Current behavior

First of all, there are two different websites that currently link to this repository: https://ariakit.org/ and https://reakit.io/

Both of those websites have a newsletter, I tried signing up to that newsletter but I get redirected to this pages respectively: 

- https://newsletter.ariakit.org/  (from ariakit.org)
- https://www.getrevue.co/profile/diegohaz/add_subscriber  (from reakit.io)

There is a scary-looking warning saying that the project is shut down (I guess it's talking about Revue, which is unrelated to Ariakit).

### Steps to reproduce the bug

1. Visit the website ariakit.org / reakit.io
2. Try signing up for the newsletter

### Expected behavior

The newsletter should be available (or if there is no newsletter anymore, the link shouldn't be there)

Also, maybe reakit.io should redirect to ariakit.org?

**Comment by diegohaz** [comment]
Yes, Revue was shut down, and I am still deciding where to migrate to (open to suggestions). I'm working on significant updates to the website, so I'll either remove the newsletter link or replace it with the new newsletter service.

**Comment by diegohaz** [comment]
Fixed: https://newsletter.ariakit.org
