### ISSUE TITLE
Intercom widget is unusable when a modal dialog is open

### ISSUE THREAD

**Issue by Dremora** [ariakit/ariakit#2232]
### Motivation

I want to display Intercom widget when a modal dialog is open. Currently, clicking on Intercom widget closes the modal.

Note that I still want the dialog to behave as a modal - e.g. not be able to interact with the body, I want to make modal closable on click outside, but make Intercom widget an exception to this.

This likely applies to any other support widgets, as they all function in a similar way.

### Usage example

Option 1: provide reference or selector to the elements that are allowed to stay interactive
Option 2: elements with a special attribute will always stay interactive

### Requirements

It should be possible to exclude certain HTML elements from being affected (they should be tabbable, shouldn't have `aria-hidden` set, clicking on them shouldn't close the modal)

### Workaround

The only workaround I have right now is to hide the widget altogether, but that's undesirable from product perspective.

**Comment by diegohaz** [comment]
Hi @Dremora!

I think that may be already possible from user land (although we can probably make that easier in the library). Could you put together a simple example on CodeSandbox, Blitz, or a repo so we can play with it?

**Comment by Dremora** [comment]
I can confirm the new solution works! The elements I have to pass to `getPersistentElements` are:

`.intercom-lightweight-app, #intercom-container`
