### ISSUE TITLE
Hovercard hides unexpectedly when anchor uses absolute position and hovercard has the `modal` prop

### ISSUE THREAD

**Issue by gnapse** [ariakit/ariakit#2238]
### Current behavior

When moving the mouse over the anchor after the hovercard was already shown, the hovercard gets unmounted and re-mounted repeatedly.

<details><summary>Screen recording</summary>
<p>

https://user-images.githubusercontent.com/15199/231205933-971b77ba-cffd-46a2-8b0c-00bbec59ef0d.mp4

</p>
</details> 

### Steps to reproduce the bug

1. Visit https://ariakit.org/components/hovercard
2. Edit the live example to have the following changes in place

```diff
 export default function Example() {
   const hovercard = useHovercardState({ gutter: 16 });
   return (
-    <div className="wrapper">
+    <div className="wrapper" style={{ position: 'absolute', inset: '100px' }}>
       <HovercardAnchor
         state={hovercard}
         href="https://twitter.com/ariakitjs"
         className="anchor"
       >
         @ariakitjs
       </HovercardAnchor>
-      <Hovercard state={hovercard} className="hovercard">
+      <Hovercard state={hovercard} className="hovercard" modal backdrop={false}>
         <img
           src="https://pbs.twimg.com/profile_images/1547936373243490306/dSn6Am0o_400x400.jpg"
           alt="Ariakit"
           className="avatar"
         />
```

<details><summary>Full edited example code</summary>
<p>

```js
import {
  Hovercard,
  HovercardAnchor,
  HovercardHeading,
  useHovercardState,
} from "ariakit/hovercard";
import "./style.css";

export default function Example() {
  const hovercard = useHovercardState({ gutter: 16 });
  return (
    <div className="wrapper" style={{ position: 'absolute', inset: '100px' }}>
      <HovercardAnchor
        state={hovercard}
        href="https://twitter.com/ariakitjs"
        className="anchor"
      >
        @ariakitjs
      </HovercardAnchor>
      <Hovercard state={hovercard} className="hovercard" modal backdrop={false}>
        <img
          src="https://pbs.twimg.com/profile_images/1547936373243490306/dSn6Am0o_400x400.jpg"
          alt="Ariakit"
          className="avatar"
        />
        <HovercardHeading className="username">Ariakit</HovercardHeading>
        <p>Toolkit for building accessible web apps with React.</p>
        <a href="https://twitter.com/ariakitjs" className="button">
          Follow
        </a>
      </Hovercard>
    </div>
  );
}
```

</p>
</details> 

Summary of the changes:

1. Make the anchor be placed inside an absolutely positioned element
2. Use `modal` mode in the hovercard so that it is rendered right inside the `body` element through a portal

> **Note**
> The `backdrop={false}` is not important. With a backdrop in place, the only change is mentioned below in the "Possible solutions" section.

### Expected behavior

The hovercard should remain visible as long the mousemove event happens within the anchor element.

### Workaround

```jsx
<Hovercard modal autoFocusOnShow />
```

### Possible solutions

No idea. But I did find this when digging into the problem causes:

The check `contains(anchor, target)` in the following line of code is returning `false`.

https://github.com/ariakit/ariakit/blob/764d96720b608c5f1c65a29e42990e3258366cc4/packages/ariakit/src/hovercard/hovercard.tsx#L51

The reason being that the `target` is the `<body />` element[^1], and not an element inside the anchor.

[^1]: If a backdrop is in place, the `target` during the mouse move event is the backdrop element instead.

**Comment by diegohaz** [comment]
> 2\. Use `modal` mode in the hovercard so that it is rendered right inside the `body` element through a portal

You probably want to use the `portal` prop, not `modal`.

The `modal` prop should make the popup behave as a modal dialog. That is, the focus should be trapped inside it, and elements outside shouldn't be accessible.

That said, you're reporting a valid bug if the intention is to really make it `modal`.

The `autoFocusOnShow` prop should be set to `true` by default when the `modal` prop is `true`:

https://github.com/ariakit/ariakit/blob/764d96720b608c5f1c65a29e42990e3258366cc4/packages/ariakit/src/hovercard/hovercard.tsx#L82-L86

But, apparently, it's not working.

The workaround is to explicitly set `autoFocusOnShow`:

```jsx
<Hovercard modal autoFocusOnShow />
```

**Comment by gnapse** [comment]
Oh well, indeed, `portal` is what I want instead of `modal`. That fixes it for me.

I'll leave it to you to decide if you want to keep this open. I actually wonder if the hovercard should support `modal` at all.

**Comment by diegohaz** [comment]
Yeah, for the most direct use case of hovercard, `modal` doesn't make sense. But there are other uses for hovercard where it could make sense. For example, one could set `modal={wasTriggeredByKeyboard}`.

**Comment by diegohaz** [comment]
> But, apparently, it's not working.
> 
> The workaround is to explicitly set `autoFocusOnShow`:
> 
> ```js
> <Hovercard modal autoFocusOnShow />
> ```

Closing this since the bug above seems to be fixed already.
