### ISSUE TITLE
Is the defaultValue of radio deprecated？

### ISSUE THREAD

**Issue by septem1997** [ariakit/ariakit#2260]
### Current behavior

In the previous API，there is a props defaultValue in useRadioState but not in the new useRadioStore。Or is there any alternative? 

### Steps to reproduce the bug

call useRadioStore

### Expected behavior

exist defaultValue in useRadioStore or any alternative

### Workaround

```jsx
const [value, setValue] = React.useState("defaultValue");
const radio = useRadioStore({ value, setValue });
```

**Comment by diegohaz** [comment]
No, it should be there. I think we missed it somehow 🤦‍♂️

It should be here:

https://github.com/ariakit/ariakit/blob/b88ce64e6e1946cfeaebf4784596adea58fe0caf/packages/ariakit-core/src/radio/radio-store.ts#L27

Similar to the checkbox store:

https://github.com/ariakit/ariakit/blob/b88ce64e6e1946cfeaebf4784596adea58fe0caf/packages/ariakit-core/src/checkbox/checkbox-store.ts#L22-L27
