### ISSUE TITLE
FormRadio throws unexpected `CompositeItem must be wrapped in a Composite component` error

### ISSUE THREAD

**Issue by Saeris** [ariakit/ariakit#2281]
### Current behavior

When using the `FormRadio` component as documented in the doc comment example, the following error is thrown: 

> `CompositeItem must be wrapped in a Composite component`

Here is the example usage from the source code: https://github.com/ariakit/ariakit/blob/c54e8e6335a063d23ec168a155b5806b9082953a/packages/ariakit-react-core/src/form/form-radio.ts#L80-L95

The same error occurs when building a custom FormRadio component using the `useFormRadio()` hook.

### Steps to reproduce the bug

Error can be observed in this CodeSandbox: https://codesandbox.io/p/sandbox/ariakit-formradio-component-error-6cu7n1?file=%2Fsrc%2Fpages%2Findex.tsx

### Expected behavior

FormRadio + FormRadioGroup should behave in a manner similar to their Radio + RadioGroup counterparts

### Workaround

https://github.com/ariakit/ariakit/issues/2281#issuecomment-1514982293

**Comment by diegohaz** [comment]
Thanks, looks like we're not passing the store to the underlying `Radio` component.

**Comment by diegohaz** [comment]
As a workaround, you can replace `FormRadioGroup` with `RadioGroup` and manually provide the radio store:

```jsx
const form = useFormStore({
  defaultValues: {
    color: ``,
  },
});
const radio = useRadioStore();

return (
  <Form store={form}>
    <RadioGroup store={radio}>
      <RadioField name={form.names.color} value="red">
        Red
      </RadioField>
      <RadioField name={form.names.color} value="green">
        Green
      </RadioField>
      <RadioField name={form.names.color} value="blue">
        Blue
      </RadioField>
    </RadioGroup>
  </Form>
);
```
