### ISSUE TITLE
Unintuitive behavior with `useValidate()` hook and built-in input validations

### ISSUE THREAD

**Issue by Saeris** [ariakit/ariakit#2282]
### Current behavior

When using the `useValidate()` hook from `useFormStore()`, user-defined error messages do not always apply when used in conjunction with the built-in input validation attributes such as the `required` attribute. This is due both to the hierarchy of the component tree imposing a specific execution order on when errors are set, and because these errors are set asynchronously inside of the `useFormField()` hook, which causes these values to be updated as a side-effect outside of React's render loop.

I believe I've narrowed this down to this section of the code: https://github.com/ariakit/ariakit/blob/c54e8e6335a063d23ec168a155b5806b9082953a/packages/ariakit-react-core/src/form/form-field.ts#L91-L99

Because this hook calls `useValidate()` inside the `FormField` component (or custom implementation with `useFormField()`), this effect will fire _after_ any user-defined call of `useValidate()` either defined at the parent Form level, or at the custom Field component level depending on the specific implementation and ordering of hooks, in addition to whether the callback is asynchronous or not.

Because the implementation inside of `useFormField()` is asynchronous, this means that unless the user is _also_ using an asyc callback, the `useFormField()` internals will apply _last_, overriding any user-defined custom error messages. Even then, other factors such as race conditions may apply.

This results in a very unintuitive behavior for how user-defined custom error messages are defined for custom form fields.

### Steps to reproduce the bug

Behavior can be observed in [this CodeSandbox](https://codesandbox.io/p/sandbox/ariakit-forminput-validation-bug-trj2oc?file=%2Fsrc%2Fpages%2Findex.tsx) or [this Replay](https://app.replay.io/recording/ariakit-form-validation-error--20ec7553-7812-4eb6-a686-6996e57682bd)

Once the page has loaded:

1. Click the Name field, observe that the default browser `required` error is displayed
1. Click the Favorite Fruit select drop-down menu, but don't select an item, observe that the Name field's error has changed to the custom error message defined in the `useValidation()` hook

### Expected behavior

I would expect that errors for form inputs would be applied in this order:

1. The default browser error message is gathered from the Constraint Validation API
2. Then, any user defined custom errors that are defined at the parent Form level are applied
3. Finally, any user defined custom errors that are defined at the component level are applied

### Workaround

https://github.com/ariakit/ariakit/issues/2282#issuecomment-1515098325

### Possible solutions

Presently I'm not sure what the best solution here is, but I think it needs to involve some way to override the internal behavior of the `useFormField()` hook at the lines linked to above.

One idea that came to mind was an API for the user to provide an "error map" that would facilitate defining custom errors for the common [ValidityState](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState) types from the Constraint Validation API before falling back to whatever message is set by default from the browser on these lines: https://github.com/ariakit/ariakit/blob/c54e8e6335a063d23ec168a155b5806b9082953a/packages/ariakit-react-core/src/form/form-field.ts#L96-L98

Another possible solution would be the addition of a `useStore()` hook returned in `useFormField()`''s props, or via a callback added to `FormFieldOptions` that would allow the user to hook into the store obtained automatically from context to modify the form store _after_ all of `useFormField()`'s internals have executed. This would also help to satisfy some ugly workarounds I've had to write that necessitated passing in the form state as a `store` prop on a custom field component when I'd rather just have all of my custom inputs automatically obtain the form store via context. This would help to eliminate scenarios such as:

```ts
function MyForm() {
  const form = useFormStore({ defaultValue: { name: "" } });
  return (
    <Form store={form}>
      <NameInput store={form} name={form.names.name} />
    </Form>
  );
}

function NameInput({ store, name, ...props }) {
  store.useValidate(() => {
    const value = store.getValue(name);
    if (value.length < 3) {
      store.setError(name, "Name must be at least 3 characters long");
    }
  });
  return <FormInput name={name} {...props} />;
}
```

Which comes from the [Form Custom Validation Docs](https://ariakit.org/components/form#custom-validation) whereby `NameInput` _requires_ that the `store` prop is passed in for its internal custom validation to work.

I would also like to see better documentation and examples of how to define custom errors for forms. I ran into this problem just following along with the existing example and not understanding why my custom message wasn't being applied to the text input. This wasn't an issue I had observed in previous versions of Ariakit before the state refactor discussed in #1875

**Comment by diegohaz** [comment]
We can potentially use [`setCustomValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setCustomValidity) internally to make the error messages consistent.

> This would also help to satisfy some ugly workarounds I've had to write that necessitated passing in the form state as a `store` prop on a custom field component when I'd rather just have all of my custom inputs automatically obtain the form store via context.

Could you elaborate more on that?

This is how you'd pass the form store to your components via context:

```tsx
const FormContext = React.createContext<Ariakit.FormStore | null>(null);

function Form() {
  const form = Ariakit.useFormStore();
  return (
    <FormContext.Provider value={form}>
      <Ariakit.Form store={form}>
        <MyField />
      </Ariakit.Form>
    </FormContext.Provider>
  );
}

function MyField() {
  const form = React.useContext(FormContext);
  ...
}
```

**Comment by Saeris** [comment]
> This is how you'd pass the form store to your components via context:

Hadn't seen this documented anywhere, so hadn't tried it yet. I've only seen examples like the one I linked whereby the store is passed explicitly to the component.

**Comment by diegohaz** [comment]
Yeah, there are many things to document yet, and especially Form should have more examples. I hadn't thought about an example using React Context, though. So thank you for the feedback. Maybe we can include it in the [Component stores](https://ariakit.org/guide/component-stores) guide since all modules could benefit from this.

However, for this particular case using React Context, the approach with the form store and the old form state remains pretty much the same.

**Comment by Saeris** [comment]
> I'm still thinking of a workaround for this, but the best thing I can think of is not to combine browser validation with custom validation. That is, remove the required attribute (you can still set aria-required for announcements, though). Does that fix the issue?

Still feels unintuitive to me. Like the expectation here is that you can use the native validation options like `required`, but use Ariakit to customize the messages thrown. Hence why I'm thinking something like an error map would help bridge the gap. For reference, I'm trying to throw together an example using Zod for form validation for my company, and it has a similar concept for its own internal error types.

I can see your point about a workaround, I just don't like the either/or scenario. Like, I think perhaps an api like you mentioned with `setCustomValidity()` would be nice, whereby `useValidate()` could pass it's callback extra metadata about the connected form fields, such as a method like: 

```ts
form.useValidate(() => {
    form.getFieldValidity(form.names.fieldName, (element) => {
        if (element.validity.typeMismatch) {
            form.setError(form.names.fieldName, "Wrong data type!"));
        }
    });
});
``` 

Does this make sense? And then `setError()` calls `setCustomValidity()` under the hood.

A simplified, component prop API might be like:

```tsx
<MyField
    required
    errorMap={{
        valueMissing: `This field is required!`
    }}
/>
```

With that you can just override the validation API defaults with minimal boilerplate. The values for each key of the map could either be a string or a callback in perhaps the signature of `(event: ValidationEvent) => string` (guessing on what type event would be).

**Comment by Saeris** [comment]
The `errorMap` prop would help with the issue of `useValidate()` being called insde the component itself, which occurs after the parent form runs it's call of that hook. That issue with calling `useValidate()` at the parent level would still exist though, as subsequent calls are what are overriding the error messages currently.

**Comment by Saeris** [comment]
Further going down that route, could have one of the properties of `errorMap` be `customError`. Using the callback signature I mentioned above, then that field can use the field's value to do custom validation. The downside is now custom errors would be set per-component, rather than whole form, which is where parsing form values against like a Zod schema is convenient.

**Comment by davegomez** [comment]
While reading this thread I was thinking if these component would be compatible with [React Router's Form](https://reactrouter.com/en/6.10.0/components/form) component?

**Comment by Saeris** [comment]
> While reading this thread I was thinking if these component would be compatible with [React Router's Form](https://reactrouter.com/en/6.10.0/components/form) component?

My guess would be no, as to my understanding it uses the native form submission methods to kick off a request to the server to submit the form data.

But,, you can try and wire it up with the [`useForm()` hook](https://github.com/ariakit/ariakit/blob/3169a06a31f898d11d47089b76a0042a06295b04/packages/ariakit-react-core/src/form/form.tsx#L41) in some manner.

**Comment by diegohaz** [comment]
> Still feels unintuitive to me. Like the expectation here is that you can use the native validation options like `required`, but use Ariakit to customize the messages thrown. Hence why I'm thinking something like an error map would help bridge the gap. For reference, I'm trying to throw together an example using Zod for form validation for my company, and it has a similar concept for its own internal error types.

I agree that's not the ideal solution. But I just want to confirm that the proposed workaround (using either custom validation or built-in validation) gets rid of the bug you reported so we can mark this issue as `has workaround` and proceed to work on a proper solution (see https://github.com/ariakit/ariakit/issues/1564#issuecomment-1170091992).

**Comment by diegohaz** [comment]
> I would expect that errors for form inputs would be applied in this order:
> 
> 1. The default browser error message is gathered from the Constraint Validation API
> 2. Then, any user-defined custom errors that are defined at the parent Form level are applied
> 3. Finally, any user-defined custom errors that are defined at the component level are applied

I agree that the built-in validation should run first (1), but the field-level custom validation (3) should run before the form-level custom validation (2):

1. Built-in validation
2. Field-level validation
3. Form-level validation

The main reason is that that's the order in which React effects run, and we don't have a good reason to write a custom logic here (that would even require some hacks, I suppose).

Another reason is that that's the order that goes from the most abstract component, where you'll want to make things more generic and extensible, to the most concrete component, where you have more information and may want to override some defaults.

As an example, consider a generic `RequiredInput` component that adds a general error message when the field is empty:

```jsx
function RequiredInput({ store, ...props }) {
  store.useValidate(() => {
    // We may use store.getError(props.name) here to get the built-in validation message
    if (!store.getValue(props.name)) {
      store.setError(props.name, "Please fill in this field.");
    }
  });
  return <Ariakit.FormInput required {...props} />
}
```

You could override this logic in a more concrete form component:

```jsx
function Form() {
  const store = Ariakit.useFormStore({ defaultValues: { name: "" } });
  store.useValidate(() => {
    // We may also retrieve the field-level error message with store.getError(store.names.name)
    if (!store.getValue(store.names.name)) {
      store.setError(store.names.name, "Name is required.");
    }
  });
  return (
    <Ariakit.Form store={store}>
      <RequiredInput store={store} name={store.names.name} />
    </Ariakit.Form>
  );
}
```

What do you think?
