### ISSUE TITLE
Menu doesn't wait for 'hide' animation when combined with Combobox

### ISSUE THREAD

**Issue by danphilibin** [ariakit/ariakit#2296]
### Current behavior

I wanted to add an animation to this "Menu with Combobox" example: https://ariakit.org/examples/menu-combobox

The 'enter' animation runs fine, and if you select an item in the menu the menu disappears with an animation. But if you click the toggle button, click outside the menu, or press the escape key, the menu disappears immediately without an animation.

It seems to have something to do with combining menu and combobox, since removing the `combobox` prop from `useMenuStore` alleviates the issue. (In my experience a full page reload is necessary; sometimes the issue persists if only relying on hot reloading.)

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/practical-wildflower-s9kwss?file=/index.js
2. Click the button to open the menu
3. Click the button again (or click outside the menu or press the escape key). The menu disappears without an animation.
4. Open the menu and select an item. The menu disappears with an animation.

### Expected behavior

I expect the menu to animate out when hiding the menu without making a selection with the combobox.

### Workaround

https://github.com/ariakit/ariakit/issues/2296#issuecomment-1518476544

### Possible solutions

We may need to change this logic so `animating` is always `true` even when `state.open === prev.open`:

https://github.com/ariakit/ariakit/blob/19333a46c73c5683b61717a50a2c01839b45a261/packages/ariakit-core/src/disclosure/disclosure-store.ts#L50-L51

**Comment by diegohaz** [comment]
Thanks for reporting! I think there's a conflict, and the combobox store is resetting the `animating` state of both the combobox and menu stores to `false` right after menu sets it to true.

You can work around that by making sure the `animating` state is always set to `true` when the `open` state changes:

```js
const open = menu.useState("open");

useEffect(() => {
  menu.setState("animating", true);
}, [menu, open]);
```

**Comment by danphilibin** [comment]
That'll do, thanks!

**Comment by Jackardios** [comment]
I have the same problem when binding `select` + `combobox`
