### ISSUE TITLE
Clicking on the nested dialog backdrop closes all dialogs

### ISSUE THREAD

**Issue by Jackardios** [ariakit/ariakit#2298]
### Current behavior

I have nested dialogs. When I click on the backdrop in a nested dialog, all dialogs are closed, although I would like only the current one to be closed.

### Steps to reproduce the bug

1. Open sandbox: https://stackblitz.com/edit/angular-p9nhel
2. Click on "Show modal"
3. In dialog click on "Show nested modal"
4. In nested dialog click on backdrop
5. All dialogs have been closed even though only the current one is expected to close

### Expected behavior

When I click on the backdrop of a nested dialog, only the current dialog is expected to close

### Workaround

https://github.com/ariakit/ariakit/issues/2298#issuecomment-1518713114

**Comment by diegohaz** [comment]
Thanks for reporting! It seems that the parent dialog is capturing the `mouseup`/`click` event right after the nested dialog has been closed by the `mousedown` event.

You can work around that by ignoring the `mousedown` event on the *nested* dialog:

```jsx
<Dialog hideOnInteractOutside={(event) => event.type !== "mousedown"} />
```
