### ISSUE TITLE
Animated nested dialog not opening

### ISSUE THREAD

**Issue by Jackardios** [ariakit/ariakit#2309]
### Current behavior

I have two animated dialogs. When I try to open a nested dialog it doesn't open but instead the current dialog closes.
I use @ariakit/react@0.1.4

### Steps to reproduce the bug

1. Open sandbox: https://stackblitz.com/edit/angular-p9nhel-bd7myu
2. Click on the "show modal" button
3. In the dialog, click on the "show nested modal" button.
4. Instead of opening a nested dialog, the current one was closed

### Expected behavior

Animated nested dialog should open

### Workaround

This seems to be due to the fact that I am using the `mounted` state value. If the dialog is always mounted, no bug occurs: https://stackblitz.com/edit/angular-p9nhel-8dtrae

**Comment by diegohaz** [comment]
Thanks for reporting.

It does seem to be related to the `mounted` state. I can reproduce it even without `animated`.

**Comment by Jackardios** [comment]
@diegohaz Maybe this is related too: using `open` state to mount/unmount the dialog doesn't work either https://stackblitz.com/edit/angular-p9nhel-lfu41p

**Comment by diegohaz** [comment]
> @diegohaz Maybe this is related too: using `open` state to mount/unmount the dialog doesn't work either https://stackblitz.com/edit/angular-p9nhel-lfu41p

Yeah, `open` and `mounted` are the same when `animated` is `false`.
