### ISSUE TITLE
No such export MenuPopover: MenuItem must be wrapped in a MenuList, MenuPopover or MenuBar component

### ISSUE THREAD

**Issue by httpete** [ariakit/ariakit#2317]
### Current behavior

In my UT things are failing now because of the strict validation.

   MenuItem must be wrapped in a MenuList, MenuPopover or MenuBar component
   
   It would be nice to turn this off, but I can't even find the MenuPopover export so I can at least keep passing.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/m4n32vjkoj
2. Remove any line
3. See console logs

### Expected behavior

.

**Comment by diegohaz** [comment]
`MenuPopover` should be `Menu`. Other than that, the error is valid.

**Comment by httpete** [comment]
Works perfectly with Menu. So it's just the error message that is misleading. Thank you!
