### ISSUE TITLE
Moving the mouse away from the menu item inside a dialog before depressing closes the dialog

### ISSUE THREAD

**Issue by Dremora** [ariakit/ariakit#2330]
### Current behavior

Moving the mouse away from a button/menu item before depressing it is a valid way to cancel user action. However, if a menu is rendered with `portal` property inside a dialog, this behaviour also closes the dialog in addition to the menu.

This was working fine in an earlier version (pre-component stores).

Version: 0.1.6

### Steps to reproduce the bug

1. Open sandbox: https://stackblitz.com/edit/angular-evxmok
2. Open the menu
3. Press mouse down on any item
4. Move the mouse and position it inside the modal, but outside the menu

The dialog gets closed.

### Expected behavior

Menu closes, dialog is still open

### Workaround

https://github.com/ariakit/ariakit/issues/2330#issuecomment-1526883404

**Comment by diegohaz** [comment]
Thanks for reporting @Dremora!

It looks like the click event is being captured by the parent dialog portal element. I'm still not sure why, but in the meanwhile you can fix it with the following code:

```jsx
const portalRef = useRef(null);

<Ariakit.Dialog
  // TODO: Remove when https://github.com/ariakit/ariakit/issues/2330 gets fixed
  portalRef={portalRef}
  hideOnInteractOutisde={(event) => event.target !== portalRef.current}
>
```
