### ISSUE TITLE
scrolling bug when using virtual list with select-with-combobox

### ISSUE THREAD

**Issue by Jackardios** [ariakit/ariakit#2398]
### Current behavior

When using a virtual list with a select-with-combobox, the scroll stops working and starts jumping. I tried the [`react-cool-virtual`](https://github.com/wellyshen/react-cool-virtual/) and [`@tanstack/react-virtual`](https://github.com/TanStack/virtual/) packages and they both have this problem

https://github.com/ariakit/ariakit/assets/24757335/7ca1019b-5741-4863-ad8e-7f11195a7ab2

### Steps to reproduce the bug

1. Open stackblitz: https://stackblitz.com/edit/1jidmc?file=select-combobox/index.tsx
2. Click on select button
3. Scrolling works well
4. Type something in the combobox input (like "he")
5. The list starts to lag when you try to scroll

### Expected behavior

Scroll should work fine

### Workaround

https://github.com/ariakit/ariakit/issues/2398#issuecomment-1544524008

**Comment by diegohaz** [comment]
It's related to the `autoSelect` prop. It will auto-select the first item whenever the rendered items change (which happens on a virtualized list when you scroll). This is so we can still catch items that are rendered asynchronously (for example, if they come from a network call or use React Suspense).

https://github.com/ariakit/ariakit/blob/6137f1bd7d7516e34b72fcb85255803768f72a02/packages/ariakit-react-core/src/combobox/combobox.ts#L205-L214

I'd suggest removing the `autoSelect` prop and implementing it yourself if you need it. You can just listen to the value changes if you don't need to consider async items.

Also, if those libraries don't allow you to always render the first and last items, I'd suggest disabling `focusLoop` on the combobox store:

```jsx
useComboboxStore({ focusLoop: false });
```

**Comment by Jackardios** [comment]
@diegohaz Without `autoSelect` everything works fine, thanks a lot!
