### ISSUE TITLE
Ariakit can't be imported when using Create React App and Jest

### ISSUE THREAD

**Issue by Eldor901** [ariakit/ariakit#2400]
### Current behavior

<img width="900" alt="image" src="https://github.com/ariakit/ariakit/assets/31973508/29d86de0-a0f3-4c4b-8fe7-13b54b11cac4">

### Steps to reproduce the bug
https://github.com/Eldor901/Ariakit-jest

### Expected behavior

Jest tests should not fail

### Workaround

Eject and update the [`moduleFileExtensions`](https://jestjs.io/docs/configuration#modulefileextensions-arraystring) option to include `cjs`.

### Possible solutions

We can potentially fix this on our build script by including the `.cjs` extension on the package.json files inside the proxy folders:

https://github.com/ariakit/ariakit/blob/8e4d7e69a609a499345ffb58a22a45021f995c37/scripts/build/utils.js#L263-L264

The same way we do here for the main package.json:

https://github.com/ariakit/ariakit/blob/8e4d7e69a609a499345ffb58a22a45021f995c37/scripts/build/utils.js#L67-L68

**Comment by diegohaz** [comment]
Could you please provide a link with the reproduction code (repository, CodeSandbox, StackBlitz)?

Anyway, I don't recommend using JSDOM (if you're using it with Jest) to test components that use Ariakit or any other accessible component library. You will need a real browser to test most interactions.

**Comment by Eldor901** [comment]
@diegohaz  https://github.com/Eldor901/Ariakit-jest.

**Comment by Eldor901** [comment]
> Could you please provide a link with the reproduction code (repository, CodeSandbox, StackBlitz)?
> 
> Anyway, I don't recommend using JSDOM (if you're using it with Jest) to test components that use Ariakit or any other accessible component library. You will need a real browser to test most interactions.

@diegohaz https://github.com/Eldor901/Ariakit-jest.

**Comment by Eldor901** [comment]
> 

Is there a specific reason why you don't recommend JSDom and Jest for testing? I think Jest (with JSDom) is one of the most popular ways to write unit tests for JavaScript applications.

**Comment by diegohaz** [comment]
Thanks for the reproduction.

Looks like it's an issue with Create React App that ships with a custom [`moduleFileExtensions`](https://jestjs.io/docs/configuration#modulefileextensions-arraystring) option that doesn't include `cjs`. There's an open PR on the CRA repo that would fix this: https://github.com/facebook/create-react-app/pull/12605

The last CRA release was over a year ago, and it's super outdated. I don't recommend it for new projects. If you want to keep using it, I suggest ejecting (which would allow you to update the Jest config). Or just use [Vite](https://vitejs.dev/).

**Comment by diegohaz** [comment]
> Is there a specific reason why you don't recommend JSDom and Jest for testing? I think Jest (with JSDom) is one of the most popular ways to write unit tests for JavaScript applications.

You can use JSDOM, but you'll likely see a lot of `act` warnings from React. That's because Ariakit performs some actions asynchronously. JSDOM doesn't flush them automatically as the browser does, so you'll have to [do extra work](https://twitter.com/diegohaz/status/1560525455383461888) before and after triggering events.

We do use JSDOM to test Ariakit components internally, but we have an internal [`@ariakit/test`](https://github.com/ariakit/ariakit/tree/main/packages/ariakit-test) package that makes JSDOM behave more like a real browser.

I recommend using a more robust testing framework like [Playwright](https://playwright.dev/) to test your components and pages.
