### ISSUE TITLE
Select: Focus not moving to SelectPopover when there is a hidden SelectItem

### ISSUE THREAD

**Issue by crisshaker** [ariakit/ariakit#2491]
### Current behavior

When you click to open `<Ariakit.Select />` that has `<Ariakit.SelectItem hidden value="" />`, and try navigating with up and down arrow keys, focus is still in the select component and doesn't move to the SelectPopover.

**Important:** The behavior happens when there's a hidden SelectItem.

I've attached a codesandbox repro.

<img width="774" alt="image" src="https://github.com/ariakit/ariakit/assets/36159205/d86cc960-90bc-462a-83ec-71ef5dc37bb0">

### Why am I using `<Ariakit.SelectItem hidden value="" />`?
Without the hidden SelectItem, when I submit the form with no value for the select field, the value of the select field in the FormData is the value of the first SelectItem instead of an empty string(""). So then the `required` prop on the Select component is useless since it's not enforced. A really weird behavior.

Using the hidden SelectItem guarantees that the value is an empty string("") when submitted with no value and also enforces the `required` prop.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/inspiring-joana-i5iugf?file=/src/App.tsx
2. Click to open select
3. Trying navigating using arrow up and down keys

### Expected behavior

Focus should move to SelectPopover and SelectItems.

### Workaround

https://github.com/ariakit/ariakit/issues/2491#issuecomment-1571144023

### Possible solutions

https://github.com/ariakit/ariakit/issues/2491#issuecomment-1571144023

**Comment by diegohaz** [comment]
Thanks for reporting @crisshaker!

This is similar to #1989, but I guess the workaround proposed there doesn't work anymore?

Internally, the `Select` component renders a hidden `<select>`. I think the solution would be rendering an `<option>` with the current value if there's no `SelectItem` for that value (so you don't need to render a hidden select item).

In the meantime, you can render the hidden `<select>` yourself: https://codesandbox.io/s/ariakit-select-workaround-for-empty-default-value-4vkuzr?file=/src/App.tsx

**Comment by idfunctor** [comment]
@diegohaz thanks a lot for the workaround, really helpful
is this being worked on? If not, it looks like a good first issue to take up? I'd be happy to work on it

**Comment by diegohaz** [comment]
@idfunctor Sure, feel free to work on it. Here's the [contributing guide](https://github.com/ariakit/ariakit/blob/main/contributing.md).
