### ISSUE TITLE
`inert` attribute is not removed after nested dialog is closed

### ISSUE THREAD

**Issue by Jackardios** [ariakit/ariakit#2501]
### Current behavior

I am using dynamic rendering dialog depending on `mounted` state. If there are more than 2 nested dialogs, then when they are closed, the `inert` attribute is no longer removed and therefore the page elements remain inactive.

https://github.com/ariakit/ariakit/assets/24757335/9ae6395f-06a4-4836-93a6-217ce6090c8f

### Steps to reproduce the bug

1. Open sandbox: https://stackblitz.com/edit/ndpy3v?file=dialog-nested
2. Click on the "Open dialog"
3. Click on the "Open first nested dialog"
4. Click on the "Open second nested dialog"
5. Close all dialogs
6. Now try clicking "Open dialog" again on and you won't succeed

### Expected behavior

The `inert` attribute must be removed after the subdialog is closed.

### Workaround

Do not dynamically render the `dialog` based on the `mounted`/`open` state or don't nest dialogs in the React tree (make them siblings).

**Comment by Dremora** [comment]
See also #2503 - my conditions are slightly different (only 2 levels of nesting, but some other conditions need to be met). Likely the same cause.

**Comment by Jackardios** [comment]
@Dremora Yes, this is most likely due to the use of the `mounted` state

**Comment by diegohaz** [comment]
This should be fixed in v0.2.7
