### ISSUE TITLE
Select/Dropdown/Autosuggest

### ISSUE THREAD

**Issue by diegohaz** [ariakit/ariakit#256]
Just opening the issue to put together some links/ideas/suggestions about this/these component(s).

- https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/combobox/aria1.1pattern/listbox-combo.html
- https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html
- https://uxmastery.com/anatomy-of-an-accessible-auto-suggest/
- https://pattern-library.dequelabs.com/components/selects
- http://haltersweb.github.io/Accessibility/autocomplete.html

Initial thought on API:

```jsx
<Dropdown.Container>
  {dropdown => (
    <Block>
      <Dropdown.Input {...dropdown} />
      <Dropdown.ArrowButton {...dropdown} />
      {/* Maybe using Popover and Menu */}
      <Dropdown {...dropdown}>
        <Dropdown.Item>Item 1</Dropdown.Item>
        <Dropdown.Item>Item 2</Dropdown.Item>
      </Dropdown>
    </Block>
  )}
</Dropdown.Container>
```

EDIT: Update with v1 API

```jsx
const listbox = useListboxState();
<Listbox {...listbox}>
  <ListboxItem {...listbox}>item 1</ListboxItem>
  <ListboxItem {...listbox}>item 2</ListboxItem>
  <ListboxItem {...listbox}>item 3</ListboxItem>
</Listbox>
```

```jsx
const listbox = useListboxPopoverState();
<ListboxButton {...listbox} />
<ListboxPopover {...listbox}>
  <ListboxItem {...listbox}>item 1</ListboxItem>
  <ListboxItem {...listbox}>item 2</ListboxItem>
  <ListboxItem {...listbox}>item 3</ListboxItem>
</ListboxPopover>
```

```jsx
const combobox = useComboboxListboxState();
<Combobox {...combobox} />
<ComboboxListbox {...combobox}>
  <ComboboxListboxItem {...combobox}>item 1</ComboboxListboxItem>
  <ComboboxListboxItem {...combobox}>item 2</ComboboxListboxItem>
  <ComboboxListboxItem {...combobox}>item 3</ComboboxListboxItem>
</ComboboxListbox>
```

```jsx
const combobox = useComboboxListboxPopoverState();
<Combobox {...combobox} />
<ComboboxListboxPopover {...combobox}>
  <ComboboxListboxItem {...combobox}>item 1</ComboboxListboxItem>
  <ComboboxListboxItem {...combobox}>item 2</ComboboxListboxItem>
  <ComboboxListboxItem {...combobox}>item 3</ComboboxListboxItem>
</ComboboxListboxPopover>
```

**Comment by lluia** [comment]
I raise my hand for this one if it's still relevant 🙋🏻‍♂️

**Comment by diegohaz** [comment]
@lluia It is. But I think the API should be discussed more. I've been drafting some ideas for [Dropdown Select](https://gist.github.com/diegohaz/f0b3b198745e381c37c60f317212d546#file-dropdown-jsx), [Dropdown Input (combobox)](https://gist.github.com/diegohaz/f0b3b198745e381c37c60f317212d546#file-dropdowneditable-jsx) and [Dropdown Multi Input](https://gist.github.com/diegohaz/f0b3b198745e381c37c60f317212d546#file-dropdownmulti-jsx) using React hooks, but I still don't know how it should look like with components.

**Comment by mattfwood** [comment]
@lluia have you had any luck with this? I’d definitely be up for helping out, I enjoy Reakit a lot but frequently finding myself wanting a more robust select drop down that’s also accessible.

I think @diegohaz’s idea with hooks looks solid. But if we’re looking for a model for a dropdown using components, I really like Ryan Florence’s approach with his MenuButton in reach-ui:

https://github.com/reach/reach-ui/tree/master/packages/menu-button

A similar approach would also continue keeping Reakit highly accessible.

**Comment by lluia** [comment]
@mattfwood go ahead, I finally didn't find the moment to address this during Christmas 👍🏻 

Regarding the API, @diegohaz @mattfwood, I think to expose both Hooks and a Component make sense to me:

- Component API reads more clean to me
- Hooks are cool to compose or built something on top of them

We could write most of it as a hook/s and for the component just expose a thin wrapper?
```js
export default function Dropdown(props) {
  return <div {...useDropdown} {...props} />
}
```

**Comment by phil-lgr** [comment]
What about taking inspiration from https://reacttraining.com/reach-ui/combobox

**Comment by diegohaz** [comment]
Reference implementation: #592

**Comment by Guria** [comment]
Does it makes sense to combine Downshift with Reakit promitives for this?

**Comment by diegohaz** [comment]
I don't think so. It overlaps a lot with [Composite](https://reakit.io/docs/composite/). It's probably better to create something out of `Composite` instead. That's probably how we're gonna make it. There are some examples here: https://codesandbox.io/s/composite-gcqs2

**Comment by Grsmto** [comment]
Hey guys,
I've been playing with the `Composite` examples you just sent Diego and I tried to rewrite the implementation from #592 by Greg using it: [https://codesandbox.io/s/composite-k68fs?file=/index.js)](https://codesandbox.io/s/composite-k68fs?file=/index.js)

It's just a small basic example but a Select component is one of the top most complex UI components and can do millions of things...(see react-select...). So I guess a scope of supported features needs to be defined for Reakit's implementation.

**Comment by diegohaz** [comment]
Thank you for the example @Grsmto! That's really helpful!

Regarding the name, my only concern about naming it `Select` is that there's an abstract ARIA role with the same name (https://www.w3.org/TR/wai-aria-1.1/#select), which is the base for widgets like `combobox`, `listbox` and `menu`.

At first, I thought about having a `Select` component that would take care of item selection (including multiple selection) on composite components and would be used by other components like `Combobox`, `Listbox`, `Menu`, `Tree` etc. But I would rather try to avoid this name even for this kind of component. For now, I'm thinking about `Selectable` for this component.

As for the `<select>` alternative, I've seen both `Combobox` and `Listbox` being used. Although a `listbox` is primarily represented as a `<select>` with the `size` attribute set to `2` or higher.

**Comment by vvo** [comment]
> I don't think so. It overlaps a lot with [Composite](https://reakit.io/docs/composite/). It's probably better to create something out of `Composite` instead. That's probably how we're gonna make it. There are some examples here: [codesandbox.io/s/composite-gcqs2](https://codesandbox.io/s/composite-gcqs2)

Hey there @diegohaz, I am trying to use the "Combobox (aria-activedescendant)" example from this codesandbox. Only difference being that I'd like the listbox to show only when input has focus, how would you do that with Reakit? Thanks!

**Comment by diegohaz** [comment]
@vvo You would have to play with the input's `onFocus` and `onBlur` props.

There's a Combobox component in the works on #688 (example: https://deploy-preview-688--reakit.netlify.app/storybook/iframe.html?id=examples--accessible-combobox&viewMode=story)

**Comment by vvo** [comment]
Ok thanks, the Combobox is coming up nicely, good luck for the release of it.

For now I am trying to combine your codesandbox example with a popover but not so easy!

**Comment by frassinier** [comment]
Not sure that a Combobox will fit for a Select, maybe for replacing a <datalist />.
@diegohaz What do you think about implementing a Listbox, in addition?

**Comment by vvo** [comment]
I am using the Combobox in production: works well now :)

**Comment by strass** [comment]
Hi @diegohaz, myself and a coworker are using combobox as a select/multiselect component with some success so far. However, we're having to do a lot of logic outside of reakit's internals to handle our use cases.

How would you imagine multiselect working? I assume the major issue making it difficult to integrate into Combobox as is would be the type definitions – do you think a separate MultiCombobox component would be the method forward or do you think it could be integrated into Combobox as is? 

Besides handling multiselect state we've found a few additional necessary changes:
- not closing the menu upon selection in case the user wants to select more items
  - closing menu when focus leaves the component (clicking out works, tabbing out [blur] doesn't)
- usage of space to select options (which I think involves some changes to virtual focus)

We'd like to take a crack at it, what do you think?

**Comment by diegohaz** [comment]
Hey @strass! I'm not sure if it's the same design as yours, but I've created this example a few months ago: https://codesandbox.io/s/reakit-combobox-with-tags-smfgu

On the API, I imagine we could have a separate `Tag` component that could be combined with `Combobox`, like this: https://twitter.com/diegohaz/status/1337358924236939268

**Comment by strass** [comment]
> Hey @strass! I'm not sure if it's the same design as yours, but I've created this example a few months ago: https://codesandbox.io/s/reakit-combobox-with-tags-smfgu
> 
> On the API, I imagine we could have a separate `Tag` component that could be combined with `Combobox`, like this: https://twitter.com/diegohaz/status/1337358924236939268

lol this must be the one example we didn't find. We'll review and compare :)

**Comment by sjaq** [comment]
I've been playing with the component after struggling to implement a custom component using `useCombobox` from downshift and must say the API looks great so far. 

The main thing I haven't found an easy solution to is to change the reference element that is used when placing the popover. Ideally this would be configurable as it is quite common to have the popover connected to another element as the input (for instance to connect it to the outer `Composite` in the tag example shared above).

**Comment by ZachHaber** [comment]
Here's how I've done it. It's very much so labeled as unstable, and I had to do this on each render not in an effect.

It's kinda weird, but it worked.

```tsx
  if (testRef.current) {
    // Need to set the ref up! We want it to cover the correct element
    // It's a very unfortunate issue - Maybe something to ask for in the reakit?
    // Or we need to just not use the TextInput component here and make a basic compromise one?
    (combobox.unstable_referenceRef as MutableRefObject<HTMLElement>).current =
      testRef.current;
  }
  ```
