### ISSUE TITLE
Select popover direction doesn't update when re-opened

### ISSUE THREAD

**Issue by MarosPistej** [ariakit/ariakit#2567]
### Current behavior

When select popover is opened 1st time, it opens correctly in direction of available space, but when closed and page scrolled so select popover should open in opposite direction it opens to direction of 1st open and scroll page.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/elastic-boyd-k5789f
2. Scroll page so select open in some direction and close it
3. Scroll page so select should open in opposite direction

https://github.com/ariakit/ariakit/assets/43110161/af877f80-562e-48c9-9f3e-706c68dfb84c

### Expected behavior

When select popover is re-opened it correctly position itself in direction of available space

### Workaround

https://github.com/ariakit/ariakit/issues/2567#issuecomment-1607650419

### Possible solutions

Note: I thought that this issue have same base as https://github.com/ariakit/ariakit/issues/1872 but was told in comment that it probably is different bug.

**Comment by diegohaz** [comment]
Thanks for reporting!

Looks like we'll have to delay the initial focus a bit so the popover has enough frames to position itself.

In the meantime, you can do something like this:

```jsx
const mounted = select.useState("mounted")
const [autoFocusOnShow, setAutoFocusOnShow] = useState(false)

// TODO: Remove when https://github.com/ariakit/ariakit/issues/2567 gets fixed
useEffect(() => {
  const raf = requestAnimationFrame(() => setAutoFocusOnShow(mounted))
  return () => cancelAnimationFrame(raf)
}, [mounted])

<SelectPopover autoFocusOnShow={autoFocusOnShow} />
```
