### ISSUE TITLE
Add animation support to Tooltip

### ISSUE THREAD

**Issue by DaniGuardiola** [ariakit/ariakit#2657]
### Motivation

Disclosure and Disclosure-based components already offer a convenient API for handling animations: `[data-enter]` and `[data-leave]` (as documented [here](https://ariakit.org/guide/styling#data-enter)).

However, the Tooltip component (which is typically also styled with animations) doesn't support this. This has the following consequences:

 - Forces the user to introduce an external library like Framer Motion, adding to the bundle size and complexity.
 - Alternatively, forces the user to build a custom implementation of the same.
 - Leads to different and potentially inconsistent methods of animation styling across components (e.g. Tooltip and Menu would need different implementations).
 - Causes incompatibility with tools like the [tailwindcss-animate](https://github.com/jamiebuilds/tailwindcss-animate) plugin.

My proposal is to implement the same animation API in Tooltip (and any other relevant components) so that it can be as simple as `className="data-[enter]:animate-in data-[leave]:animate-out (etc)"` (tailwindcss-animate example).

### Usage example

```tsx
<Tooltip className="data-[enter]:animate-in data-[leave]:animate-out (etc)">My tooltip</Tooltip>
```

### Requirements

The Tooltip component (and others where relevant) expose the same animation API as Disclosure and Disclosure-based components.

### Workaround

Either:

- Custom implementation that essentially replicates the implementation of animation in Disclosure components.
- Third party tool and diverging method of animation.

**Comment by diegohaz** [comment]
Tooltip should support that already. Otherwise, it's probably a bug. Could you reproduce that in a CodeSandbox/StackBlitz?

**Comment by DaniGuardiola** [comment]
:facepalm:
