### ISSUE TITLE
Controlled Combobox caret jumping

### ISSUE THREAD

**Issue by tienpv222** [ariakit/ariakit#2670]
### Current behavior

With controlled `Combobox`, the caret will jump to the end regardless of its current position. This doesn't happen with uncontrolled `Combobox`.

### Steps to reproduce the bug

1. Open: https://stackblitz.com/edit/react-zhq7r7?file=src%2FApp.js
2. Place caret in middle of input text
3. Start typing, caret will jump to the end of string

### Expected behavior

The caret should not jump around.

### Workaround

https://github.com/ariakit/ariakit/issues/2670#issuecomment-1650340873

**Comment by diegohaz** [comment]
Thanks for reporting. As a workaround, you can do the following:

```js
import { flushSync } from "react-dom";

const combobox = useComboboxStore({
  value,
  setValue(value) {
    // Remove when https://github.com/ariakit/ariakit/issues/2670 gets fixed
    flushSync(() => setValue(value));
  },
});
```
