### ISSUE TITLE
Nested dialog doesn't work with scrollable backdrop

### ISSUE THREAD

**Issue by hyanmandian** [ariakit/ariakit#2687]
### Current behavior

When we use nested dialog with a custom backdrop (like a scrollable that uses backdrop as parent instead of sibling) for some reason it closes both dialogs when you click outside or if you interact with any other popover inside of it

### Steps to reproduce the bug

1. Open sandbox: https://stackblitz.com/edit/tm2vor-jk6b49?file=dialog-nested%2Findex.tsx
2. Click on view cart to open first dialog
3. Click on remove to open the second dialog
4. Click outside dialogs or click on "Actions" then click outside the menu list

https://github.com/ariakit/ariakit/assets/5044101/7c6d7edd-2cb5-4403-a2f4-9a7948aa69b1

### Expected behavior

- If you click outside the dialogs, it should close the latest open dialog, not both.
- If you click outside the menu, it should close the menu but not dialogs, the dialogs should keep open

### Workaround

https://github.com/ariakit/ariakit/issues/2687#issuecomment-1659502735

**Comment by diegohaz** [comment]
You're passing a function to the `backdrop` prop. This is the correct way to render the backdrop element as a parent:

```jsx
<Dialog
  backdrop={false}
  render={(dialogProps) => (
    <div className="backdrop">
      <div {...dialogProps} />
    </div>
  )}
/>
```

Ref: https://ariakit.org/examples/dialog-backdrop-scrollable#rendering-a-custom-backdrop

**Comment by diegohaz** [comment]
I noticed that even rendering the backdrop element correctly, as per my previous comment, the issues you reported still exist.

For now, you can use the [`hideOnInteractOutside`](https://ariakit.org/reference/dialog#hideoninteractoutside) prop as a function and return `false` when interacting with those elements.

**Comment by hyanmandian** [comment]
> You're passing a function to the `backdrop` prop. This is the correct way to render the backdrop element as a parent:
> 
> ```js
> <Dialog
>   backdrop={false}
>   render={(dialogProps) => (
>     <div className="backdrop">
>       <div {...dialogProps} />
>     </div>
>   )}
> />
> ```
> 
> Ref: https://ariakit.org/examples/dialog-backdrop-scrollable#rendering-a-custom-backdrop

You are right, I copied it wrong from my code, but like you said here the issue is still there, I'll try to do what you said [here](https://github.com/ariakit/ariakit/issues/2687#issuecomment-1659502735). Thanks for the quick response!

**Comment by hyanmandian** [comment]
> > You're passing a function to the `backdrop` prop. This is the correct way to render the backdrop element as a parent:
> > ```js
> > <Dialog
> >   backdrop={false}
> >   render={(dialogProps) => (
> >     <div className="backdrop">
> >       <div {...dialogProps} />
> >     </div>
> >   )}
> > />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Ref: https://ariakit.org/examples/dialog-backdrop-scrollable#rendering-a-custom-backdrop
> 
> You are right, I copied it wrong from my code, but like you said here the issue is still there, I tried to do it as you said [here](https://github.com/ariakit/ariakit/issues/2687#issuecomment-1659502735) and it works properly!

```jsx
const backdropRef = useRef<HTMLDivElement>(null);

const onInteractOutside = useEvent((e) => {
  const isNested = [
    ...document.querySelectorAll("[data-scope='backdrop']"),
  ].some((el) => el !== backdropRef.current && el.contains(e.target));

  return !isNested;
});

return (
  <Dialog
    backdrop={false}
    render={(dialogProps) => (
      <div ref={backdropRef} className="backdrop" data-scope="backdrop">
        <div {...dialogProps} />
      </div>
    )}
    hideOnInteractOutside={onInteractOutside}
  />
)
```

Thanks for the quick response!
