### ISSUE TITLE
Automatically close `Disclosure` when interact outside

### ISSUE THREAD

**Issue by mule-stand** [ariakit/ariakit#2696]
### Motivation

How about adding functionality to the `Disclosure` component to automatically close when interacting outside the container? It could be useful to use it as a `Popover` component without popover, for example for some lists (like menus).

### Usage example

`<Ariakit.Disclosure hideOnInteractOutside={true} />`

### Requirements

The component should  hidden when the user clicks or focus on an element outside of the `Disclosure`.

**Comment by diegohaz** [comment]
Is it not a `<Dialog modal={false}>`? If not, could you provide more details about your specific use case? Screenshots would be helpful.

**Comment by mule-stand** [comment]
Hmm, I tried to do the same for Popover but there are some default styles that absolutely position Popover anyway 
With the dialog, I was really able to achieve what I want. But is it really well suited semantically for my case? Here's my case:
![image](https://github.com/ariakit/ariakit/assets/113935919/3442e4f0-0814-4017-9166-a96ab726d288)

**Comment by diegohaz** [comment]
Yes, it's semantically correct for a non-modal dialog. `<Dialog modal={false}>` is `Popover` without the position styles. You should use [`DialogDisclosure`](https://ariakit.org/reference/dialog-disclosure) as well.

**Comment by mule-stand** [comment]
> Yes, it's semantically correct for a non-modal dialog. `<Dialog modal={false}>` is `Popover` without the position styles. You should use [`DialogDisclosure`](https://ariakit.org/reference/dialog-disclosure) as well.

Thanks!)
