### ISSUE TITLE
items/setItems don't behave correctly with useSelectStore

### ISSUE THREAD

**Issue by Dremora** [ariakit/ariakit#2697]
### Current behavior

When passing `items` and `setItems` (as produced by `useState`) to `useSelectStore`, `items` doesn't get populated.

When `SelectPopover` gets rendered with `portal`, only some items make it through.

### Steps to reproduce the bug

1. Open sandbox: https://stackblitz.com/edit/dxcty1?file=select%2Findex.tsx&theme=dark
2. Observe the number of items printed below the select component - it says "0"
3. Uncomment line with `portal` and refresh the page
4. Observe the number of items printed below the select component - it says "2" and lists "Orange" twice

### Expected behavior

In both cases, we expect 4 items to be present, all listed in order they appear in the select.

### Workaround

https://github.com/ariakit/ariakit/issues/2697#issuecomment-1674173029

**Comment by diegohaz** [comment]
Thanks @Dremora!

Could you share more details on your use case so we can create a real-world example to test that?

**Comment by Dremora** [comment]
I have discovered this issue in my attempt to figure out whether I can find a solution to #2698, I didn't actually have any requirements for this yet.

But I can think of the following scenario (note that I haven't tried this): if the dropdown is rendered with framer-motion, and thus is not present in DOM when it's closed, Ariakit won't have any knowledge of the contents of such dropdown. This means that typing letters on a closed focused Select won't be changing its value. There are two potential workarounds here:
- use `items`/`setItems`
- use `typeahead={false}` and implement custom logic

**Comment by diegohaz** [comment]
Yes, that makes sense! We will likely have more use cases for that with the [virtualization components](https://ariakit.org/examples/select-combobox-virtualized). The example currently uses `defaultItems`, but I can envision a scenario where the `items` are dynamic and need to be managed as a separate state.

**Comment by mule-stand** [comment]
> Yes, that makes sense! We will likely have more use cases for that with the [virtualization components](https://ariakit.org/examples/select-combobox-virtualized). The example currently uses `defaultItems`, but I can envision a scenario where the `items` are dynamic and need to be managed as a separate state.

Why isn't this example in the documentation in the "Examples" section?

**Comment by diegohaz** [comment]
> > Yes, that makes sense! We will likely have more use cases for that with the [virtualization components](https://ariakit.org/examples/select-combobox-virtualized). The example currently uses `defaultItems`, but I can envision a scenario where the `items` are dynamic and need to be managed as a separate state.
> 
> Why isn't this example in the documentation in the "Examples" section?

The `*Renderer` components are still experimental and only exported by the `@ariakit/react-core` package, which is unstable.

**Comment by diegohaz** [comment]
This is the simplest workaround I can think of:

```js
const [items, setItems] = useState([]);
const select = Ariakit.useSelectStore({ setItems });

const selectItems = select.useState("items");

useEffect(() => {
  setItems(selectItems);
}, [selectItems]);
```
