### ISSUE TITLE
Cannot disable `setValueOnMove` on `SelectList`

### ISSUE THREAD

**Issue by tienpv222** [ariakit/ariakit#2731]
### Current behavior

Moving item with keyboard on `SelectList` still updates value, regardless of `setValueOnMove` setting.

### Steps to reproduce the bug

https://stackblitz.com/edit/react-jqrqqh?file=src%2FApp.js

### Expected behavior

When `setValueOnMove=false`, item should still be moved and focused (either `data-focus-visible` through virtual focus or native `:focus-visible` without virtual focus), without value change.

**Comment by diegohaz** [comment]
Hi @tienpv222! Could you share more details about your specific use case where you encountered this bug? Depending on the context, it could have different solutions.

**Comment by tienpv222** [comment]
> Hi @tienpv222! Could you share more details about your specific use case where you encountered this bug? Depending on the context, it could have different solutions.

Hi @diegohaz. I'm using `SelectList` as the layer panel in a drawing app. It's always visible so I use that instead of `SelectPopover`. However I expect the `setValueOnMove` behavior to be similar to `SelectPopover` when set to `false`. The reason is I'd like to let users navigate through long list of items, without changing the selected `value` (which might trigger change in my other components). I hope this makes sense. Thank you.

**Comment by tienpv222** [comment]
Ahh, so if `open: false` then value will be set on move regardless. I used `alwaysVisible` on `SelectList` and thought it was enough. Thank you. It's solved now.
