### ISSUE TITLE
Menu to add other defaultOpen dropdown components, triggers their setOpen event 

### ISSUE THREAD

**Issue by cloud-walker** [ariakit/ariakit#2773]
### Current behavior

This is like the old #2450 issue, but in a different way 🤔 

The regression seems to come from the v0.2.16 onward, and the workaround from #2450 using `autoFocusOnHide` solve it partially as this time I cannot use `element?.focus()` to eventually refocus the Add filter menu button.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/p/sandbox/tos-dash-filtersbar-93dmhl
2. Try to add a filter through the "Add filter" menu
3. notice that it tries to add the filter, but immediately close it

### Expected behavior

I expect to add a select defaultOpen to remain open without human interaction

### Workaround

https://github.com/ariakit/ariakit/issues/2773#issuecomment-1710984357

**Comment by cloud-walker** [comment]
Sorry! I've left uncommented the autoFocusOnHide thing, now the bug should be visible

> Also, can you reproduce it on this example? https://ariakit.org/examples/select-menu-default-open

I've tried, but in the example is working properly, I don't know why yet, but I suspect that in the example you used the setValues and values props of useMenuStore (in my version I don't use them)

**Comment by diegohaz** [comment]
I'm struggling to distinguish between your example and the one on the Ariakit website. Could you possibly modify a fork to mirror your situation, ideally with as few changes as possible?

https://stackblitz.com/run?file=select-menu-default-open%2Fstyle.css,select-menu-default-open%2Ffilter-select.tsx,select-menu-default-open%2Ffilter-menu.tsx,select-menu-default-open%2Fall-filters.ts,select-menu-default-open%2Findex.tsx&theme=dark

**Comment by cloud-walker** [comment]
Hi! @diegohaz, after several attempts, starting from the ariakit website example, the steps to reproduce the "bug" are:

1. move the SelectMenu in the same div of the filters array;
2. the SelectMenu uses SelectItem instead of checkboxes, and the onClick handler in the SelectItem instead of the onValuesChange prop;

Here the fork: https://stackblitz.com/edit/6jtpwr-sxcvpe?file=select-menu-default-open%2Findex.tsx

I suspect that the bug comes from the React render algorithm that behave differently because of points 1 and 2.

I'm curious of your considerations, cheers!

**Comment by cloud-walker** [comment]
I correct myself, the bug seems to pop out based on SelectMenu order:

1. SelectMenu before filter list -> no bug
2. SelectMenu after filter list -> bug

**Comment by diegohaz** [comment]
Thanks! I can reproduce it now.

In the meantime, you can either change the order of the elements or delay the `onAdd` call a bit:

```jsx
onClick={() => {
  requestAnimationFrame(() => {
    onAdd?.(field)
  });
}}
```

**Comment by cloud-walker** [comment]
I'm curious, what was the issue?
