### ISSUE TITLE
FormCheckbox errors when an "integer-like" name is used as a field name

### ISSUE THREAD

**Issue by Exanite** [ariakit/ariakit#2799]
### Current behavior

Using an "integer-like" name (eg: `"123"`) as a field name causes FormCheckbox to raise the following error when clicked:
```
TypeError: values.slice is not a function or its return value is not iterable
```

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/p/sandbox/nice-saha-hmfh88?file=%2Fapp%2Fpage.tsx%3A5%2C25
2. Click on the checkboxes for "123" and "safe".
3. "123" will error, but "safe" will not.

### Expected behavior

Using an "integer-like" name as a field name should not cause FormCheckbox to error.

### Workaround

Don't use integer-like field names or append some letter/other character to the end of the string to make it not parse as an integer.

### Possible solutions

This seems to be because set doesn't directly check whether `values` is an array or an object, and only uses the `key` is "integer-like" to decide whether `values` is an array or not.

Therefore, this should be fixable by checking if `values` is an array or not.

I edited the following code in my project's `node_modules` folder and it appears to have fixed the error:
https://github.com/ariakit/ariakit/blob/e8a2160490b368395a5f4fab9a47347d5bf2fbdc/packages/ariakit-core/src/form/form-store.ts#L80
```diff
- if (isIntegerKey) {
+ if (isIntegerKey && Array.isArray(values)) {
```

---

(Edit: I had this in my original message here so I'm keeping it as reference)

This is the code that is erroring for reference: https://github.com/ariakit/ariakit/blob/e8a2160490b368395a5f4fab9a47347d5bf2fbdc/packages/ariakit-core/src/form/form-store.ts#L65
```ts
function set<T extends Values | unknown[]>(
  values: T,
  path: StringLike | string[],
  value: unknown,
): T {
  const [k, ...rest] = Array.isArray(path) ? path : `${path}`.split(".");
  if (k == null) return values;
  const key = k as keyof T;
  const isIntegerKey = isInteger(key);
  const nextValues = isIntegerKey ? values || [] : values || {};
  const nestedValues = nextValues[key];
  const result =
    rest.length && (Array.isArray(nestedValues) || isObject(nestedValues))
      ? set(nestedValues, rest, value)
      : value;
  if (isIntegerKey) {
    const index = Number(key);
    if (values) {
      return [
        ...values.slice(0, index),
        result,
        ...values.slice(index + 1),
      ] as T;
    }
    const nextValues = [] as unknown as T;
    nextValues[index as keyof T] = result as T[keyof T];
    return nextValues;
  }
  return { ...values, [key]: result };
}
```

isInteger is implemented here: https://github.com/ariakit/ariakit/blob/de19a6e3dcc1f49ff17157f4e848e173b780f922/packages/ariakit-core/src/utils/misc.ts#L107
```ts
export function isInteger(arg: any): boolean {
  if (typeof arg === "number") {
    return Math.floor(arg) === arg;
  }
  return String(Math.floor(Number(arg))) === arg;
}
```

**Comment by Exanite** [comment]
One thing I'm also noticing is that since values is typed as `Values | unknown[]`, Typescript's typing is essentially bypassed and the invalid call to `slice()` is not noticed by Typescript.

Values is defined here as:
https://github.com/ariakit/ariakit/blob/de19a6e3dcc1f49ff17157f4e848e173b780f922/packages/ariakit-core/src/utils/types.ts#L4
```ts
/**
 * Any object.
 */
export type AnyObject = Record<string, any>;
```

It might be worth using `Record<string, unknown>` here instead to force type checking, but I don't know how much this impacts the codebase.

**Comment by diegohaz** [comment]
@Exanite Thanks for the detailed issue. Would you like to submit a PR with your solution?

I think we can use `Record<string, unknown>` instead of `AnyObject` here:

https://github.com/ariakit/ariakit/blob/de19a6e3dcc1f49ff17157f4e848e173b780f922/packages/ariakit-core/src/form/form-store.ts#L29

**Comment by Exanite** [comment]
Sure! I'm reading through the contribution guidelines file right now.

Is there anything I should know for this particular pull request?
