### ISSUE TITLE
Provide an example of a menu bar in docs

### ISSUE THREAD

**Issue by noahbald** [ariakit/ariakit#2874]
### Motivation

The documentation mentions the ability to use the Menu and related components as a menu bar as opposed to just a dropdown. However, all examples given are of dropdown menus and no menu bars are presented.

It would be good to have some examples of menu bars in a frequently used context, such as a header menu or an always-visible side-menu

### Usage example

// not applicable

### Requirements

- An example of a menu-bar in a header
- An example of a menu-bar that is always visible in a sidebar

### Workaround

Make assumptions about the best way to implement a menu bar or always-visible sidebar

**Comment by diegohaz** [comment]
There's already an example: https://ariakit.org/examples/menu-bar

Important read: [Can I use MenuBar for site navigation](https://ariakit.org/examples/menu-bar#can-i-use-menubar-for-site-navigation)

**Comment by noahbald** [comment]
Thanks @diegohaz, sorry I missed this.
I suppose that such a pattern could also be used in a vertical manner for something like a sidebar.
