### ISSUE TITLE
Tooltip doesn't hide correctly with animated option

### ISSUE THREAD

**Issue by mleralec** [ariakit/ariakit#2929]
### Current behavior

When I create a tooltipStore with `animated` option to `true`:
```tsx
const tooltip = Ariakit.useTooltipStore({ animated: true })
```
The tooltip is displayed correctly on hover but remains visible when I move the mouse elsewhere.

### Steps to reproduce the bug

1. Open sandbox: https://stackblitz.com/edit/xjcyvw?file=tooltip%2Findex.tsx
2. Hover the "Content"
3. Move your mouse out of the "Content", the tooltip is still visible 

### Expected behavior

The tooltip must be hidden when we are not flying over the anchor.

### Workaround

Give a `number` instead of `true` to **animated** seems to fix the problem.
```tsx
const tooltip = Ariakit.useTooltipStore({ animated: 300 })
```

**Comment by diegohaz** [comment]
The reproduction you've given isn't animating the tooltip. There's no CSS transition or animation applied to the tooltip, which is why it isn't hiding. If you set `animated` to `true`, the element will hold off until the transition is complete before it hides the tooltip.
