### ISSUE TITLE
Select: introduce a new prop to allow empty selection 

### ISSUE THREAD

**Issue by johnsonthedev** [ariakit/ariakit#3150]
### Motivation

Currently you can set a default value for select boxes. If not set, the first non-disabled item will be used.

I have a scenario where the select box is optional and I don't want to auto select it. 

My idea is to add a property to allow empty values: 

Attribute	                       Type	Description	                                                       Default
allowEmptySelection	boolean	Whether the collection allows empty selection.	false

<img width="666" alt="Screenshot 2023-12-05 at 01 46 52" src="https://github.com/ariakit/ariakit/assets/21923568/a260dd9e-c68c-40c8-a4e0-882baa0a5f98">

### Usage example

```jsx
      <Ariakit.SelectProvider allowEmptySelection={true} />
```

### Requirements

- If allowEmptySelection is set to true the select box should allow empty values
- Introduce a placeholder component that will render when there are no values

### Workaround

https://github.com/ariakit/ariakit/issues/3150#issuecomment-1840743063

**Comment by diegohaz** [comment]
Is this a duplicate of #2516?

Currently, you can pass an empty string (`""`) as the value and directly render the placeholder as the `Select` element's children:

```jsx
<Select>
  {value || "Select an animal"}
</Select>
```

**Comment by johnsonthedev** [comment]
siiii it's similar. i tried with null and undefined but the typecheck failed. thanks for the info with the empty string

**Comment by johnsonthedev** [comment]
this a duplicate of https://github.com/ariakit/ariakit/issues/2516?
