### ISSUE TITLE
TabProvider type issue in v0.3.8

### ISSUE THREAD

**Issue by kellyk** [ariakit/ariakit#3171]
### Current behavior

I tried to update to ariakit version 0.3.8 today, but I'm seeing this error when I try to provide `defaultSelectedId` prop to `<Ariakit.TabProvider />`:

`Type '{ children: Element[]; defaultSelectedId: string; }' is not assignable to type 'IntrinsicAttributes & TabProviderProps'.`

The ariakit [docs](https://ariakit.org/reference/tab-provider#defaultselectedid) show that defaultSelectedId is a valid type

### Steps to reproduce the bug

Use Ariakit to render a TabProvider with defaultSelectedId prop, eg:

`<Ariakit.TabProvider defaultSelectedId="foo">`

### Expected behavior

No errors

### Workaround

Ignore the error with [`// @ts-expect-error`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#-ts-expect-error-comments) until the next release.

**Comment by diegohaz** [comment]
Thanks for reporting, @kellyk. This should be fixed by #3155. The next release should be published by Monday.
