### ISSUE TITLE
Combobox calls `onFocus` on every input change with `autoSelect` property with no items

### ISSUE THREAD

**Issue by Bloomca** [ariakit/ariakit#3203]
### Current behavior

Currently, I observe that if you add `onFocus` handler to the `<Combobox autoSelect` component (the `autoSelect` property is important), and you have no `<ComboboxItem`, e.g. due to filtering, every keystroke will trigger the focus handler.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/p/sandbox/ariakit-combobox-test-kqhjn2
2. Type a matching string first and see that there are no additional `onFocus` calls
3. Type anything which is not matched, and observe that 

### Expected behavior

I expect `onFocus` to be called only when the input gets focus.

### Workaround

There is a partial solution to wrap `autoSelect={Boolean(options.length}`, but you'll still get one more `onFocus` call when you start typing something which gets some matches.

**Comment by diegohaz** [comment]
Thanks for reporting! Did you find this issue while working on a specific use case? Could you describe this use case (screenshots help)? This will help us create an example to ensure it doesn't break again in the future.

**Comment by Bloomca** [comment]
Thanks for the reply!

Our use-case is that when we focus the input, we want to select the content for the user, so new typing would start from scratch. Here is our handler:

```tsx
    const handleFocus = useEvent(function handleFocus(event: React.FocusEvent<HTMLInputElement>) {
        const inputElement = event.currentTarget
        setTimeout(() => inputElement.setSelectionRange(0, 999))
        onFocus()
    })
```

Running `onFocus` multiple times usually is not a problem, so I assume it can easily be masked. So, for example, in this date parsing field, if the user typed an invalid date, then selected all the content, and typed a first character which yields matches, `handleFocus ` would be called and that would select the typed character.

**Comment by diegohaz** [comment]
Does it change anything if you use `inputElement.select()` instead of `setSelectionRange`?

**Comment by Bloomca** [comment]
Thanks for the recommendation, I think we'll refactor to use it instead of `setSelectionRange`!

That being said, it doesn't change anything, because the issue is not limited to the selection itself. In the codesandbox I shared ([ref](https://codesandbox.io/p/sandbox/ariakit-combobox-test-kqhjn2)), you can see that the `onFocus` handler is called every time we type another symbol when there are no options available.

I checked and the `onBlur` handler is not called on every keystroke, so we can probably can make a better workaround by tracking `isFocused` by ourselves and selecting content in the React effect.

But from my understanding the `onFocus` should not be called on every keystroke with `autoSelect={true}` and no options available, am I correct here?
