### ISSUE TITLE
No longer possible to display multiple Tooltips on screen at the same time, when desired

### ISSUE THREAD

**Issue by vivshaw** [ariakit/ariakit#3216]
### Current behavior

We are upgrading from `ariakit@2.0.0-next.43` to `@ariakit/react@0.3.9`. In our codebase, we use Tooltips for two slightly different purposes:

1. An interactive, display-on-mouseover-or-focus piece of info anchored to some element on the page. Normal, standard tooltip! So let's call this type a Tooltip
2. A _static, programmatically-controlled_ piece of info anchored to some element on the page. This is visually identical to a Tooltip, anchors to an element the same as a Tooltip... the only difference is, instead of displaying on mouse-over-or-focus, it is controlled by an `open?: boolean` prop, passed to the `open` prop in `useTooltipStore`. So let's call this type a Controlled Tooltip.

After the upgrade, we discovered that the regular ol' Tooltips works fine, but the Controlled Toolips are broken. Specifically, it is no longer possible to have more than one Controlled Tooltip visible on the page- the last one that renders will be the only one that displays. (And if I mouse over another Tooltip, the Controlled Tooltip will close.) This is excellent, expected behavior for regular Tooltips- but we routinely use Controlled Tooltips in a way that expects two or more to be visible at the same time.

After some digging in the changelog and PRs, I suspect this may be related to #2692, which says: "I also fixed an issue where the tooltip wasn't closing when it was open while another popover was still visible." This _sounds_ pretty similar to what we're seeing

### Steps to reproduce the bug

Codesandbox: https://codesandbox.io/s/nostalgic-darwin-yl98k4?file=/index.js

### Expected behavior

I'd expect a tooltip where I manually control the tooltip state by passing the `open` prop to remain open, even when other tooltips are opened.

If for some reason that is not the desired behavior of `open`, I'd expect an override prop of some kind, like `forceOpen`.

### Workaround

No workaround found so far

### Possible solutions

I'm not sure- I've been poking at #2692 to try to understand how those changes impact automatic closing, but I don't quite follow it!

**Comment by diegohaz** [comment]
Hi @vivshaw!

It looks like what you described as a _controlled tooltip_ is just a [Popover](https://ariakit.org/components/popover)? Or maybe a [Hovercard](https://ariakit.org/components/hovercard)?

Tooltip is built on top of Hovercard with more limitations — as you mentioned, only one tooltip can be open at a time. Hovercard, in turn, is built on top of Popover. Therefore, depending on your specific requirements, you can opt to use a more abstract component.

If you can share screenshots of your specific use case, I can put together a quick example using these components.

**Comment by vivshaw** [comment]
Aha, I believe that Popover may work for our purposes- thank you! Two further questions then:

1. Do you have any recommendation for coverage of Tooltips in visual snapshot testing, such as Chromatic? We used the `open` prop to open them all in our kitchen-sink pages that are used for snapshots, but can no longer do so.
2. Is it possible that, if the `open` prop is no longer intended to work with a Tooltip, that Ariakit might remove it? The current state, where the prop is present but doesn't work like one expects, is a little confusing.

**Comment by diegohaz** [comment]
> 1. Do you have any recommendation for coverage of Tooltips in visual snapshot testing, such as Chromatic? We used the `open` prop to open them all in our kitchen-sink pages that are used for snapshots, but can no longer do so.

You may want to build your tooltips with `Hovercard`, then:

```jsx
const [open, setOpen] = useState(false);

<HovercardProvider open={open} setOpen={setOpen}>
  <HovercardAnchor onFocusVisible={() => setOpen(true)}>
    Anchor
  </HovercardAnchor>
  <Hovercard role={undefined}>
    Tooltip
  </Hovercard>
</HovercardProvider>
```

> 2\. Is it possible that, if the `open` prop is no longer intended to work with a Tooltip, that Ariakit might remove it? The current state, where the prop is present but doesn't work like one expects, is a little confusing.

Could you provide more details on why you believe the `open` prop isn't working? I'm able to control the tooltip's visibility using it:

```jsx
const [open, setOpen] = useState(false);

<button onClick={() => setOpen(!open)}>Toggle tooltip</button>

<TooltipProvider open={open} setOpen={setOpen}>
  <TooltipAnchor />
  <Tooltip />
</TooltipProvider>
```

It's just that `setOpen` will be called when another tooltip is shown.

**Comment by vivshaw** [comment]
> Could you provide more details on why you believe the open prop isn't working? I'm able to control the tooltip's visibility using it:
> It's just that setOpen will be called when another tooltip is shown.

Thank you, this clears up my misunderstanding! I had assumed that `open` would have semantically the same meaning for Tooltip as it does for Popover, Hovercard, etc. ("it exclusively controls the open state"), and assumed that your earlier answer meant that Tooltip should not be used with the `open` prop. Now I understand that the intention is for `open` to be usable with both, but to work a little differently- "it exclusively controls the open state" for Hovercard, Popover, etc., and "it'll pop the thing open, but other things can pop it closed" for Tooltip.

It'd be neat if the docs clarified this difference (and I'd be happy to PR an update if you think that's worthwhile). Other than that, I think we're all resolved! Thanks for answering :+1:

**Comment by taehee-sp** [comment]
It helped me a lot. Our app went down when we open two tooltip as default (with open prop).

We changed our tooltip implementation with hovercard.

I hope you can add it to the document that we can't open two tooltips at the same time (by controlled state).

**Comment by vivshaw** [comment]
A note for posterity in case anyone else finds this:

@diegohaz was absolutely correct, Popover did the trick! We had a bit of a rocky migration from Tooltip to Popover and from our old version to the current, but we got there in the end.

One specific piece of advice for anyone who has the same usecase I did, "a Tooltip-like thing that is either externally controlled by an `open` prop, or always open": there are a few Popover props that you will probably want to set. [`autoFocusOnHide`](https://ariakit.org/reference/popover#autofocusonhide), [`autoFocusOnShow`](https://ariakit.org/reference/popover#autofocusonshow), and [`hideOnInteractOutside`](https://ariakit.org/reference/popover#hideoninteractoutside) each default to `true`, and can each lead to some pretty surprising behavior in a controlled Popover if you weren't expecting them. So, if you experience any seeming Heisenbugs around Popovers and focus states, don't panic: there's a high chance that playing with these props will solve it!

**Comment by diegohaz** [comment]
> A note for posterity in case anyone else finds this:
> 
> @diegohaz was absolutely correct, Popover did the trick! We had a bit of a rocky migration from Tooltip to Popover and from our old version to the current, but we got there in the end.
> 
> One specific piece of advice for anyone who has the same usecase I did, "a Tooltip-like thing that is either externally controlled by an `open` prop, or always open": there are a few Popover props that you will probably want to set. [`autoFocusOnHide`](https://ariakit.org/reference/popover#autofocusonhide), [`autoFocusOnShow`](https://ariakit.org/reference/popover#autofocusonshow), and [`hideOnInteractOutside`](https://ariakit.org/reference/popover#hideoninteractoutside) each default to `true`, and can each lead to some pretty surprising behavior in a controlled Popover if you weren't expecting them. So, if you experience any seeming Heisenbugs around Popovers and focus states, don't panic: there's a high chance that playing with these props will solve it!

@vivshaw Thanks for the follow-up.

That's true. Currently, controlled components are not fully controlled. We keep the internal state as the source of truth and adjust it based on the controlled value from props, if needed. Due to how React works, this can't be done synchronously, so there might be a single render/commit phase when a popover is closed even though you're passing `open={true}` to it. As you experienced, this may trigger show/hide behaviors (like `autoFocusOnShow/Hide`) unexpectedly.

The original idea was to ensure consistency throughout the store state. For example:

```js
popoverStore.setOpen(false);
console.log(popoverStore.getState().open);
```

This ensures that `false` will be logged in the console even when the component is controlled (then it will be set to the controlled value again in the next render).

However, this proved to be more problematic than helpful. In v0.5.0, we will change this behavior so that the controlled props, if passed, will be the source of truth. This means the internal `open` state will never differ from the controlled `open` prop. Therefore, you won't need to worry about `autoFocusOnHide`, `autoFocusOnShow`, etc., triggering their behavior due to changes in the internal state while the controlled state didn't.

Related issues:

#3402
#4100
