### ISSUE TITLE
Allow interactions with iframes to hide popovers

### ISSUE THREAD

**Issue by ciampo** [ariakit/ariakit#3250]
### Current behavior

Originally discussed in https://github.com/WordPress/gutenberg/issues/57206#issuecomment-1863615985

> Ariakit popups using the [hideOnInteractOutside](https://ariakit.org/reference/tooltip#hideoninteractoutside) prop only close when you interact with something else in the same window.
>
> We might be able to do something about iframes though.

@diegohaz , what did you have in mind? Could ariakit allow interactions to/from iframes as triggers to hide popovers?

### Steps to reproduce the bug

N/A

### Expected behavior

N/A

**Comment by diegohaz** [comment]
Let's use https://github.com/ariakit/ariakit/issues/3031
