### ISSUE TITLE
[Combobox] It's not possible to scroll outside of focused item

### ISSUE THREAD

**Issue by honzatmn** [ariakit/ariakit#3285]
### Current behavior

In [multiselect example](https://ariakit.org/examples/combobox-multiple) (with `focusOnHover` enabled), when scrolling, the focus doesn't allow to scroll the item outside of the visible area and results in glitching (see video)

https://github.com/ariakit/ariakit/assets/6851247/27cc6424-bbff-4b7a-8cc7-d525fab5c717

### Steps to reproduce the bug

1. Open [multiselect example](https://ariakit.org/examples/combobox-multiple) 
2. Hover over an item
3. Try to scroll away

### Expected behavior

It's possible to scroll the list without issues

### Workaround

Set [`resetValueOnSelect`](https://ariakit.org/reference/combobox-provider#resetvalueonselect) to false and manually reset the combobox value.

**Comment by diegohaz** [comment]
Thanks for the report, @honzatmn!

Are you able to reproduce this issue locally, or does it only occur on the site? I suspect that an unreleased change might have introduced this regression.
