### ISSUE TITLE
Screen reader announces all dialog content instead of focused controls

### ISSUE THREAD

**Issue by charlesanim** [ariakit/ariakit#3377]
### Discussed in https://github.com/ariakit/ariakit/discussions/3340

<div type='discussions-op-text'>

<sup>Originally posted by **charlesanim** January 18, 2024</sup>
I have a dialog that is opened when a user clicks on their profile picture icon in a header. This dialog contains a close X button, line of text and about 5 buttons aligned vertically.  When screen reader is activated specifically windows narrator, it reads all the content in the dialog including the buttons instead of just the button that its focused on. Any thoughts on this? Is there any prop in Ariakit i can leverage?              Am I missing anything here? Have other folks encountered this issue or similar issue? Any help is appreciated. 

````
<AriakitDialog
                modal={false}
                portal={false}
                backdrop={backdrop}
                store={dialogStore}
                // Let custom focus handler handle the focus
                autoFocusOnShow={false}
                autoFocusOnHide={false}
                hideOnEscape={false}
                aria-modal={true}
                aria-describedby={DESCRIPTION_ID}
                hideOnInteractOutside={false}
                {...rest}
            >
            
            

</div>

**Comment by diegohaz** [comment]
Please, let's keep questions in discussions. I recommend adding a video to your post reproducing the behavior with one of the three major screen readers (NVDA, JAWS, or VoiceOver) as we don't officially support Narrator.

If you believe this is a bug, I'd ask you to follow the bug template when creating the issue.
