### ISSUE TITLE
Regression with Menus and 0.4.0

### ISSUE THREAD

**Issue by httpete** [ariakit/ariakit#3382]
### Current behavior

In 0.3.13, Menus opened and closed fine, according to the show and hide timeouts.
After upgrading to 0.4.0, they don't respond to .hide() as quickly and my menus interleave.

Just an alert that 0.4.0 does not work the same as 0.3.13.  I can try to make a reproduction example, but it is just a set of Menus and I programatically call .hideAll() and .show() to open and close them onMouseEnter.

### Steps to reproduce the bug

Have a set of Menus, and programatically call show and hide.

### Expected behavior

Show and hide when programatically called have changed - they seem to have a timeout applied when they didn't before. menu.hide() knocked it down immediately. Now it has a delay.

**Comment by diegohaz** [comment]
> ### Steps to reproduce the bug
> Have a Menu set, and showOnHover={true}

I couldn't see any difference between 0.3.13 and 0.4.0 when using `showOnHover`. Could you please provide more details?

**Comment by httpete** [comment]
I have isolated it I think - the show and hideTimeouts are not honored at all in 0.4.0.

```
    const rkMenu = useMenuStore({
      placement: isTopNavFirstLevel ? 'bottom-start' : 'right-start',
      showTimeout: 4000,
      hideTimeout: 5100,
    });

**Comment by diegohaz** [comment]
What exactly is the difference between versions 0.3.13 and 0.4.0 in that CodeSandbox? I ran tests with both versions and they seem to behave identically. I can keep both menus open if I move the mouse in a specific way in both versions. The video below is using your CodeSandbox with `@ariakit/react@0.3.13`:

https://github.com/ariakit/ariakit/assets/3068563/150d3479-6637-4873-9c03-ebc9a4229431

**Comment by diegohaz** [comment]
Is it possible that the behavior you're observing with 0.4.0 was present earlier, but you just didn't happen to reproduce it (since it requires specific mouse movements)?

In fact, the demo you provided is working as expected, even for 0.3.13, due to _hover intent_. When the user moves the mouse toward the menu, pointer events outside the menu are disabled. That's why your `onMouseLeave` event handler doesn't trigger when the mouse leaves the menu button to reach its menu. Without this hover intent detection, it wouldn't work as you expect at all. You can turn off the hover intent detection feature by setting the [`disablePointerEventsOnApproach`](https://ariakit.org/reference/menu#disablepointereventsonapproach) prop to `false` on the `Menu` component.

**Comment by httpete** [comment]
I tried disablePointerEventsOnApproach  Ill keep fiddling, but it worked great in 0.3 and as soon as I go to 0.4 I See:
![image](https://github.com/ariakit/ariakit/assets/1200635/876eb1d1-46e2-47c5-a18c-d086a12ede30)

**Comment by diegohaz** [comment]
Is the app public (not the code, just the app itself)?

**Comment by httpete** [comment]
Unfortunately no. I am just fiddling away trying to see why the timeouts don't work right.  I really want the top level site menus to be up and down immediately, and have the rest of them have a nice natural timeout. I do this in a store action where I knock them down:
```
    actionHideAllMenusAndShowMenu: menuToShow => {
      const menus = get().topLevelMenus;
      menuToShow.setState('timeout', 0);
      menuToShow.setState('showTimeout', 0);
      menuToShow.show();
      menus.forEach(menu => {
        if (menu !== menuToShow) {
          menu.setState('hideTimeout', 0);
          console.log(menu.getState());

          menu.hide();
        }
      });
    },
    
    This worked swell in the old version.

**Comment by httpete** [comment]
What I Am noticing is even if I set timeout: 0 on the store, the menus still (even the normal second level menus) lag and overlap.

**Comment by diegohaz** [comment]
Are those menus animated?

**Comment by httpete** [comment]
nope - never had animation on.

**Comment by httpete** [comment]
WOO! That was it! If I do 0.4 and set animated to 0, it works fine!!!

**Comment by diegohaz** [comment]
In v0.4.0, animations are automatically detected. Is there a chance you have any CSS animation/transition property set on your menu components? Can you inspect them and check their computed styles?

**Comment by httpete** [comment]
Does this count as an animation?
![image](https://github.com/ariakit/ariakit/assets/1200635/466c1520-7030-47fc-893f-78099fea8321)

**Comment by diegohaz** [comment]
Yes, Ariakit will now automatically wait for those 300 milliseconds before hiding the menu, the same way it would do with the `animated` prop set to `true` in previous versions. You can turn off the leave transition with something like this:

```css
.menu[data-leave] {
  transition: none;
}
```

**Comment by httpete** [comment]
so not with animated: false? Big thanks again @diegohaz

**Comment by diegohaz** [comment]
> so not with animated: false? Big thanks again @diegohaz

Exactly. Though that works now, the `animated` prop will be removed in a future version (probably hard deprecated in 0.5.0 and then finally removed in 0.6.0 or 1.0.0), so transitions should be managed where they should be, in CSS.

**Comment by httpete** [comment]
Whew I think I Am going to limp off by doing animated: false on my stores at the moment, and get that in and working. This was a surprise for sure and super hard to tell!

**Comment by httpete** [comment]
I don't see the [data-leave] attribute on the menu - ?
```
          <AriaMenu
            store={rkMenu}
            render={
              <Paper
                component="ul"
                sx={{
                  zIndex: 15000,
                  m: 0,
                  p: 0,
                  ':focus-visible': { outline: 'none' },
                  '[data-leave]': {
                    transition: 'none',
                  },
                }}
                elevation={8}
              />
            }

**Comment by httpete** [comment]
When I turn the animation off - suddenly my menu item clicks don't work? Wierd?

**Comment by httpete** [comment]
Ok for other folks - I am integrating MUI and Ariakit. This is an unfriendly combination given how much MUI does these transitions all over the css.

My current fix is to do an sx prop way up at the top of the component that houses our menus and do this:
```
          '* [data-leave]': {
            transition: 'unset!important',
          },

**Comment by diegohaz** [comment]
> @diegohaz  Diego - just one last point - super strange here.
> 
> I have one menu that renders in a portal and portalRef and one that doesn't. 
> 
> 
> 
> The one that renders in the Portal, the LAST MENU onClicks won't work if I do the [data-leave] css trick, the rest work fine. The CSS somehow stops the onClick handler. I have it absolutely pegged.
> 
> 
> 
> The one that doesn't render in the portal, works fine with the [data-leave] transition unset.

That looks like another problem. Could you open a separate issue (with a repro please, even if it's not minimal)?
