### ISSUE TITLE
Combobox examples seem broken at least on mobile 

### ISSUE THREAD

**Issue by crisshaker** [ariakit/ariakit#3485]
### Current behavior

https://github.com/ariakit/ariakit/assets/36159205/ad2846a2-7418-46f2-b187-661031a3ef98

### Steps to reproduce the bug

1. Visit https://ariakit.org/examples/combobox-animated on a mobile browser
2. Try searching in the combobox

### Expected behavior

The list should filter as you type

**Comment by diegohaz** [comment]
Combobox does not automatically filter its options. See [Combobox filtering](https://ariakit.org/examples/combobox-filtering).
