### ISSUE TITLE
Nested tabs no longer working

### ISSUE THREAD

**Issue by mattrothenberg** [ariakit/ariakit#3550]
### Current behavior

Previously, when rendering a nested tab UI inside of a `TabPanel`, the nested tabs behaved normally. Now, selecting an inner tab affects the pattern tabs.

### Steps to reproduce the bug

**Version 0.3.14** works fine
https://stackblitz.com/edit/ariakit-rbzvhn?devToolsHeight=33&file=src%2FApp.tsx

**Version 0.4.0** no longer works
https://stackblitz.com/edit/ariakit-gkymik?devToolsHeight=33&file=src%2FApp.tsx,package.json,src%2Findex.tsx

### Expected behavior

When clicking a nested tab, I don't expect it to have any effect on a parent tab.

### Workaround

Don't use nested tabs?

Or https://github.com/ariakit/ariakit/issues/3550#issuecomment-1978977492

**Comment by diegohaz** [comment]
Thanks for reporting. Indeed, there's a regression in v0.4.2.

For now, you can circumvent this issue by explicitly passing `composite={null}` to the [`TabProvider`](https://ariakit.org/reference/tab-provider) component:

```jsx
// TODO: Remove the composite prop when https://github.com/ariakit/ariakit/issues/3550 is resolved
<TabProvider composite={null}>
```

Also, could you elaborate on your use case for nested tabs? It would help us create an example and ensure we don't break this again in the future.
