### ISSUE TITLE
Typeahead is not working correctly with virtualised select

### ISSUE THREAD

**Issue by patrikholcak** [ariakit/ariakit#3567]
### Current behavior

I know the `<SelectRenderer />` component is still experimental, but while implementing it, I discovered that typeahead isn’t working for items that aren’t rendered. I noticed #3535 and tried to update to newer version but it still didn’t work. My use case doesn’t allow for rendering combobox, because the performance isn’t as great as with selects (as noted in [#3451](https://github.com/ariakit/ariakit/issues/3451#issuecomment-1962363666))

On the topic of typeahead, I’m also thinking if matching the `value` of the item (as opposed to the option label users see) is the right choice, because for example with countries, `Switzerland` might have a value of `ch` and typing `Swi…` wouldn’t work.

### Steps to reproduce the bug

1. Open https://stackblitz.com/edit/github-vjvhs5-d9z3gk?file=src%2FApp.tsx
2. Open the select
3. Try typing "G" for Germany or any other country below the fold

### Expected behavior

The select has knowledge of all items using the `defaultItems` prop to `<SelectProvider />` (or `useSelectStore`) so it should be able to guesstimate the position in the list and scroll.

### Workaround

—

### Possible solutions

We should probably use the `items` state here if its length is greater than the length of `renderedItems`:

https://github.com/ariakit/ariakit/blob/771ba3e3110b8f39d9cb00a160888dc3eaf84d78/packages/ariakit-react-core/src/composite/composite-typeahead.ts#L132-L137

**Comment by diegohaz** [comment]
> ### Steps to reproduce the bug
> 1. Open https://stackblitz.com/edit/github-vjvhs5-d9z3gk?file=src%2FApp.tsx
> 2. Open the select
> 3. Try typing "G" for Germany or any other country below the fold

It's possible that #3535 has broken the typeahead functionality on virtualized lists. If you test your reproduction with `v0.4.1`, it works as expected.

> On the topic of typeahead, I’m also thinking if matching the `value` of the item (as opposed to the option label users see) is the right choice, because for example with countries, `Switzerland` might have a value of `ch` and typing `Swi…` wouldn’t work.

`CompositeTypeahead` uses `value` as a fallback. It will check the rendered element's `textContent` and the item's `children` properties first.

**Comment by patrikholcak** [comment]
Yup, downgrading works for now. Thanks!

**Comment by patrikholcak** [comment]
@diegohaz Sorry for the ping, but any news on this? I’d love to upgrade :pray: I don’t know much about the internals, but I can attempt to fix this if you point me in the right direction

**Comment by diegohaz** [comment]
Not yet. Stabilizing virtualization is one of my next tasks, and this issue is part of that.

**Comment by patrikholcak** [comment]
Thank you for the update!
