### ISSUE TITLE
Input inside Menu does not autoFocus 

### ISSUE THREAD

**Issue by abhishekmg** [ariakit/ariakit#3700]
### Current behavior

Having input with `autoFocus` true inside the menu does not trigger the inputs focus

https://github.com/ariakit/ariakit/assets/34393560/67af4273-e821-4b6e-9c80-3fe77bd0c5e6

### Steps to reproduce the bug

https://codesandbox.io/p/sandbox/gallant-kapitsa-m83myg?file=%2Fsrc%2FApp.js%3A13%2C60

in this codesandbox open the menu 

### Expected behavior

When the menu is opened the input should have autoFocus

**Comment by diegohaz** [comment]
A textbox (`input`) isn't a valid child of a `role="menu"` element (`Menu`). If you describe the kind of UI you're trying to implement, I can suggest a more appropriate structure. For example, consider a [Menu with Combobox](https://ariakit.org/examples/menu-combobox).

**Comment by abhishekmg** [comment]
Thank you for the reply @diegohaz ! The UI I want to achieve is just rending a Input inside a dropdown , thats why I had chosen to have an input element inside the `Menu` component 

I have just found a solution for this using `initialFocus` passed to `Menu`. This solved the issue I was facing 

https://codesandbox.io/p/sandbox/gallant-kapitsa-m83myg?file=%2Fsrc%2FApp.js%3A18%2C11-18%2C23

**Comment by diegohaz** [comment]
I see. If you want an input inside a dropdown, you probably want to use [Popover](https://ariakit.org/components/popover), not `Menu`. As I said, a textbox (`input`) isn't a valid child of a `role="menu"` element (`Menu`). This will produce an invalid accessibility tree.

**Comment by abhishekmg** [comment]
Oh got it ! yes using `Popover` will help in implementing the UI I need , thank you so much will proceed with this ! 😄
