### ISSUE TITLE
Infinite dialog(alert, etc.) loop on `<Radio>` button change with arrow key navigation

### ISSUE THREAD

**Issue by wonu** [ariakit/ariakit#3771]
### Current behavior

If radio buttons trigger a dialog (alert, confirm, or prompt) on `change` event, navigating between buttons with arrow keys causes an infinite loop of dialogs opening.

### Steps to reproduce the bug

Tested on Windows 11, Chrome 124.0.6367.119, Firefox 125.0.3.

1. Open https://stackblitz.com/edit/vitejs-vite-jbhfjq?file=src%2FApp.tsx,package.json&terminal=dev
    1. Created with `vite.new/react-ts`
    2. Installed `@ariakit/react (0.4.6)`
    3. Modified `App.tsx`
2. Follow the reproduction setps in `App.tsx`
    1. click one radio button
    2. close alert dialog
    3. press an arrow key
    4. close alert dialog (loop starts here in Chrome)
    5. click the next button
    6. close alert dialog (loop starts here in Firefox)

### Expected behavior

With native radio buttons, closing dialog does not trigger further dialogs.

### Workaround

https://github.com/ariakit/ariakit/issues/3771#issuecomment-2295743206

**Comment by diegohaz** [comment]
Workaround:

```jsx
const radio = Ariakit.useRadioStore();

<Ariakit.RadioProvider store={radio}>
  ...
    <Ariakit.Radio
      value="a"
      // TODO: Remove when https://github.com/ariakit/ariakit/issues/3771 is fixed
      onFocus={(event) => {
        const checked  = store.getState().value === "a";
        if (checked) {
          // Avoid triggering onChange on focus when the radio button is already checked in the store
          event.preventDefault();
        }
      }}
    />
```
