### ISSUE TITLE
AutoSelect weird behavior in virtualized SelectCombobox during Touch Events

### ISSUE THREAD

**Issue by marilari88** [ariakit/ariakit#3808]
### Current behavior

Hi @diegohaz,

I'm encountering an issue when combining Ariakit's `SelectCombobox` with Virtua, specifically when `autoSelect="true"` is enabled. The functionality generally works well, but on mobile devices, I’ve noticed some unusual behavior.

**Steps to Reproduce:**
1. Type into the combobox input.
2. Attempt to scroll using a touch event.

**Observed Behavior:**
Scrolling becomes impossible because the focus repeatedly returns to the first auto-selected element, interrupting the scrolling action.

This issue is also present in the example with `selectRenderer`

**Screenshots:**
1. ![autoSelect issue](https://github.com/ariakit/ariakit/assets/32909388/5a3814d1-aaeb-4079-9626-e22ca3790ba4)
2. ![selectrenderer](https://github.com/ariakit/ariakit/assets/32909388/c1434287-66b5-4009-ba89-6e0e8bb4cbcc)

Could you please look into this? Any guidance or fixes would be greatly appreciated.

Thank you!

### Steps to reproduce the bug

https://stackblitz.com/~/github.com/marilari88/ariakit-virtua-select-combobox

### Expected behavior

I expect to scroll through the filtered SelectItems smoothly, similar to the experience on non-touch devices.

### Workaround

https://github.com/ariakit/ariakit/issues/3808#issuecomment-2123532464

**Comment by diegohaz** [comment]
Thanks for the report! The best workaround I can think of right now is to disable `autoSelect` when you detect a touch device.
