### ISSUE TITLE
Unexpected behavior when updating to the latest Next.js version

### ISSUE THREAD

**Issue by irangarcia** [ariakit/ariakit#3818]
### Current behavior

When updating Next.js to the latest version `14.2.3` this happens:

<img width="952" alt="Screenshot 2024-05-23 at 09 19 37" src="https://github.com/ariakit/ariakit/assets/60601780/8bd5f955-f9cb-4f1c-96e0-fd3374eed55a">

### Steps to reproduce the bug

Using ariakit 0.4.5

1. Update Next.js to `14.2.3`
2. Run `npm run dev`
3. The error happens

### Expected behavior

Run the server without errors

**Comment by georgekaran** [comment]
Hey @irangarcia 

Could you provide a reproducible so we can investigate?

**Comment by irangarcia** [comment]
Turn out to be an internal problem with our library
