### ISSUE TITLE
Animating children of Disclosure breaks after first animation

### ISSUE THREAD

**Issue by petejodo** [ariakit/ariakit#3828]
### Current behavior

`data-enter=true` not being removed from a disclosure when the disclosure closes, therefore transition animations are breaking.

My repro is a contrived example for sake of repro but my actual use case is using the Dialog as a mobile side nav. The nav swings in from the left which is a child of the actual element that the dialog rendered. It is an adaption of the tailwind side navigation components.

### Steps to reproduce the bug

1. Open https://stackblitz.com/edit/ariakit-kpxl8r?file=src%2Fstyle.css
2. Open dialog, note animated fade-in of the list
3. Close and reopen dialog
4. Note that the list is no longer animating the fade-in

### Expected behavior

The animation to continue to work across multiple dialog open/closes

### Workaround

This is breaking due to in `DisclosureContent`, [it parses the transition delay/duration](https://github.com/ariakit/ariakit/blob/main/packages/ariakit-react-core/src/disclosure/disclosure-content.tsx#L174-L195) on the disclosure element which will be 0 since it isn't on the disclosure element which will cause `animated` state to be set to `false` on a later render. Since animated is `true` at first, the animation does work for 1 time. Adding a transition duration to the disclosure element e.g. the dialog works around this issue.

### Possible solutions

I believe this may just be user misuse but I'm not entirely sure. Below is the tailwind html of the side nav in case there would be a different way this should be implemented.

```html
<!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
<!-- ### This is the classes I have set for Dialog ### -->
<div class="relative z-50 lg:hidden" role="dialog" aria-modal="true">
  <!--
    Off-canvas menu backdrop, show/hide based on off-canvas menu state.

    Entering: "transition-opacity ease-linear duration-300"
      From: "opacity-0"
      To: "opacity-100"
    Leaving: "transition-opacity ease-linear duration-300"
      From: "opacity-100"
      To: "opacity-0"
  -->
  <div class="fixed inset-0 bg-gray-900/80"></div>

  <div class="fixed inset-0 flex">
    <!--
      Off-canvas menu, show/hide based on off-canvas menu state.

      Entering: "transition ease-in-out duration-300 transform"
        From: "-translate-x-full"
        To: "translate-x-0"
      Leaving: "transition ease-in-out duration-300 transform"
        From: "translate-x-0"
        To: "-translate-x-full"
    -->
    <div class="relative mr-16 flex w-full max-w-xs flex-1">
      <!--
        Close button, show/hide based on off-canvas menu state.

        Entering: "ease-in-out duration-300"
          From: "opacity-0"
          To: "opacity-100"
        Leaving: "ease-in-out duration-300"
          From: "opacity-100"
          To: "opacity-0"
      -->
      <div class="absolute left-full top-0 flex w-16 justify-center pt-5">
        <button type="button" class="-m-2.5 p-2.5">
          <span class="sr-only">Close sidebar</span>
          <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

      <!-- Sidebar component, swap this element with another sidebar if you like -->
      <div class="flex grow flex-col gap-y-5 overflow-y-auto bg-indigo-600 px-6 pb-4">
          ...
      </div>
    </div>
  </div>
</div>
```

**Comment by petejodo** [comment]
looking a little more into it, using `portalElement` as the wrapping element could work but seems cumbersome since you have to define it as a callback function. I noticed an undocumented type `wrapElement` but I can seem to get typescript happy with it

**Comment by georgekaran** [comment]
Not sure if it fits your use-case but as an alternative workaround you could add [unmountOnHide](https://ariakit.org/reference/dialog#unmountonhide) to your `Dialog`.

**Comment by diegohaz** [comment]
This is working as intended. `DisclosureContent` only detects animations and transitions on its own element. This is because there may be multiple children with animations unrelated to the enter/exit state of the disclosure content as a whole.

Previously, you could pass `animated: 300` to the disclosure/dialog store/provider. This would force the disclosure content to wait 300 ms before hiding/unmounting and removing the `data-enter` attribute. This option still exists but is deprecated because JavaScript is not the ideal place to configure this setting.

The workaround you suggested is actually the canonical solution:

> Adding a transition duration to the disclosure element e.g. the dialog works around this issue.

You can configure both the enter and leave states:

```css
.dialog {
  transition-duration: 300ms;
}
```

Or only a single state:

```css
.dialog[data-enter] {
  transition-duration: 300ms;
}
```

Doing this with JavaScript wasn't as straightforward. Additionally, CSS allows you to use CSS variables and/or benefit from inheritance:

```css
.dialog {
  transition-duration: 300ms;
}

.dialog .list {
  transition-duration: inherit;
}
```

**Comment by petejodo** [comment]
`transition-duration: inherit` makes total sense to me, thanks! This maybe has potential as a pro example :wink:

**Comment by petejodo** [comment]
One annoyance is that because `inherit` only inherits from the direct parent, you need to add a chain of `transition-duration: inherit` from the disclosure to the child element you want to animate

**Comment by diegohaz** [comment]
I recommend using a custom property:

```css
.dialog {
  --transition-duration: 300ms;
  transition-duration: var(--transition-duration);
}

.list {
  transition-duration: var(--transition-duration);
}
```

**Comment by petejodo** [comment]
ok that works a bit better. One minor annoyance with that still (sorry I'm not trying to be difficult! 😅) is that the backdrop doesn't inherit the css variable so you end up having to set the css variable twice, one for the dialog and its children and then another for the backdrop itself. This is a very minor inconvenience though
