### ISSUE TITLE
Cannot use arrow keys to move around textfield in Select with Combobox and Tabs example.

### ISSUE THREAD

**Issue by rostero1** [ariakit/ariakit#3889]
### Current behavior

Cannot use arrow keys to move around textfield in Select with Combobox and Tabs example.

This is similar to a problem I see with react-aria-components table where it's trying to handle keyboard navigation for you within cells, but gets tripped up on an input field.  

I'm not sure the actual solution here.  GitHub seems to allow the user to move around the input field with their keyboard, but will take control after they reach the ends of the input field.

### Steps to reproduce the bug

1. Open https://ariakit.org/examples/select-combobox-tab
2. Select the fourth combobox.
3. Type some text in the "Find or create branch" input field.
4. Use your arrows move around the input field.  It changes tabs instead of allowing the user to move the cursor around the input field to correct a mistake in the text.

### Expected behavior

Expected the cursor position to change within the field.  When it reaches the end of the field it could resume the current arrow-left/right behavior of changing tabs.

**Comment by diegohaz** [comment]
That's intentional. You can move the caret by focusing directly on the text box, either by clicking on it or pressing the Arrow Up key.
