### ISSUE TITLE
Portals open behind native dialogs

### ISSUE THREAD

**Issue by ilyasmez** [ariakit/ariakit#3934]
### Current behavior

Portals or a portal-based components (popover, menu, etc.) render in the background when used inside a native <dialog> element.

When the [<dialog element>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) is opened using the the [`.showModal()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal) method, it gets rendered in a special [top layer](https://developer.mozilla.org/en-US/docs/Glossary/Top_layer), which is above anything, including the portals added to the document.

### Steps to reproduce the bug

1. Open https://stackblitz.com/edit/hx9wql-uqkw8j?file=App.tsx&theme=light
2. Press the "Open popover" button
3. Notice that the popover is opening behind the dialog

https://github.com/ariakit/ariakit/assets/30146019/e25118d0-c677-46a2-abf5-eccbd7fe6d59

### Expected behavior

https://github.com/ariakit/ariakit/assets/30146019/9b64c445-281f-482b-9c20-20bebdfb8e1c

### Workaround

https://github.com/ariakit/ariakit/issues/3934#issuecomment-2220222385

### Possible solutions

It would be nice if the Ariakit portals supported being rendered inside a native dialog, maybe by adding the portal to the dialog itself instead of the document, or by using a top layer as well.

**Comment by diegohaz** [comment]
You can use [`PortalContext`](https://ariakit.org/reference/portal-context).

**Comment by ilyasmez** [comment]
`PortalContext` + setting `overflow: visible` on the dialog was exactly what I needed:
https://stackblitz.com/edit/hx9wql-k15zuw?file=App.tsx

Thank you very much @diegohaz!!
