### ISSUE TITLE
[Combobox] - input is pushed up during height animation

### ISSUE THREAD

**Issue by ItaiYosephi** [ariakit/ariakit#3937]
### Current behavior

Hi,
During height animation triggered by `ReizeObserver`, the input is pushed up and isn't seen until the end of the animation.
When replacing `Combobox` with a plain input, it works fine.

https://github.com/ariakit/ariakit/assets/40234776/ff5f825d-10f1-493c-bcfa-92d60f1f3a94

### Steps to reproduce the bug

1. Open https://stackblitz.com/edit/2fswd5?file=dialog-combobox-command-menu%2Findex.tsx
2. Wait 2 seconds for the items to "load" .
3. Replace with plain input for expected behavior 

### Expected behavior

Should work the same as it does when using a native HTML input.

**Comment by diegohaz** [comment]
When you use [`autoSelect="always"`](https://ariakit.org/reference/combobox#autoselect), the first item is automatically focused when the list opens, likely causing the item to scroll into view during the animation.

The solution will depend on your specific use case, but you can either use `autoSelect={true}` or wait until the animation ends to change the value to `"always"`.

**Comment by ItaiYosephi** [comment]
Thanks! `overflow-clip` works great!
