### ISSUE TITLE
Select Combobox scrolls to top when new SelectItems are rendered in ComboboxList

### ISSUE THREAD

**Issue by reydelo** [ariakit/ariakit#3957]
### Current behavior

[Watch this loom](https://www.loom.com/share/46e842eb4ff742bd8ce6ced16d62835d?sid=5bc47be0-f943-4746-9688-2a6122d869c3)

I built a SelectCombobox which is working great - but then I needed to add a virtualization method for long lists. My approach is simple: Initially render 25 items in the ComboboxList with an empty `<div>` at the bottom. When the empty div is scrolled into view, include the next 25 items into the list.

While scrolling through the list (and having additional items rendered), the scroll position jumps to the top. This behavior is not present until a search query is given. Once a search is given, the bug is present with or without a search query.  Everytime a new set of items is added to the list to render, the scroll position shifts back to the top.  This does not happen when using arrow keys to navigate through the list, only when scrolling.

I attempted to rebuild this using [SelectRenderer](https://ariakit.org/examples/select-combobox-virtualized) instead of my own virtualization method, but I ran into many rendering issues and aborted.

https://github.com/user-attachments/assets/f0d5f6c0-5f9e-4782-849c-4596209930c4

### Steps to reproduce the bug

1. Open https://stackblitz.com/edit/u17aat-v6fnfh?file=select-combobox-virtualized%2FSelectCombobox.tsx
2. type a value into the Combobox input (e.g. "a")
3. Slowly scroll through the list
4. when you reach the bottom of the list and new items are added, notice that the scroll position resets to 0 

### Expected behavior

Scroll position should not change during scrolling when additional items are rendered in a ComboboxList

### Workaround

Looks like this behavior is triggered by something internal to Ariakit's components and a workaround is not possible - perhaps [useCompositeHover.tsx](https://github.com/ariakit/ariakit/blob/aee0ca3e68c9ed9017a03e912307adcf34bbc2f6/packages/ariakit-react-core/src/composite/composite-hover.tsx#L73)?

**Comment by diegohaz** [comment]
> ### Steps to reproduce the bug
> 1. Open https://stackblitz.com/edit/ariakit?devToolsHeight=33&file=src%2FApp.tsx

Hi! Thanks for reporting.

I believe you forgot to replace the repro link here?

**Comment by reydelo** [comment]
@diegohaz oops 🤦‍♀️  
here's the code: https://stackblitz.com/edit/u17aat-v6fnfh?file=select-combobox-virtualized%2FSelectCombobox.tsx

**Comment by diegohaz** [comment]
Thanks for the repro.

I don't know exactly why that was happening, but that `render={<Fragment>}` seemed suspicious, so I removed it, and it seems to be working now: https://stackblitz.com/edit/u17aat-gk6yzb?file=select-combobox-virtualized%2FSelectCombobox.tsx

I assume your specific use case is more complex, so let me know if it doesn't work for you.

**Comment by reydelo** [comment]
@diegohaz you're right, the `render={<Fragment>}` was the culprit.  I'm happy that the fix is simple and not stuck in the library code  🙏  thank you!
