### ISSUE TITLE
[Dialog + Tabs] -  Selected tab reset when dialog closes

### ISSUE THREAD

**Issue by ItaiYosephi** [ariakit/ariakit#3963]
### Current behavior

when closing a dialog that renders `Tabs`, `setSelectedId` is fired with the original `selectedId`

https://github.com/user-attachments/assets/a5069330-12df-4abe-8adf-636a751c1ada

### Steps to reproduce the bug

1. Open https://github.com/user-attachments/assets/b368a7ae-6ca7-469e-a13f-631a8db5ab9c
https://stackblitz.com/edit/am32ns-b2vc47?file=dialog-combobox-command-menu%2Findex.tsx
2. Click on button
3. Move to a different tab
4. Close the dialog

### Expected behavior

`setSelectedId` shouldn't fire when dialog closes

### Workaround

https://github.com/ariakit/ariakit/issues/3963#issuecomment-2301183016

**Comment by benrodrs** [comment]
Workaround:

```jsx
// TODO: Remove when https://github.com/ariakit/ariakit/issues/3963 is fixed
const canSetTabRef = useRef(true);

<CommandMenu
  // ...
  // TODO: Revert to setTabId={setTabId} when https://github.com/ariakit/ariakit/issues/3963 is fixed
  setTabId={(tabId) => {
    if (!canSetTabRef.current) {
      canSetTabRef.current = true;
    } else {
      setTabId(tabId);
    }
  }}
  onClose={() => {
    canSetTabRef.current = false;
  }}
```
