### ISSUE TITLE
Smooth scroll issue when closing Dialog and chrome device toolbars enabled

### ISSUE THREAD

**Issue by SarKurd** [ariakit/ariakit#3980]
### Current behavior

When using `scroll-behavior: smooth` and closing the dialog, the scroll restore [here](https://github.com/ariakit/ariakit/blob/0dc620f15b2371ea7b0a3d101ea5d14c75ffed0a/packages/ariakit-react-core/src/dialog/utils/use-prevent-body-scroll.ts#L72) triggers the smooth scroll.

Also applying `position fixed` with with negative `top` affects places where we rely on the scroll position (window.scrollY)

https://github.com/user-attachments/assets/4bc33f41-90a5-481d-88b3-8509bdbe6c76

### Steps to reproduce the bug

1. Open https://codesandbox.io/p/devbox/modal-scroll-smooth-issue-pw9hjs or https://pw9hjs-5173.csb.app/
2. Open chrome dev tools and enable devices toolbar
3. Use any device
4. Scroll down and open the dialog
5. Now close the dialog and see the restoring scroll issue 

### Expected behavior

Closing the dialog shouldn't trigger the smooth scroll and preserve the scroll position

### Workaround

https://github.com/ariakit/ariakit/issues/3980#issuecomment-2260735633

### Possible solutions

Temporary disable `scroll-behavior: smooth` when the dialog closes.

**Comment by benrodrs** [comment]
> ### Possible solutions
> Temporary disable `scroll-behavior: smooth` when the dialog closes.

You can do that in the `onClose` handler:

```jsx
<Ariakit.Dialog
  onClose={() => {
    setOpen(false);
    const { style } = document.documentElement;
    const previousScrollBehavior = style.scrollBehavior;
    style.scrollBehavior = "auto";
    queueMicrotask(() => {
      style.scrollBehavior = previousScrollBehavior;
    });
  }}
```

**Comment by diegohaz** [comment]
> Now the other issue is finding a workaround for window.scrollY

Is this a separate problem? If so, could you please open a new issue with a reproduction?

**Comment by SarKurd** [comment]
Adding position: fixed makes that window.scrollY zero, I don't know if we can do anything about it inside ariakit as long we use position fixed for the screen lock

I'll close this issue and try to open another issue for that.
