### ISSUE TITLE
window.scrollY is zero when a Dialog is open

### ISSUE THREAD

**Issue by SarKurd** [ariakit/ariakit#3984]
### Current behavior

When opening a Dialog, window.scrollY becomes zero because we make the body position fixed.

### Steps to reproduce the bug

1. Open https://codesandbox.io/p/devbox/falling-wind-pw9hjs
2. Open chrome dev tools
3. Enable devices toolbar
4. Trigger the Dialog
5. add `window.scrollY` to the console.

### Expected behavior

`window.scrollY` remain the same.

### Workaround

https://github.com/ariakit/ariakit/issues/3984#issuecomment-2261154746

### Possible solutions

We can remove iOS specific related code and use `overscroll-behavior: none`, the disadvantage of this is it supports iOS 16 only and not sure if it breaks anything. Personally i'm fine with it.

Radix and Reach UI: They use react-remove-scroll to handle that which it does a ton of work underneath.
Headless UI: They have some own code which prevents touch actions.
 
~It might be best to just use react-remove-scroll save ourselves the headache.~ never mind, i heard it has some issues too

Should we just ignore iOS and do overflow: hidden? i would rather have the `scroll` APIs work than scroll locking to be honest.

**Comment by benrodrs** [comment]
> ### Steps to reproduce the bug
> 1. Open https://codesandbox.io/p/devbox/falling-wind-pw9hjs
> 2. Open chrome dev tools
> 3. Enable devices toolbar
> 4. Trigger the Dialog
> 5. add `window.scrollY` to the console.

What's the exact buggy behavior here? How does this affect your users?

Also, you can always disable [`preventBodyScroll`](https://ariakit.org/reference/dialog#preventbodyscroll) and replace it with a custom solution when a modal dialog is open.

**Comment by SarKurd** [comment]
Thanks @benrodrs i totally missed that api, will consider my own implementation then.

**Comment by diegohaz** [comment]
I think we can close this issue for now, as it appears to be an edge case that can be resolved by replacing the `preventBodyScroll` logic with a custom solution.
