### ISSUE TITLE
State what screen readers are tested

### ISSUE THREAD

**Issue by WestonThayer** [ariakit/ariakit#399]
### Motivation

Similar to [Reach UI](https://ui.reach.tech/), if the project declares what screen readers and browser combinations are tested, it gives adopters confidence that the components take into account different screen reader quirks to deliver the best UX.

### Example

Quote from Reach UI:

> Each component is tested with Safari + Voiceover, Firefox + NVDA, and Edge + JAWS. As the project matures we’ll get it audited by Web AIM to ensure that if you pick Reach UI, your app has a solid, accessible foundation.

**Comment by WestonThayer** [comment]
Bump

**Comment by WestonThayer** [comment]
Bump

**Comment by lluia** [comment]
I'm happy to help with this one 👍🏻

As far as I saw components on this library are tested through [**RTL**](https://github.com/testing-library/react-testing-library/) ( Node ) simulating keyboard interactions there ... ⌨️ , and I feel that's probably enough?

For what I can see **Reach UI** [does the same](https://github.com/reach/reach-ui/blob/master/packages/combobox/__tests__/combobox.test.tsx) and couldn't find where they state that they test manually with VoiceOver etc... nor any documentation around that process 🤔

One thing we could improve in **Reakit's** tests is to add [`jest-axe`](https://github.com/nickcolley/jest-axe) to them, what do you think @diegohaz ?

**Comment by diegohaz** [comment]
jest-axe would be a nice addition! 👍

I manually test components on Safari with VoiceOver and on Windows Firefox/Chrome with NVDA and JAWS. And this represents about 74% of usage according to the most recent survey from WebAIM: https://webaim.org/projects/screenreadersurvey8/#browsercombos

IE 11 is tested and it works with polyfills (that are added automatically by babel). But I usually don't test JAWS with Internet Explorer (testing on IE alone is enough of a nightmare 😅), but I expect it works.

**Comment by lluia** [comment]
Coolios, I see two pieces of work from this?

### Task 1 

> I manually test components on Safari with VoiceOver and on Windows Firefox/Chrome with NVDA and JAWS. And this represents about 74% of usage according to the most recent survey from WebAIM: https://webaim.org/projects/screenreadersurvey8/#browsercombos

> IE 11 is tested and it works with core-js polyfills (that are added automatically by babel). But I usually don't test JAWS with Internet Explorer (testing on IE alone is enough of a nightmare 😅), 

Explain this in the documentation, maybe in the[ homepage at the bottom](https://reakit.io/) or in the [troubleshooting](https://reakit.io/docs/troubleshooting/) page?

### Task 2

Open a PR adding axe verifications for each component, in the lines of...
```ts
import { axe } from 'jest-axe'

test("has no a11 violations", async () => {
  const { container } = render(<Button>button</Button>)
  const results = await axe(container)
  expect(results).toHaveNoViolations()
})
```

**Comment by tom-sherman** [comment]
@lluia It probably makes sense to also run the examples through jest-axe. Related to #626 and #624

**Comment by WestonThayer** [comment]
Thanks for tackling this y'all! Great to hear you've already been testing in different ATs (assistive technologies, like screen readers) @diegohaz. You might consider adding iOS VoiceOver + iOS Safari to that list, as it's a different codebase than MacOS VoiceOver with different bugs.

@lluia here's where Reach UI mentions it: https://reacttraining.com/reach-ui/

> Each component is tested with Safari + VoiceOver, Firefox + NVDA, and Edge + JAWS. As the project matures we’ll get it audited by WebAIM to ensure that if you pick Reach UI, your app has a solid, accessible foundation.

I agree more detail would be welcome, but documenting exactly how you're manually testing and the AT/browser versions you last tested with can get tedious.

At the least, stating AT/browser support sends the signal that you're willing to fix bugs people find, which is great.

**Comment by diegohaz** [comment]
> You might consider adding iOS VoiceOver + iOS Safari to that list, as it's a different codebase than MacOS VoiceOver with different bugs.

Ah yeah! Forgot to mention that one. I do test on VoiceOver on iOS.

**Comment by lluia** [comment]
@diegohaz should we add that text in the homepage then? 🧐

**Comment by Chudesnov** [comment]
Bump. 

Has anything changed since 2020 in this regard, and does it make sense for an external contributor to send a PR outlining things what @diegohaz stated previously in this thread in project readme and contribution guidelines?
