### ISSUE TITLE
Composite: `[data-focus-visible]` is applied with a noticeable delay

### ISSUE THREAD

**Issue by ciampo** [ariakit/ariakit#4083]
### Current behavior

Originally reported in https://github.com/WordPress/gutenberg/pull/64873 

In the PR linked above, we use the `data-active-item` to apply active (and hover) styles to a `Ariakit.Menu`, and the `data-focus-visible` to apply focus visible styles.

When using the keyboard to navigate the menu items, it can happen that the `data-active-item` styles are applied for a few frames before the `data-focus-visible` styles are (correctly) applied.

@diegohaz said:

> Yes, `data-focus-visible` is applied using `requestAnimationFrame`, but the delay is likely caused by React batching state updates rather than `rAF`. Could you please open an issue on https://github.com/ariakit/ariakit?

### Steps to reproduce the bug

- Open https://stackblitz.com/edit/cbdw6b?file=menu%2Fstyle.css,menu%2Findex.tsx&theme=dark
- Cycle through the active items using keyboard. Notive how, sometimes, the focused item flickers red before turning blue

### Expected behavior

The `data-focus-visible` attribute should be applied sooner, without delays. In the demo shared above, the item should not flicker red.

### Workaround

Using the native CSS `:focus-visible` selector in addition to `[data-focus-visible]` (as done in https://github.com/WordPress/gutenberg/pull/64873) — although this not ideal, as also explained in the [ariakit docs](https://ariakit.org/guide/styling#data-focus-visible)

Or https://github.com/ariakit/ariakit/issues/4083#issuecomment-2321244865

### Possible solutions

Maybe we should wrap the focus visible update in `flushSync` here:

https://github.com/ariakit/ariakit/blob/b2fdf603f8ee3506c022a8da155522b1a250b55f/packages/ariakit-react-core/src/focusable/focusable.tsx#L335

and here:

https://github.com/ariakit/ariakit/blob/b2fdf603f8ee3506c022a8da155522b1a250b55f/packages/ariakit-react-core/src/focusable/focusable.tsx#L350

See https://github.com/ariakit/ariakit/issues/4083#issuecomment-2321244865

**Comment by ciampo** [comment]
Added a Stackblitz example and updated PR description

**Comment by diegohaz** [comment]
This seems to be a delay caused by React. So, alternatively, you can use `flushSync` to update the `data-focus-visible` prop:

```jsx
import { useState } from 'react';
import { flushSync } from 'react-dom';

function CompositeItem(props: Ariakit.CompositeItemProps) {
  // TODO: Remove when https://github.com/ariakit/ariakit/issues/4083 is fixed
  const [focusVisible, setFocusVisible] = useState(false);
  return (
    <Ariakit.CompositeItem
      {...props}
      data-focus-visible={focusVisible || undefined}
      onFocusVisible={(event) => {
        props.onFocusVisible?.(event);
        flushSync(() => setFocusVisible(true));
      }}
      onBlur={(event) => {
        props.onBlur?.(event);
        setFocusVisible(false);
      }}
    />
  );
}
```
