### ISSUE TITLE
`--popover-available-height` is incorrect

### ISSUE THREAD

**Issue by ItaiYosephi** [ariakit/ariakit#4086]
### Current behavior

when using tooltip or popover renderd inside a portal, `--popover-available-height` is expcted to be the full height of the viewport. instead it's a very small number:
![CleanShot 2024-08-29 at 12 15 48](https://github.com/user-attachments/assets/8f7420e2-31e0-47cf-91ff-25c51adf3d32)
this is from the official tooltip example

### Steps to reproduce the bug

1. Open https://ariakit.org/previews/tooltip
2. Trigger tooltip
3. investigate `--popover-available-height` in dev tools

### Expected behavior

should be the height of the viewport

**Comment by diegohaz** [comment]
The value is correct. It's the available space based on the direction of the popover placement (in this case, top), not the entire viewport.

**Comment by bengry** [comment]
@diegohaz Just a quick follow-up on this, which is somewhat related - am I correct to understand that using [`overflowPadding`](https://ariakit.org/reference/tooltip#overflowpadding) means that the `<Ariakit.Tooltip>` needs to be added a
```css
.tooltip {
  margin: var(--popover-overflow-padding);
}
```
to work as expected, or does `overflowPadding={aNumber}` already does the computation needed so the tooltip will be `{aNumber}px` away from the viewport edge? If so, what is `--popover-overflow-padding` useful for? Besides [this example](
https://ariakit.org/guide/styling#--popover-overflow-padding:~:text=You%20can%20use%20this%20in%20combination%20with%20100%25%20or%20100vw%20values%20to%20make%20the%20popover%20element%20fill%20the%20entire%20viewport%20width%2C%20while%20still%20keeping%20the%20padding) (notice the highlighted text in the link).

**Comment by diegohaz** [comment]
> overflowPadding={aNumber} already does the computation needed so the tooltip will be {aNumber}px away from the viewport edge

This.

You don't need to set a `margin` if you use `overflowPadding`.

**Comment by bengry** [comment]
> You don't need to set a `margin` if you use `overflowPadding`.

Thanks. What about 👇?

> If so, what is `--popover-overflow-padding` useful for? Besides [this example](https://ariakit.org/guide/styling#--popover-overflow-padding:~:text=You%20can%20use%20this%20in%20combination%20with%20100%25%20or%20100vw%20values%20to%20make%20the%20popover%20element%20fill%20the%20entire%20viewport%20width%2C%20while%20still%20keeping%20the%20padding) (notice the highlighted text in the link).
