### ISSUE TITLE
Clicking on esc keyboard elements do not prevent propagation to popover from child elements.

### ISSUE THREAD

**Issue by Eldor901** [ariakit/ariakit#4089]
### Current behavior

Clicking the Esc key on a textarea does not prevent e.stopPropagation() from stopping event propagation to the parent element, resulting in the popover closing.

### Steps to reproduce the bug

1. Open https://stackblitz.com/edit/ariakit-d58rnq?file=src%2FApp.tsx 
2. Click "Accept invite" button
3. Focus on textarea
4. Clicking "Esc" key should not close the popover

### Expected behavior

When a textarea is focused and the Esc key is pressed, the popover component should not close.

**Comment by benrodrs** [comment]
The [`hideOnEscape`](https://ariakit.org/reference/dialog#hideonescape) feature operates during the capture phase, so you can't stop propagation from children. However, this is an implementation detail. The idiomatic way to prevent this is by returning `false` from the function version of this prop:

```jsx
<Dialog hideOnEscape={(event) => event.target !== textareaRef.current}>
```
