### ISSUE TITLE
DisclosureContent: the `animating` state key is not `true` on entry animations.

### ISSUE THREAD

**Issue by DaniGuardiola** [ariakit/ariakit#4115]
### Current behavior

The `animating` state key is not `true` on entry animations, with either `data-enter` + transitions or `data-open` + `@keyframes` animations. This does not happen with exit animations, where it seems to behave appropriately.

### Steps to reproduce the bug

Sandbox: https://stackblitz.com/edit/ariakit-ya9owz?devToolsHeight=33&file=src%2FApp.tsx,src%2Fstyle.css

https://github.com/user-attachments/assets/f2ec538d-9e3a-45e7-931a-02d96a674be6

This sandbox uses CSS transitions but I have also confirmed that it happens with `@keyframes` animations. I can provide another sandbox with it if necessary.

### Expected behavior

The `animating` key is `true` on entry animations.

### Workaround

https://github.com/ariakit/ariakit/issues/4115#issuecomment-2348057706

### Possible solutions

Maybe there's a problem with this logic:

https://github.com/ariakit/ariakit/blob/9584251e9ec6cb2c3e015f1ea45f7cb3b58783b3/packages/ariakit-react-core/src/disclosure/disclosure-content.tsx#L135-L138

**Comment by benrodrs** [comment]
Workaround:

```jsx
<button
  onClick={() => {
    store.setOpen((open) => !open);
    // TODO: Remove when https://github.com/ariakit/ariakit/issues/4115 is fixed
    queueMicrotask(() => {
      store.setState("animating", true);
    });
  }}
>
```
