### ISSUE TITLE
Hovercard should programmatically focus smartly, setting `.focus({ focusVisible: false })` when returning from mouse interactions

### ISSUE THREAD

**Issue by jasikpark** [ariakit/ariakit#4190]
### Motivation

Currently Hovercard, and therefore Menu will focus the MenuButton and have `:focus-visible` styles enabled. I think that should only be the case when the last interaction was via keyboard, rather than when hovering or clicking with a mouse, to match the normal button styles.

### Usage example

Should be default behavior for Menu / MenuButton

### Requirements

- The MenuButton should receive `:focus-visible` focus when the menu is being interacted with via keyboard
- The MenuButon should receive `:focus` focus when the menu is being interacted with via mouse

### Possible implementations

Detect whether the menu is receiving keyboard or mouse events, and then set `focusVisible` in the .focus method accordingly: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#focusvisible

**Comment by benrodrs** [comment]
Hi @jasikpark! Could you provide a screencast or reproduction and share the browser version that demonstrates the focus visible state being added when interacting with the menu using a mouse? I can't reproduce it. It works just as you described it should:

> ### Requirements
> * The MenuButton should receive `:focus-visible` focus when the menu is being interacted with via keyboard
> * The MenuButon should receive `:focus` focus when the menu is being interacted with via mouse

**Comment by jasikpark** [comment]
https://github.com/user-attachments/assets/7e8dd9d4-7905-4993-adbe-2ce54caea659

Absolutely! So this is also in the case of using `openOnHover={true}` and then calling `menuStore.show()` and `menuStore.hide()` when the mouse changes intersecting with the menu button, the menu, and the hidden svg i've put between them as a safe zone

**Comment by benrodrs** [comment]
Thanks! I'm not sure if this is a bug or just how the browser heuristics work. I noticed you were using the keyboard before the mouse, which might be a factor. I'd appreciate a minimal repro on StackBlitz so I can take a closer look.

**Comment by jasikpark** [comment]
Not perfectly minimal, but here's the deets: https://stackblitz.com/edit/vitejs-vite-xmdeaz



https://github.com/user-attachments/assets/82314637-9f72-4c7b-9a7e-9af7eab3c040

**Comment by benrodrs** [comment]
Is there any reason to use a custom `SafeArea` solution instead of relying on Ariakit's hover intent behavior? 

You might also consider using [`[data-focus-visible]`](https://ariakit.org/guide/styling#data-focus-visible) instead of `:focus-visible`.

**Comment by benrodrs** [comment]
Related issue: https://github.com/ariakit/ariakit/issues/3815#issuecomment-2127219983

**Comment by benrodrs** [comment]
> Is there any reason to use a custom `SafeArea` solution instead of relying on Ariakit's hover intent behavior?

To clarify, you can enable the [`hideOnHoverOutside`](https://ariakit.org/reference/menu#hideonhoveroutside) prop on the `Menu` component, eliminating the need for custom `SafeArea` logic. Although the documentation states this prop is `true` by default, I believe this might be an oversight.

Since `hideOnHoverOutside` isn't triggered when the menu or hovercard has focus, it's also advisable to disable the [`focusOnHover`](https://ariakit.org/reference/menu-item#focusonhover) prop on `MenuItem`.

Also, the [`tabbable`](https://ariakit.org/reference/menu-item#tabbable) prop can be useful here, as keyboard users might expect to tab through navigation items.

```jsx
<MenuButton showOnHover />
<Menu hideOnHoverOutside>
  <MenuItem tabbable focusOnHover={false} />
</Menu>
```

With this setup, you will have a widget similar to [Navigation Menubar](https://ariakit.org/examples/menubar-navigation).

**Comment by jasikpark** [comment]
Ah... I assumed that prop would be on MenuButton, didn't think to take a look at Menu 🤦

i'll update things and report back 🫡 

What is the diff between data-focus-visible and :focus-visible?

**Comment by jasikpark** [comment]
Yep, works great! Last question, is there a flag to disable clicking to hide the menu, but allow keyboard interaction? So you don't hover and then click the menu

**Comment by jasikpark** [comment]
Sounds like disabling toggleOnClick and then building my own event handlers *is* the way, as I've done

**Comment by jasikpark** [comment]
I would wish that `:focus-visible` worked instead of needing to use the custom data attribute, but that works fine for me 👍
