### ISSUE TITLE
onSubmit doc versus typing conflict

### ISSUE THREAD

**Issue by agriffis** [ariakit/ariakit#4207]
### Current behavior

The documentation and the type definition seem to be in conflict. Doc says it returns a cleanup function, but typing says it returns void.

### Steps to reproduce the bug

Here is the code in question:

https://github.com/ariakit/ariakit/blob/714961a43eae3846f8265ad9b278090f9a45844e/packages/ariakit-core/src/form/form-store.ts#L532-L546

### Expected behavior

Probably the typing should be updated.

**Comment by benrodrs** [comment]
Thanks! It does seem that the type should be updated.
