### ISSUE TITLE
Change design to support React Compiler

### ISSUE THREAD

**Issue by faradaytrs** [ariakit/ariakit#4238]
### Motivation

We already use React Compiler in production, unfortunately design pattern like that is not supported:
We always get:
````
Hooks must be the same function on every render, but this value may change over time to a different function. See https://react.dev/reference/rules/react-calls-components-and-hooks#dont-dynamically-use-hooks
````
It's eslint warning, warning can be avoided, but react compiler follows similar logic, and nobody can convince it that this reference is actually stable.
### Usage example

````ts
const combobox = useComboboxStore();
const search = combobox.useState("value");
````
or
````ts
const open = select.useState("open");
````

### Requirements

Design patterns shouldn't break react compiler

**Comment by benrodrs** [comment]
Hey @faradaytrs! Have you seen this? https://ariakit.org/changelog#new-usestorestate-hook

**Comment by faradaytrs** [comment]
> Hey @faradaytrs! Have you seen this? https://ariakit.org/changelog#new-usestorestate-hook

wow thank you it worked, awesome
