### ISSUE TITLE
Menu Show / Hide Change in Behavior in 0.14.4 vs 0.14.3

### ISSUE THREAD

**Issue by httpete** [ariakit/ariakit#4247]
### Current behavior

I have a top navigation menu system that is all Ariakit.
    
 This works perfectly in 0.14.3, but in .4, I see the menus overlap awkwardly and show multiple at a time. I see that showOnHover is set to true, but they aren't coming down properly in 0.14.4.

### Expected behavior

Like it did in 0.14.3

### Workaround

https://github.com/ariakit/ariakit/issues/4247#issuecomment-2506083953

### Possible solutions

I think this has something to do with the transition animation, which I set on my mui components to "unset" previously to stop this in earlier versions.

![image](https://github.com/user-attachments/assets/5535780a-90d2-40ea-b53f-ba2dc475f854)

**Comment by httpete** [comment]
Thanks @diegohaz - Was some new [data-leave] styling / attribute adjusted that might be the clue? I have it nailed dead to rights on the version change from .3 to .4.

**Comment by benrodrs** [comment]
Hi @httpete! I reviewed this and other related issues you've had before, and it seems they keep recurring. If you provide a reproduction, we can create an internal example of your use case with tests to ensure this won't break again in the future—or if it does, we'll know exactly why.

Here's an example where we test very specific WordPress use cases in Ariakit to ensure we won't break them: https://github.com/ariakit/ariakit/blob/d955bf36167ff0d9175dd69caac39ae30c9962d3/examples/menu-wordpress-modal/menu.tsx

**Comment by httpete** [comment]
It's been very solid for some time. It is a recursive N level deep Menu system, it was done before the MenuProvider was in Ariakit, so I will try to refactor to that using the [Submenu ](https://ariakit.org/examples/menu-nested#anatomy-of-nested-menus)example as a guide. I am doing what that suggests, iterating over the tree and selectively rendering with the render prop:

```
    <AriaMenuItem
      render={
        itemHasSubmenuItems ? (
          <Menu menuItem={menuItem} />
        ) : (
          <MenuItem onClick={handleOnClick} />
        )
      }
      ```

**Comment by httpete-broadcom** [comment]
I tried raking off all of the render props (which were using Mui ListItem and Mui/Buttons) and it still fails. There is just something going on with the way they come down in .4.  I have a simple case where I loop and call menu.hide() on them and they just come down slowly and overlap.

![image](https://github.com/user-attachments/assets/5a864f44-db62-431f-9aea-ea97ce5f876e)

**Comment by httpete-broadcom** [comment]
I produced this codesandbox, with example code right from yours, and it overlaps exactly the same way.

Hover quickly over "Find" And "Speech" at the link below.

@benrodrs 

https://codesandbox.io/p/sandbox/happy-meninsky-5vvt8v

**Comment by httpete-broadcom** [comment]
![image](https://github.com/user-attachments/assets/b22e6ee3-6a1b-49f5-977b-f31630737394)

**Comment by httpete-broadcom** [comment]
@benrodrs  - Sorry to nudge but this is really going to break a lot of people and I want to raise it to your attention. My proof is solid, it is introduced in this release.

**Comment by bengry** [comment]
@diegohaz Is [this](https://stackblitz.com/edit/1bcaov-pnmxus) the same issue? Downgrading to 0.14.3 fixes it.
If not, please LMK and I'll open a separate issue to track this bug.

**Comment by benrodrs** [comment]
@bengry It's the same issue. I'm working on a fix.

**Comment by benrodrs** [comment]
If you want to upgrade and can't wait for the next release, you can work around this issue by applying this `onMouseLeave` prop to the `*Anchor` or `MenuItem` component that triggers the hovercard or submenu.

```js
  // TODO: Remove when https://github.com/ariakit/ariakit/issues/4247 is fixed
  onMouseLeave={(event) => {
    const view = event.currentTarget.ownerDocument.defaultView;
    const nextEvent = new MouseEvent("mouseleave", {...event, view });
    event.target.dispatchEvent(nextEvent);
  }}
```

**Comment by httpete-broadcom** [comment]
I have to re-open this bug. It is still there in 0.4.15.

**Comment by httpete-broadcom** [comment]
@benrodrs It is still there. I had the old version cached.
