### ISSUE TITLE
Cannot scroll on view in popup

### ISSUE THREAD

**Issue by miketamis** [ariakit/ariakit#469]
### Current behavior
In a popup even if the the div in the popup is scroll: auto; the content is not scrollable on iOS (tested on iPad- iOS 11.3.1 and iPhone 11 Pro iOS 13.2)

Explain what's happening.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/reakit-sci4x on an iOS device
2. Click Open Dialog
3. attempt to scroll coloured blocks
4. Obverse it is unscrollable 

### Expected behavior
Blocks are scrollable

### Environment
iOS

**Comment by diegohaz** [comment]
Looks like `body-scroll-lock` disables all scroll elements except the one it receives as the argument. Not sure if it's a bug or intended behavior. A workaround is to use it on your app and pass your scroll element: https://codesandbox.io/s/reakit-dialog-with-scrollable-content-tx72h

**Comment by zarabotaet** [comment]
sandbox is broken

**Comment by diegohaz** [comment]
@zarabotaet Updated it!

**Comment by zarabotaet** [comment]
Why does no need scroll lock when I use `useDialogState({ modal: false })` ?

**Comment by diegohaz** [comment]
The issue is that we use `body-scroll-lock` (BSL) internally on the `Dialog` component to disable the document body scroll (i.e. the scrolling behind the modal dialog).

But BSL, on touch devices, disables scrolling on everything except the element that has been passed to the `disableBodyScroll`/`enableBodyScroll` functions. In order to allow other elements, we must call these functions on them as well (and that's what the CodeSandbox on my previous comment is doing).

Disabling body scroll isn't a behavior required by non-modal dialogs. So we don't use it when you set `modal` to `false`. Therefore, all scrollable elements are enabled.

**Comment by diegohaz** [comment]
The ideal solution is to get rid of the `body-scroll-lock` dependency and come up with our own solution. This would also fix #505.

**Comment by zarabotaet** [comment]
Maybe for now you can provide scrollRef from useDialog ? And use it like this
```javascript 
const dialog = useDialogState()

<Dialog {...dialog} aria-label="scrollable">
  <div ref={dialog.scrollablelRef}>long content</div>
</Dialog>
```

**Comment by tom-sherman** [comment]
That's an interesting idea, although would only support one scrollable element. It may be better to pass the ref in as an option:

```jsx
const scrollablelRef = React.useRef(null)
const dialog = useDialogState({ scrollableRef })

<Dialog {...dialog} aria-label="scrollable">
  <div ref={scrollablelRef}>long content</div>
</Dialog>
```

**Comment by diegohaz** [comment]
That could be a temporary solution, but I still think that we should get rid of the dependency altogether. I would consider this a bug on `body-scroll-lock` as it only happens on iOS, [but they don't seem to think this way](https://github.com/willmcpo/body-scroll-lock/issues/102). You don't need those additional refs to make it work on desktop browsers, for example.

**Comment by zarabotaet** [comment]
our IOS client is about 50% of total (=

**Comment by navin-moorthy** [comment]
> The ideal solution is to get rid of the `body-scroll-lock` dependency and come up with our own solution. This would also fix #505.

I was going through React-Aria's codebase on how they have approached the body scroll lock, seems they are using thier own hook - `usePreventScroll` - https://github.com/adobe/react-spectrum/blob/c700898916bbd076bcc63e49d77c16d80623a8e7/packages/%40react-aria/overlays/src/usePreventScroll.ts

I hope this helps you if incase haven't looked at this before.

**Comment by diegohaz** [comment]
@navin-moorthy Thanks! I think we can do something like that if that works well on mobile.

**Comment by diegohaz** [comment]
Another reference: https://github.com/adobe/react-spectrum/blob/0ac271ac5508fc6b03e0bd416142aba02546164a/packages/%40react-aria/overlays/src/usePreventScroll.ts

**Comment by netojose** [comment]
Hey, I used this, and worked for me.

https://codesandbox.io/s/reakit-dialog-with-scrollable-content-tx72h?from-embed=&file=/index.js

**Comment by diegohaz** [comment]
It looks like we can replace `body-scroll-lock` with a really simple alternative:
```js
export function usePreventBodyScroll(enabled?: boolean) {
  useLayotuEffect(() => {
    if (!enabled) return;
    const { documentElement } = document;
    const scrollBarWidth = window.innerWidth - documentElement.clientWidth;
    const previousOverflow = documentElement.style.overflow;
    const previousPaddingRight = documentElement.style.paddingRight;
    documentElement.style.overflow = "hidden";
    documentElement.style.paddingRight = `${scrollBarWidth}px`;
    return () => {
      documentElement.style.overflow = previousOverflow;
      documentElement.style.paddingRight = previousPaddingRight;
    };
  }, [enabled]);
}
```

**Comment by netojose** [comment]
I solved with this:

https://codesandbox.io/s/reakit-dialog-with-scrollable-content-tx72h?from-embed=&file=/index.js:1223-1248

**Comment by dkempner** [comment]
> I solved with this:
> 
> https://codesandbox.io/s/reakit-dialog-with-scrollable-content-tx72h?from-embed=&file=/index.js:1223-1248

Note that if you do this workaround on a `<Dialog>` where `modal` is `true`, you'll need to pass `preventBodyScroll` as `false` so that `reakit` doesn't try to prevent body scroll as well.

This would be fixed if we updated `reakit` to use `body-scroll-lock` v4, which solves this for iOS safari.

**Comment by revelict** [comment]
Hi, any action on this topic ?
