### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by diegohaz** [ariakit/ariakit#626]
Opening this issue in case anyone wants to help. Recently, we've configured Storybook to import files from [`__examples__`](https://github.com/reakit/reakit/tree/master/packages/reakit/src/Composite/__examples__) folders inside Reakit component folders. This is how we're doing it:

https://github.com/reakit/reakit/blob/0b70f435673db13b75f82d69ac2760b485879674/.storybook/preview.js#L7-L22

Those files aren't specific to Storybook. They're generic component files that can be used for other things, like [integration testing](https://github.com/reakit/reakit/blob/master/packages/reakit/src/Composite/__examples__/CompositeWithTooltip/__tests__/index-test.tsx) and, in the future, website live examples or [browser testing](https://github.com/reakit/reakit/issues/624).

The idea is to have a single place in the component folder to keep examples that will also work as test cases and stories on Storybook, so we can have a visual representation of the component while we write tests for it.

Also, it's easier to scale than within [our test files with 2700 lines](https://github.com/reakit/reakit/blob/c4d59619f452dd608077857e6c678a91fcfcf87a/packages/reakit/src/Composite/__tests__/index-test.tsx). If someone opens an issue with a reproduction case, we can easily create an example and test it, both in code and in Storybook.

In case you want to create examples, follow these steps:

1. Run `yarn` to install dependencies
2. Run `yarn storybook` to open storybook
3. Run `yarn test --watch` to watch test files
4. Take a look at the [other](https://github.com/reakit/reakit/tree/master/packages/reakit/src/Button/__examples__) [examples](https://github.com/reakit/reakit/tree/master/packages/reakit/src/Tooltip/__examples__) and start writing yours.

**Comment by leonardoelias** [comment]
Vou escrever alguns hoje.

Teria alguma observação sobre o que seria melhor para cada component ?

**Comment by leonardoelias** [comment]
I will write some today.

Do you have any observations about what would be best for each component?

**Comment by diegohaz** [comment]
I've been mostly focusing on how they compose with other components (like `CompositeWithTooltip` or `TooltipWithToolbar`), but I guess anything that could be in the docs could be in examples. `Toolbar` with `Menu`, `Toolbar` with `Popover` etc.

**Comment by frassinier** [comment]
Is there any reason not importing a relative path in the examples? 🤔

**Comment by diegohaz** [comment]
@frassinier Some of those examples will be eventually shown on the website.

![image](https://user-images.githubusercontent.com/3068563/79613310-a94c6680-80d4-11ea-8e5a-3cdb2a204d1c.png)

It would lose a lot of context if it was `import { Button } from "../../Button";`.

**Comment by jsomsanith** [comment]
Hello @diegohaz,
That’s a great initiative. Just a question, why Don’t you put stories files next to the components files ? This would scale better and it’s like tests files, while working on a component you have everything related next to it.

**Comment by jsomsanith-tlnd** [comment]
Nevermind, I misunderstood, I thought you were putting all the stories files in a unique example folder. @frassinier told me my mistake.

**Comment by lluia** [comment]
@diegohaz happy to help with this, it's been a while since I contributed to **Reakit**, would you like me to rescue https://github.com/reakit/reakit/pull/402 as well? ( _it was close due to inactivity but have quite some free time now_ 👍🏻 )

**Comment by diegohaz** [comment]
@lluia Please! 😊I re-opened the PR and I'll comment there.

**Comment by diegohaz** [comment]
Closing in favor of #939
