### ISSUE TITLE
More configurability for tooltip

### ISSUE THREAD

**Issue by dipunm** [ariakit/ariakit#653]
### Motivation
This is kinda a couple of features/bugs.

#### Bug 1:
As per https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html.
> Another common situation is when large pointers have been selected via platform settings or assistive technology. Here, the pointer can obscure a significant area of the additional content. A technique to view the content fully in both situations is to move the mouse pointer directly from the trigger onto the new content.

In some cases, it is important to allow the tooltip to be hovered over without it being dismissed. I found that the tooltip cannot overlap the target element even with offset:
```js
// add this to the first example on: https://reakit.io/docs/tooltip/
const tooltip = useTooltipState({
    placement: 'bottom',
    unstable_offset: [-25]
});
```
and that even when close, the tooltip cannot be hovered over without disappearing.

#### Bug 2:
As per https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html.
> Once it appears, the content should remain visible until:
> - The user removes hover or focus from the trigger and the additional content, consistent with the typical user experience; 

This one is more subtle, but I observed that if an element obtains focus, and then the cursor passes by, the tooltip will disappear. This is a little annoying for me since I don't want that behaviour, the user can already dismiss the tooltip with esc. Maybe this could be a configurable thing, but the way I see it, if the tooltip was triggered by keyboard, it should be dismissed by keyboard and vice-versa -- the exception being that esc should always work.

Might it be a good idea to open the api a little to allow more control of when the tooltip shows and hides? (eg, adding a short delay or even custom touch based logic)

### Example

Apart from the w3 examples, I want to use a transparent tooltip that hovers over a textarea to indicate that the user can press Ctrl+Enter to submit. 
- If the user mouses over the textarea, the default behaviour is fine. 
- If a user tabs to the input, I want the tooltip to persist until esc is hit regardless of mouse activity. 
- If the mouse triggered the tooltip and focus by tab came after, I think it is sensible to remove the tooltip on mouse out.
- If the user touches the inputbox, I don't want to see the tooltip as it is likely not relevant to the user (touch users typically don't have key modifiers so it might be confusing and the submit button is likely more convenient).

### Possible implementations

If possible, describe how this feature could be implemented. See [CONTRIBUTING.md](https://github.com/reakit/reakit/blob/master/CONTRIBUTING.md).

**Comment by diegohaz** [comment]
> This one is more subtle, but I observed that if an element obtains focus, and then the cursor passes by, the tooltip will disappear. This is a little annoying for me since I don't want that behaviour, the user can already dismiss the tooltip with esc. Maybe this could be a configurable thing, but the way I see it, if the tooltip was triggered by keyboard, it should be dismissed by keyboard and vice-versa -- the exception being that esc should always work.

I think I agree with this. I'm pretty sure this can be done in user land by using the [composition patterns](https://reakit.io/docs/composition/) on Reakit. But that would be good if we had this behavior built into the library as well.

But, what if the user mouses over another element that triggers another tooltip? What would happen?

**Comment by dipunm** [comment]
I had a similar thought, I think it could be solved by having a tooltip context designed to coordinate the closing of the tooltip, but I'm not entirely sure of the accessibility concerns with auto closing.

I think allowing tooltips to live in a named pool should be plenty flexible. Tooltips can either be part of the default pool and close when a peer tooltip opens, or be part of its own pool and coexist with other tooltips.
