### ISSUE TITLE
Tabbable onFocusVisible prop

### ISSUE THREAD

**Issue by diegohaz** [ariakit/ariakit#737]
### Motivation

There are cases where we want to perform actions on focus, but not when focus is triggered by a pointer event.

For example: https://github.com/reakit/reakit/pull/633#discussion_r488117927

### Example

```jsx
const [show, setShow] = React.useState(false);
<Tabbable onFocusVisible={() => setShow(true)} onBlur={() => setShow(false)} />
{show && <div />}
```

### Possible implementations

Maybe checking mouse and keyboard events before focus and only triggering `onFocusVisible` when it's preceded by a keyboard event? I don't know.

**Comment by Weffe** [comment]
Can probably reference the work done on the [focus-visible polyfill](https://github.com/wicg/focus-visible) as it's pretty well documented. 

I use it in my company's project and have no issues with it. Extracting out the javascript code into a hook might not be that bad.

**Comment by mirka** [comment]
I have a working prototype that I'll PR soon ✋
