### ISSUE TITLE
RFC: Hybrid implicit/explicit state

### ISSUE THREAD

**Issue by diegohaz** [ariakit/ariakit#745]
I'm creating this issue to propose an enhancement over how we pass state to components. Instead of having to pass it for all components, we would only need to pass it to the top-level ones.

For example, currently we have to pass the state to all instances of `MenuItem` inside `Menu`:

```jsx
const state = useMenuState();

<MenuButton {...state}>Open menu</MenuButton>
<Menu {...state}>
  <MenuArrow {...state} />
  <MenuItem {...state}>Item 1</MenuItem>
  <MenuItem {...state}>Item 2</MenuItem>
  <MenuSeparator {...state} />
  <MenuItem {...state}>Item 3</MenuItem>
</Menu>
```

I'm proposing that we improve this so we don't *need* to explicitly pass state to `MenuItem` instances anymore. It would leverage React Context and subscribe to state changes internally.

```jsx
const state = useMenuState();

<MenuButton {...state}>Open menu</MenuButton>
<Menu {...state}>
  <MenuArrow />
  <MenuItem>Item 1</MenuItem>
  <MenuItem>Item 2</MenuItem>
  <MenuSeparator />
  <MenuItem>Item 3</MenuItem>
</Menu>
```

**Note**: `MenuItem` should keep accepting state being passed directly as props for [this reason](https://twitter.com/diegohaz/status/1229499934845607936). But it wouldn't be required anymore.

## Motivation

Besides being easier to write code like that, it would also make it easier to [colocate state](https://twitter.com/diegohaz/status/1307299869200191490).

In our `Menu` example, all `MenuItem` components will re-render when `state` gets updated. But if we abstract the state into a separate component that receives `children`, they won't re-render:

```jsx
import {
  useMenuState,
  Menu as BaseMenu,
  MenuButton,
  MenuItem,
} from "reakit/Menu";

function Menu({ button, ...props }) {
  const state = useMenuState();
  return (
    <React.Fragment>
      <MenuButton {...state} ref={button.ref} {...button.props}>
        {(buttonProps) => React.cloneElement(button, buttonProps)}
      </MenuButton>
      <BaseMenu {...state} {...props} />
    </React.Fragment>
  );
}

function App() {
  return (
    <Menu button={<button>Open menu</button>}>
      <MenuItem>Item 1</MenuItem>
      <MenuItem>Item 2</MenuItem>
      <MenuItem>Item 3</MenuItem>
      ...
      <MenuItem>Item 500</MenuItem>
    </Menu>
  );
}
```

**Comment by tom-sherman** [comment]
I like this for the simple fact that it's non obvious how to create this in userland in a maintainable way at the moment. More specifically I don't think it's intuitive which props would need to be put into context. I guess you could read _keys but that seems hacky?

I find it interesting how this proposal interacts with #744. On one hand #744 makes it easier to accomplish this RFC in userland, but on the other hand I think this RFC is easier to teach/learn/document in combination with #744. You would just have to know "the singular state prop is passed down via context automatically"

**Comment by tom-sherman** [comment]
Forgetting #744 for now, would this proposal support passing some state values as props and grabbing some from context? Which one takes priority?

I have concerns about how this could be implemented in a performant way, although I'm not 100% sure how valid these concerns are. Right now the state props are memoized, so don't cause a rerender of the component when they are the same. How is this possible when supporting both props and context at the same time?

**Comment by diegohaz** [comment]
> Forgetting #744 for now, would this proposal support passing some state values as props and grabbing some from context? Which one takes priority?

I don't think it should be supported. This would make the implementation a lot more complex and if we go for #744 this wouldn't work at all.

**Comment by diegohaz** [comment]
> I have concerns about how this could be implemented in a performant way, although I'm not 100% sure how valid these concerns are. Right now the state props are memoized, so don't cause a rerender of the component when they are the same. How is this possible when supporting both props and context at the same time?

There are two situations where I think the state props would still be used on inner components:

1. When you can't access the context because components are in different subtrees (like in [the WordPress SlotFill case](https://twitter.com/diegohaz/status/1229499932505264136)).
2. When you want to benefit from [types based on the state](https://twitter.com/diegohaz/status/1128547623684726784).

The implementation I imagine being something like this (simplified and considering #744):

```jsx
function CompositeItem({ state: stateFromProps, ...props }) {
  const context = React.useContext(CompositeContext);
  const state = stateFromProps || context;
  ...
}
```

The problem with passing context this way is that you can't bail out from rendering based on context slices. That is, this component would re-render every time the composite state is updated, even when the change doesn't affect the component. With props, we can just use `React.memo`:

https://github.com/reakit/reakit/blob/6f6d1ad9177156cafa4adf9c987a43c79a1bbb90/packages/reakit/src/Composite/CompositeItem.ts#L88-L110

But I would like to try it with a subscription-based state (which is what's being done in the [here](https://twitter.com/diegohaz/status/1307299869200191490)).

Instead of returning a new context value every time the state gets updated, we would return only the initial state with a  `subscribe` method. This way, the consumer (say `CompositeItem`) would be able to listen to specific parts of the state:

```jsx
function CompositeItem({ state: initialState, ...props }) {
  const initialContext = React.useContext(CompositeContext);
  const [state, setState] = React.useState(initialState || initialContext);

  React.useEffect(() => {
    return state.subscribe((prevState, nextState) => {
      if (props.id === prevState.currentId || props.id === nextState.currentId) {
        // It means that this element is the previous or the next focused item, so we
        // should re-render it with updated state.
        setState(nextState);
      }
    });
  }, [state.subscribe, props.id]);

  ...
}
```

Both `state` from props and from context would have this `subscribe` method, so we could just ignore other state changes.

Even in `React.memo`:

```jsx
function propsAreEqual(prev, next) {
  const { state: prevState, ...prevProps } = prev;
  const { state: nextState, ...nextProps } = next;
  return shallowEqual(prevProps, nextProps);
}
```

There are two things I'm concerned though:

- Concurrent mode. But this [CodeSandbox example](https://codesandbox.io/s/reakit-combobox-performance-9zxv6?file=/src/Combobox.js) is using concurrent mode and everything seems to work fine. If this becomes a problem, I think we could leverage `useMutableSource`.

- Although I think it would be a very rare case, what if the user wants to pass a different `state` object after the first render? In the implementation I shared above it wouldn't work.

Anyway, I think this context-based state is only worth it if we can use this subscription-based state.

**Comment by agriffis** [comment]
Interesting. I've been wrapping Reakit components for my own internal projects, effectively #744 and #745 combined:

```javascript
const MenuContext = React.createContext()

export const Menu = ({state, ...props}) => (
  <MenuContext.Provider value={state}>
    <RK.Menu {...state} {...props} />
  </MenuContext.Provider>
)

const MenuItem = ({state, ...props}) => {
  const context = React.useContext(MenuContext)
  return <RK.MenuItem {...(state || context)} {...props} />
}

const MenuSeparator = ({state, ...props}) => {
  const context = React.useContext(MenuContext)
  return <RK.MenuSeparator {...(state || context)} {...props} />
}

const MenuTrigger = ({state, ...props}) => {
  const context = React.useContext(MenuContext)
  return <RK.MenuButton {...(state || context)} {...props} />
}

// etc.
```

**Comment by tom-sherman** [comment]
@agriffis out of interest, how are you currently seperating props and state?

**Comment by agriffis** [comment]
@tom-sherman I'm not sure I understand the question. With my wrappers, only `<Menu />` receives the state prop, i.e. the result of `useMenuState`. The sub-components generally don't receive a state prop, so they fall back to the menu state in context. But since these are just wrappers, I still have to spread that into the wrapped components for now.
