### ISSUE TITLE
Firefox automatically select first menu item on Space for opening menu

### ISSUE THREAD

**Issue by h4m3d** [ariakit/ariakit#814]
### Current behavior

Firefox automatically select first menu item on Space for opening menu. it actually occurs when we release Space.

### Steps to reproduce the bug

with Firefox go to menu action example https://reakit.io/docs/menu/#menu-actions
1. put focus on the Menu
2. press space on the menu button
3. on release of space it automatically select first menu item so it closes the menu

### Expected behavior

like chrome it must just open the menu and not select any item

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: Linux 5.9 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 7.88 GB / 11.13 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 15.5.0 - /usr/bin/node
    npm: 6.14.10 - /usr/bin/npm
  Browsers:
    Firefox: 84.0.1
  npmPackages:
    react: ^17.0.1 => 17.0.1 
    react-dom: ^17.0.1 => 17.0.1 
    reakit: ^1.3.2 => 1.3.2
```

**Comment by diegohaz** [comment]
Thanks for reporting it @h4m3d!

This actually also happens on Chrome, but you need to press Space for a little longer.

I haven't tested it yet, but my guess is that we should check for `event.repeat` here:
https://github.com/reakit/reakit/blob/bf3fdfdfa511f8f09edf8f5c55ed691a9b592ad8/packages/reakit/src/Clickable/Clickable.ts#L86-L88

**Comment by diegohaz** [comment]
This should be fixed in the latest version of `@ariakit/react`.
