### ISSUE TITLE
input with `autoFocus` inside Dialog breaks returned focus

### ISSUE THREAD

**Issue by everdimension** [ariakit/ariakit#855]
## 🐛 Bug report

I have my component composed like this:

```
<ReakitDialog {...dialog}>
  {dialog.visible ? <SomeFormWithInputWithAutofocus /> : null}
</ReakitDialog>
```

### Current behavior
If a component inside `<Dialog />` has an input with `autoFocus={true}`, I get the desired behavior where the input gets focused when I open the dialog, but when I close the dialog, the focus no longer returns back to the disclosure button that was used to open the dialog.

### Steps to reproduce the bug

Provide a repo or sandbox with the bug and describe the steps to reproduce it.

1. https://codesandbox.io/s/beautiful-cache-cnuc1?file=/index.js
2. Open dialog, then close it
3. The "open dialog" button is not focused

**Comment by diegohaz** [comment]
Thanks for reporting @everdimension!

A workaround is to programmatically focus the input using a React effect:

```jsx
useEffect(() => {
  if (dialog.visible && inputRef.current) {
    inputRef.current.focus();
  }
}, [dialog.visible]);
```

**Comment by everdimension** [comment]
@diegohaz Thank you, I'll try it where I can, but this is still a bug that I wish could be fixed.

The idea is that the component inside the dialog may not be aware that it is rendered inside the dialog.

**Comment by diegohaz** [comment]
I agree with you that this should be fixed.

As for the workaround, you would basically put the effect in the same place you would use the `autoFocus` prop.

So, instead of doing this:

```jsx
<input autoFocus />
```

You would do this:

```jsx
const ref = useRef();
useEffect(() => {
  ref.current.focus();
}, []);
<input ref={ref} />
```

So it doesn't need to be aware of the dialog.
