### ISSUE TITLE
Dialog doesn't allow interaction with 1password browser extension

### ISSUE THREAD

**Issue by ajosedev** [ariakit/ariakit#863]
### Current behavior

When focusing on an input field inside of a Dialog, interaction to the [1password browser extension](https://addons.mozilla.org/en-US/firefox/addon/1password-x-password-manager/)'s tooltip is seemingly blocked, and focus is moved to elsewhere. I've observed this in both Firefox and Chrome.
This may be a bug specific to this specific extension, or one that's more general to any extension with a similar design.

### Steps to reproduce the bug

Provide a repo or sandbox with the bug and describe the steps to reproduce it.

1. Open sandbox: https://codesandbox.io/s/festive-euler-m49wt?file=/src/App.js
2. Focus the 'password' field
3. Try to interact with the 1password tooltip

https://user-images.githubusercontent.com/29142528/116166312-11e70e00-a741-11eb-9050-07cabe870db9.mp4

### Expected behavior

Clicks should pass through to the 1password tooltip, allowing navigation of the browser extension.

### Possible solutions

I've tried to debug with not much success, but my best guess is that the `useFocusOnBlur` function doesn't see the tooltip as an actual element (`isActualElement`), so focus is returned to the dialog instead.

Some other things I've tried that may be helpful:
- Passing `modal={false}` to the Dialog has no effect. This allows focus to escape the modal, but focus is still not passed to the tooltip
- Passing `hideOnClickOutside={false}` also does nothing
- Removing `tabindex` from the DOM of the `role=dialog` fixes the problem. Changing the `tabindex` to any other number seems to do nothing.

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 225.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 90.0.4430.85
    Firefox: 87.0
    Firefox Developer Edition: 88.0
    Safari: 14.0.3
  npmPackages:
    react: ~16.9.0 => 16.9.0
    react-dates: ^16.3.6 => 16.3.6
    react-dom: ~16.9.0 => 16.9.0
    react-dropzone: ^10.1.4 => 10.1.4
    react-google-recaptcha: ^2.1.0 => 2.1.0
    react-helmet-async: ^1.0.7 => 1.0.7
    react-hook-form: ^6.0.8 => 6.0.8
    react-hot-loader: ^4.6.0 => 4.12.11
    react-image-crop: ~8.3.0 => 8.3.1
    react-intl: ^5.13.5 => 5.13.5
    react-is: 17.0.1 => 17.0.1
    react-keyed-flatten-children: ^1.3.0 => 1.3.0
    react-responsive: ^8.2.0 => 8.2.0
    react-router: ^5.1.2 => 5.2.0
    react-router-dom: ^5.1.2 => 5.2.0
    react-select: ^3.0.4 => 3.1.1
    react-slider: ^1.0.0 => 1.0.0
    react-sortable-hoc: ~1.7.0 => 1.7.1
    react-spring: ^8.0.27 => 8.0.27
    react-swipeable: ^5.2.1 => 5.4.0
    react-text-truncate: ^0.16.0 => 0.16.0
    react-textarea-autosize: ^7.1.0 => 7.1.0
    react-transition-group: ^2.9.0 => 2.9.0
    react-visibility-sensor: ^5.1.1 => 5.1.1
    react-waypoint: ^9.0.3 => 9.0.3
    reakit: ^1.3.6 => 1.3.6
```

Copied from https://github.com/reakit/reakit/discussions/862

**Comment by cnairiwttj** [comment]
Hello!

I'm currently facing the same issue, using the `Dialog` component. I can't fill my password field using the 1password tooltip.

The workaround found by @ajosedev and also used by @nicolasvienot is also working for me.

But could you please inform me if you found any more satisfying solution please? 

Thanks a lot, have a nice day.

**Comment by sarfata** [comment]
Took me a while to figure out how to apply the "tabIndex='none'" to the Dialog container element. If you are using Material UI 4 you can use:
```
  <Dialog
      TransitionProps={{ tabindex: "none" } as any}
    >
```
See https://github.com/mui/material-ui/blob/v4.x/packages/material-ui/src/Dialog/Dialog.js#L234

And sorry for hijacking this project with an issue that is more of a material-ui problem IMHO.

**Comment by diegohaz** [comment]
Closing as the original issue will be fixed in v2: https://codesandbox.io/s/frosty-goldberg-q4qih0?file=/src/App.js

**Comment by dkempner** [comment]
hey @diegohaz do you recall what your fix was in v2. i'm having a similar issue and can't update to v2 now so i'm trying to backport the fix.

**Comment by dkempner** [comment]
It's looking like a workaround for v1.3.7 is to throw an error in the `onBlur` event of the Dialog. This prevents the callback from `useFocusOnBlur` from firing, which means we never force a focus.

```tsx
export default function App() {
  const dialog = useDialogState({ visible: true });
  return (
    <div>
      <Dialog
        state={dialog}
        aria-label="Welcome"
        hideOnClickOutside={false}
        onBlur={() => {
          throw new Error("Intentionally throwing");
        }}
      >
        <Form />
      </Dialog>
    </div>
  );
}
```
