### ISSUE TITLE
Tooltips need to follow wcag 1.4.13 - allow hovering over tooltip

### ISSUE THREAD

**Issue by samsch** [ariakit/ariakit#887]
## 🐛 Bug report

The tooltip component needs to default to allowing the user to hover over the popup without it being dismissed.

https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html

### Current behavior

Currently, when you attempt to hover over the pop up, it disappears (as you are no longer hovering over the trigger).

### Steps to reproduce the bug

Can be demonstrated in the Tooltips doc page: https://reakit.io/docs/tooltip/

### Expected behavior

When moving your cursor from the trigger to the pop op, it should remain visible (and probably allow you to select the text inside).

### Possible solutions

Sorry, I'm not familiar with the code base.

### Environment

N/A

**Comment by samsch** [comment]
Bumping, as this is still a valid issue.

**Comment by ivanov-v** [comment]
Hello. I also have a need to hover the tooltip, because it has interactive content. For example link or button.
<img width="501" alt="image" src="https://user-images.githubusercontent.com/13759065/159219458-4b16b6c7-6ba9-453c-8a51-486d44031665.png">

**Comment by diegohaz** [comment]
@ivanov-v Tooltips shouldn't contain interactive content. You're talking about another concept which is usually called "hovercard". There will be a Hovercard component in v2: https://ariakit.org/examples/hovercard

**Comment by ivanov-v** [comment]
> @ivanov-v Tooltips shouldn't contain interactive content. You're talking about another concept which is usually called "hovercard". There will be a Hovercard component in v2: https://ariakit.org/examples/hovercard

Cool! Can you tell me when it will be safe to use it in production?

**Comment by diegohaz** [comment]
@ivanov-v Sorry for the delay. You'll find more information on [Should I use Ariakit (v2) or Reakit (v1) now?](https://gist.github.com/diegohaz/bc07491aee61a5f2469574b38c5c1aa0#should-i-use-ariakit-v2-or-reakit-v1-now).
