### ISSUE TITLE
RFC: Simplify component child imports

### ISSUE THREAD

**Issue by brianespinosa** [ariakit/ariakit#894]
## 🚀 Feature request

Include all sub-components for a given component type from the base component export.

> This suggestion is inspired in part due to other optimization RFCs to make passing state hooks to a singular state prop, as well as [proposals of having to only pass state to the highest parent component](https://github.com/reakit/reakit/issues/745) instead of spreading the state to all components. It is also based on [prior art over at Semantic UI React](https://github.com/Semantic-Org/Semantic-UI-React).

### Motivation

Today we have to import all child components we are using for any given component. In some real world scenarios, this can lead to lengthy lists of import members. If implementation details change, those import members need to get updated, etc. It seems like we could simplify this significantly by only asking developers to import the base component. This is how our imports work as of today:

```jsx
import { Button } from "reakit/Button";
import {
  useTooltipState,
  Tooltip,
  TooltipArrow,
  TooltipReference,
} from "reakit/Tooltip";
import { useTabState, Tab, TabList, TabPanel } from "reakit/Tab";

// or

import {
  Button,
  useTabState,
  useTooltipState,
  Tab,
  TabList, 
  TabPanel, 
  Tooltip,
  TooltipArrow,
  TooltipReference,
} from "reakit";
```

### Example

It would be nice from a developer experience to simply be able to import the base component alone and attach all the child components to it for easy use like this:

```jsx
import { Button } from "reakit/Button";
import { useTooltipState, Tooltip } from "reakit/Tooltip";
import { useTabState, Tab } from "reakit/Tab";

// or

import {
  Button,
  useTabState,
  useTooltipState,
  Tab,
  Tooltip,
} from "reakit";

function Example() {
  const tab = useTabState();
  const tooltip = useTooltipState();
  return (
    <>
      <Tab.List {...tab} aria-label="My tabs">
        <Tab {...tab}>Tab 1</Tab>
        <Tab {...tab} disabled>
          Tab 2
        </Tab>
        <Tab {...tab}>Tab 3</Tab>
      </Tab.List>
      <Tab.Panel {...tab}>
        <Tooltip.Reference {...tooltip} as={Button}>
          Reference
        </Tooltip.Reference>
        <Tooltip {...tooltip}>
          <Tooltip.Arrow {...tooltip} />
          Tooltip
        </Tooltip>
      </Tab.Panel>
      <Tab.Panel {...tab}>Tab 2</Tab.Panel>
      <Tab.Panel {...tab}>Tab 3</Tab.Panel>
    </>
  );
}

```

### Possible implementations

We could essentially import all child components in the base component and then attach them to the default export:

```jsx
// Tooltip.js

import TooltipArrow from './TooltipArrrow',
import TooltipReference from './TooltipReference',

const Tooltip = () => { // stuff }

Tooltip.Arrow = TooltipArrow;
Tooltip.Reference = TooltipReference;

export default Tooltip;
 
```

- We would likely also want to change `displayName` on each of the child components so they present themselves as `<Tooltip.Arrow>` in devtools. 
  - We could still export all subcomponents preserving the existing API.
  - We could leave the displayName unchanged if the component was imported directly using the existing API.
- This might have an impact on tree shaking for people that might not be using all subcomponents (like TooltipArrow)
  - We might be able to alleviate that by using the dynamic import syntax for subcomponents so they will get tree shaken by bundlers 

---

Finally, @diegohaz thank you for all the work you have put into this project and your focus on accessibility. 

*Edited by @diegohaz: Added code syntax highlight.*

**Comment by diegohaz** [comment]
Thanks for writing this RFC Brian!

For context, in the earliest versions of Reakit, before React hooks existed, we used to follow that approach. Here's an example of the Tab components: https://v0.reakit.io/components/tabs

As you've already mentioned, one of the biggest reasons for changing that was those sub-components wouldn't get tree shaken. As we add more optional sub-components, this would become a bigger problem. For example, I'm currently working on components like `CompositeTypeahead`, `CompositeContainer` and `CompositeInput` that serve very specific purposes that just a few people would need, but, added together, they could significantly impact the bundle size.

Other examples of optional sub-components that are in the works are `DialogHeading`, `DialogDismiss`, `DialogDescription` (and equivalent sub-components for Popover), and more.

How does the dynamic import syntax could help with that?

That being said, you can do this today:
```jsx
import * as Tabs from "reakit/Tab";

const tab = Tabs.useTabState();

<Tabs.TabList>
  <Tabs.Tab />
</Tabs.TabList>
<Tabs.TabPanel />
```

That's a bit more verbose than what you're suggesting, but the result is pretty much the same.

**Comment by brianespinosa** [comment]
> How does the dynamic import syntax could help with that?

My understanding was that the dynamic import syntax would help split the components when using a bundler like Webpack or Parcel. I know this will generate separate chunks in the build of an application. I wanted to do some reading to be clear on this, and it seems in our case, chunk splitting and tree shaking can be related, but not necessarily equal.

I went to look and see if there was a way we could leverage the dynamic import syntax to allow tree shaking without also [relying on vendor specific annotations](https://github.com/webpack/webpack.js.org/issues/2684) ([or this](https://webpack.js.org/guides/tree-shaking/#mark-a-function-call-as-side-effect-free))... but so far, it seems like this is not the case. These child components would never get tree shaken because they are always being imported. So... this RFC might be dead unless/until bundlers are able to more deeply analyze dependencies.
