### ISSUE TITLE
Tab: Add option to not activate tab on mousedown

### ISSUE THREAD

**Issue by Leimi** [ariakit/ariakit#919]
:wave: Thanks for Reakit :)

### Current behavior

When using the tab components, clicking a `<Tab>` with the mouse instantaneously triggers the tab change, on _mousedown_.

### Steps to reproduce the bug

The problem is visible on [the documentation page](https://reakit.io/docs/tab/#usage).

### Expected behavior

The change should trigger on _mouseup_, as it is the normal behavior of a button.

### Possible solutions

I think this issue is here because the [`focus` event is used](https://github.com/reakit/reakit/blob/master/packages/reakit/src/Tab/Tab.ts#L78), and the browser internally triggers it on `mousedown`.  In the end, with a mouse click, before the actual `onClick` handler is called, the `onFocus` is called and selects the tab.

I'm not really familiar with the Reakit source code (yet?) so I didn't think of a specific solution.

Do you first agree this behavior should be changed?

Thanks

**Comment by diegohaz** [comment]
That's expected. Tabs should be activated on focus unless you pass `{ manual: true }` to `useTabState`.

**Comment by Leimi** [comment]
Oh, I didn't mean at all that it shouldn't be activated on keyboard focus. I meant keyboard focus shouldn't change the normal mouse interaction.

Here for example an implementation where mouse clicking is handled as usual (meaning, the tab change is triggered on _mouseup_ and not on _mousedown_), while still handling keyboard focus: https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html

**Comment by diegohaz** [comment]
Sorry, I guess I don't understand your use case then. Could you elaborate more on that?

**Comment by diegohaz** [comment]
I'm changing the type of the issue to feature request, because it's not really a bug. This behavior is aligned with other tabs out there (for example, Google Chrome, VSCode etc.). And the [WAI-ARIA pattern](https://www.w3.org/TR/wai-aria-practices-1.1/#keyboard-interaction-19) doesn't mention any specific difference between keyboard focus and mouse focus. It treats focus generically:

> It is recommended that tabs activate automatically when they receive focus as long as their associated tab panels are displayed without noticeable latency.

**Comment by Leimi** [comment]
There is no use-case per say, but more a desire to be consistent with usual HTML buttons behavior. Since a button pretty much never triggers its action on mouse press, but on mouse release, it feels weird that this behavior is changed because of focus handling. We do not expect the button to act like this. For example, I expect to be able to "change my mind" after clicking the button, by holding the click and moving out of the button, in order to prevent triggering its action. I can't do that here because the default behavior is changed.

I understand there is no distinction in the spec between keyboard or mouse focus but I feel like it's assumed we talk about keyboard when we talk about focus. And the "official" WAI-ARIA example does show what I mean: the tab changes on mouse click but with usual click behavior.

Chrome or VSCode tabs can behave differently, I feel the idea here is more to be consistent with usual web-content, not with any tabs defined in any software UI. If I see a button on the web, I expect it to behave like a web button, I don't expect it to work like Chrome tabs.

I know this is a bit nitpicky though haha.

**Comment by Leimi** [comment]
Yeah, I agree about the semantics and all but I don't know, just noticed this as a user myself, it felt weird to have a clickable thing on a web page that triggered a bit differently than usual.

Thanks for the workaround idea!
