### ISSUE TITLE
When MenuBarState has orientation "vertical" arrow navigation doesn't work the way it does in horizontal.

### ISSUE THREAD

**Issue by httpete** [ariakit/ariakit#996]
### Current behavior

When I navigate to the Menubar example with tabs, the arrow keys take over and it works great. I can go up / down / left / right.
But when the orientation is vertical, I can go through the menus fine, but when I go back to the top level buttons it loses focus.

### Steps to reproduce the bug

Due to corporate firewall rules, I can't use the stackblitz or codesandbox.

### Expected behavior

Arrow behavior / focus behavior like it does in Horizontal mode, just in vertical orientation add orientation="vertical" to the MenuBar.

**Comment by httpete** [comment]
I am trying this with ariakit as well, and it is the same. If you use keyboard arrows to go into a menu, and then try to go down or left you can't navigate like you can in horizontal mode.

**Comment by diegohaz** [comment]
@httpete Are you able to create a CodeSandbox now?

**Comment by httpete** [comment]
I am trying gitpod. Can you see this?

https://gitpodio-templatetypescr-4zxvldvg1h2.ws-us30.gitpod.io

**Comment by diegohaz** [comment]
Thanks! I can reproduce it now. I'll take a better look into the actual issue later. For now, you can add your own keydown handler to the `Menu` component. Something like this:
```jsx
<Menu
  onKeyDown={(event) => {
    if (event.key === "ArrowLeft") {
      menu.hide();
    }
  }}
>
```

**Comment by httpete** [comment]
I am also seeing a difference when orientation=vertical when it comes to showOnMouseMove and toggleOnClick={false}. My goal is to have one and only one menu up at a time, upon hovering. In horizontal mode it works fine, in vertical if I hover in the menu and directly into another button, I see menus overlap.

**Comment by httpete** [comment]
I can report that on the latest alpha19 this is fixed!
